### ISSUE TITLE
PHP 5.6.13 for Windows - DOMNode::cloneNode(): ID already defined warning

### ISSUE THREAD

**Issue by garethellis36** [dompdf/dompdf#1027]
I have just updated to PHP 5.6.13 (for Windows - NTS, VC11 x86) and have started getting this warning in my application logs. This issue was not happening prior to updating PHP (was previously on 5.6.6) and I have not changed any application code. I am using DOMPDF v0.6.1 installed via composer.

I am able to reproduce on my development machine. The warning is thrown on calling `DOMPDF::render()`. Below is the HTML I am inserting using `DOMPDF::load_html()`.

I am getting two warnings:

```
Warning (2): DOMNode::cloneNode(): ID header already defined [APP\Vendor\dompdf\dompdf\include\frame_decorator.cls.php, line 128]
Warning (2): DOMNode::cloneNode() [domnode.clonenode]: ID footer already defined [APP\Vendor\dompdf\dompdf\include\frame_decorator.cls.php, line 128]
```

As you can see, there is only one element with ID "header" and one with ID "footer".

```html
<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<style>
		@page { margin: 60px 50px 35px; }
    	#header { position: fixed; left: 0px; top: -45px; right: 0px; height: 50px; text-align: center; }
    	#footer { position: fixed; left: 0px; bottom: -15px; right: 0px; height: 50px; text-align: center; border-top: 1px solid black; }
    	/*#footer .footer-message:after { content: "Page " counter(page); }*/
		body { font: 12px "Calibri", "Helvetica", "Sans-Serif"; }
		th, td, p { font: 12px "Calibri", "Helvetica", "Sans-Serif"; }
		p { line-height: 1.5; page-break-inside:avoid; }
		.title { font-size: 16px; }
		table { margin-bottom: 10px; }
		thead th { font-weight: bold; }
	</style>
	</head>

	<body>
			<div id="header">
			</div>
			<div id="footer">
			</div>
	</body>
</html>

**Comment by bsweeney** [comment]
When updating PHP did libxml also update? Do you know what version is on your system (you can check `phpinfo()`)?

**Comment by bsweeney** [comment]
To work around the issue for the time being you can style using classes rather than IDs.

**Comment by garethellis36** [comment]
@bsweeney - thanks for the workaround, that solves the problem.

Per `php -i`:  In PHP 5.6.6, libxml is v2.91. In PHP 5.6.13, libxml is v2.9.2.

**Comment by bsweeney** [comment]
I believe the error is thrown because of rules triggered by using `DomDocument::load_html`, but this might be an issue specific to the version of libxml. Really need to do some more research into what's going on.

We could disable libxml exceptions using [`libxml_use_internal_errors()`](http://php.net/libxml-use-internal-errors) though that seems a bit extreme.

Since what's thrown is a warning processing of the PDF should be able to continue, so you could disable error reporting (or at least warnings) before processing the document. If that's not an option you could also call the `libxml_use_internal_errors()` function before using dompdf.

**Comment by garethellis36** [comment]
Yes, I found that the PDFs were still generating OK, but our errors logs were getting flooded with the warnings as this action is carried out many times per day.

Styling using classes is a fine workaround for this particular case as the HTML is so simple - it just required edits to four lines in the template. Thanks!

**Comment by bsweeney** [comment]
Thanks for the updates. We'll keep an eye on where libxml goes with this. It's likely we'll want to implement some kind work around in the code.

**Comment by ThomasLandauer** [comment]
I have the same issue with Cpdf and Symfony:
`Warning: DOMNode::cloneNode(): ID logo already defined`
Symfony treats this as an exception and stops. The reason for the problem in the first place is that dompdf clones the required HTML elements when the content exceeds one page. However, elements with an `id` can't be cloned. Workaround so far: Use `class` instead of `id` ;-) Any other solutions yet?

**Comment by bsweeney** [comment]
Of course, that fact had completely escaped me! Since the appropriate styling is applied prior to laying out the document we should be able to address the issue by handling the ID prior to cloning. Perhaps until we find a better solution we can reassign the ID of cloned nodes to something like a data-id attribute.

**Comment by ThomasLandauer** [comment]
Sorry, I have way too little insight into dompdf internals to give any advice here :-( If you do take the `data-` approach, I would name it `data-dompdf-clone-temp-id` to avoid conflicts.

**Comment by bsweeney** [comment]
Agreed, we would definitely want to use something more specific for the data attribute.

I think you have a good enough understanding of what's going on. I dunno why this didn't scream out at me earlier, the issue that needs to be dealt with is right there in the error message.

**Comment by bsweeney** [comment]
Triggering the issue appears to be possible by using the HTML 4 Transitional DTD and disabling the HTML5 parser.

The issue can arise if an element with an ID renders on more than one page either from straddling the page break (block and inline elements) or using fixed positioning (block elements).
