### ISSUE TITLE
If you have &GT; in your HTML, it gets rendered as &GT; instead of as a > 

### ISSUE THREAD

**Issue by consolibyte** [dompdf/dompdf#1028]
If you have HTML like this: 
`"Here is some math: 5 &GT; 2"`

It gets rendered in the PDF as: 
`"Here is some math: 5 &GT; 2"`

But if you have this in your HTML (lowercase now):
`"Here is some math: 5 &gt; 2"`

Then it renders correctly in the PDF as:
`"Here is some math: 5 > 2"`

**Comment by bsweeney** [comment]
Per the HTML spec "[character entity references are case-sensitive](http://www.w3.org/TR/html4/charset.html)." That being said, in versions 0.6.0 or newer if you enable the HTML5 parser you will get some support for incorrect character entity case.

It's unlikely we'll address the issue further since the HTML5 parser corrects the incorrect case in certain instances. Plus, unless we hard code entities where a case doesn't matter (e.g. there's no `&Gt;` or `&GT;` entity) there's no way to know what the intent was (e.g. is `&ARING;` supposed to be `&Aring;` or `&aring;`).

**Comment by bsweeney** [comment]
(Anyone is welcome, of course, to make a case for supporting this.)

**Comment by consolibyte** [comment]
Woah, I had no idea that HTML 5 says they are case sensitive. OK, consider this closed!!!

**Comment by bsweeney** [comment]
Truthfully I hadn't really thought about it ... had to go and check the spec to make sure ;)

**Comment by osworx** [comment]
With XHTML there is a specification to write all tags in lowercase.
While HTML5 does not require lowercase tags, it is recommended: http://www.w3schools.com/html/html_elements.asp

btw: I am doing this job since 20 years.
Never wrote one tag in uppercase - do not know from where you have this idea??

**Comment by bsweeney** [comment]
@osworx I don't know that the same issue applies to tags. I'd have to refresh myself on the specific, but I imagine between the HTML5 Parser and DOMDocument that the tag format is lower-cased during processing. Also, I believe dompdf uses all lowercase internally to avoid any mismatch in tag names.

Regardless of how you case your element names and attributes, the comparison by a parser should be case-insensitive [[1](http://www.w3.org/TR/html-markup/documents.html#case-insensitivity)] [[2](http://www.w3.org/TR/html-markup/documents.html#case-insensitivity)]

**Comment by bsweeney** [comment]
Also, found this nifty chart on HTML5 character entities: http://dev.w3.org/html5/html-author/charref

**Comment by bsweeney** [comment]
(actually `nodeName` returns in all uppercase)

**Comment by osworx** [comment]
@bsweeney Interesting: only 6 of them are also available in uppercase - optional and beside the lowercase - (and one of them is the &gt;) - did not know that ..
For you resp. domPDF does it mean (i would suggest) to check and convert first. 
On the other hand, between ```&uuml;``` and &Uuml; is a big difference ...

**Comment by bsweeney** [comment]
That must be why ths HTML5 parser handles this. If there's a strong enough case for doing this in dompdf we'll certainly consider it. For now I think we'll leave it to the HTML5 Parser. We'll probably look at upgrading that library for the 0.7.1 release and enable it by default.
