### ISSUE TITLE
function build_url and '//somedomain.com' without protocol

### ISSUE THREAD

**Issue by Antonimo** [dompdf/dompdf#1048]
Get an exception when trying to load this file:
http://fonts.googleapis.com/earlyaccess/opensanshebrew.css

because the function build_url does not handle this kind of links currectly:
src: url(//fonts.gstatic.com/ea/opensanshebrew/v3/OpenSansHebrew-LightItalic.eot);

It returns: 
http://fonts.googleapis.com//fonts.gstatic.com/ea/opensanshebrew/v3/OpenSansHebrew-LightItalic.woff

instead of 
http://fonts.gstatic.com/ea/opensanshebrew/v3/OpenSansHebrew-LightItalic.woff

**Comment by bsweeney** [comment]
Indeed. The function would treat that as an absolute path rather than as a protocol-relative URL. This has already been addressed in the 0.7 branch. I'm actually working on some URI-related updates so I'll fit in the fix for this as well. If you need it quicker, though, you can grab the updated function from the next release: https://github.com/dompdf/dompdf/blob/develop/src/Helpers.php#L38
