### ISSUE TITLE
Images not working..

### ISSUE THREAD

**Issue by jodhavishalsingh** [dompdf/dompdf#1088]
Hi, i'm using the latest beta version (dompdf-0.7.0-beta3).
images appearing well in html but not in pdf , there is "image not found or type unknown" error with image placeholder.

Thanks

**Comment by Kristjan-Reinsberg** [comment]
I had same error when I used http.. like..
<img src="http://digimootor.ee/images/dm183.png">

Images started working like this: 
<img src="assets/img/dm183.png">

**Comment by bsweeney** [comment]
There was a bug in the initial release of 0.7.0 beta 3. It was fixed by 5f13a9afa8862bafdae2108e01246b293cc17a34. We have re-released the beta, but apparently the archive download still had the bug. I just updated the download and it should now have the fixed code.

If you're using composer to install you will have to clear your cache before you update otherwise composer will still be pulling from the unfixed release, e.g.:

```
php composer.phar clear-cache
```

I apologize for the inconvenience.
