### ISSUE TITLE
Image embedding not working on 0.7 version

### ISSUE THREAD

**Issue by cgabriel1304** [dompdf/dompdf#1090]
I recently got the latest dompdf using composer. (0.7 beta)
I want to embed an image thru a html file but it apparently doesn't work.
The html i'm trying to load is same as here https://jsfiddle.net/zgaf6ne8/1/

I load the html using:
$test = file_get_contents('test.html');
$dompdf->load_html($test);

So it's the <img src="image/png;base64, that doesn't work. I haven't tried any other way to embed the image.
Is it a bug or am i doing something wrong? 
Thanks and keep up the good work!

**Comment by bsweeney** [comment]
This is a known issue with line breaks in base64-encoded data. White space is supposed to be ignored but it's causing issues for data-uri processing. We're not sure yet if the problem is with dompdf or PHP. See #1016 for some relevant regex to strip out the line breaks.

**Comment by themao** [comment]
Hi @bsweeney, I've done a bit of debugging and found out that it's not PHP's issue - base64_decode handles line breaks fine, the problem is in Helpers:165, the regex omits everything in data section when it meets any whitespace. Adding 's' modifier solves this problem - I tested it on an image with the line breaks and it got rendered successfully. I've created a PR for that also - https://github.com/dompdf/dompdf/pull/1151

**Comment by bsweeney** [comment]
@themao thanks for that!
