### ISSUE TITLE
Not suppoting corrency symobol or HTML entity.

### ISSUE THREAD

**Issue by Deepab23** [dompdf/dompdf#1099]
Hi All

Maybe I am wrong or may be I not using correct steps 

but dom pdf not supporting  this   	&#3647; 
http://graphemica.com/%E0%B8%BF
if possible can you help me what will be best way to do that

**Comment by bsweeney** [comment]
The core PDF fonts (Helvetica, Times, Courier) do not as they only support Windows ANSI encoding. To support characters that are not available in this encoding you can use the bundled DejaVu fonts, which have been available since 0.6.0.

Try this:
```<p style="font-family: DejaVu Sans;">฿</p>```

You can find more information about the font issue and how to enable Unicode support in the [wiki](https://github.com/dompdf/dompdf/wiki).

**Comment by Deepab23** [comment]
Thanks
