### ISSUE TITLE
Loading external fonts / css 

### ISSUE THREAD

**Issue by watercayman** [dompdf/dompdf#1101]
I am finding a similar issue to the one reported here : 
https://github.com/barryvdh/laravel-dompdf/issues/191

If I remove the call to the external stylesheet (in this case bootstrap css), the page loads with no problem.  If I try to load the pdf with bootstrap, it will first fail due to a strftime() error in line 248 of Font_Binary_Stream.php.  If I apply the fix from:
     `https://github.com/BrunoDeBarros/php-font-lib/commit/b441fea819cef599ec33676c5408759d185fe896'

This will successfully fix the strftime() error, but then brings up the ErrorException in Adobe_Font_Metrics.php line 42 that I can't get around.

My code and error are the same as the one in issue 191 above.  Using PHP 7.0.2

**Comment by bsweeney** [comment]
It looks like the font parsing failed but still added a reference to the font in your font family cache. It's possible dompdf is attempting to parse the wrong font format. Currently it only support truetype fonts, but I've seen in the past where other formats were being parsed.

Do you have a sample HTML document we can use for debugging?

Adobe_Font_Metrics.php is found in php-font-lib 0.3.x, which is used by dompdf 0.6.x. Since 0.7.0 is about to be released would you be able to test using the latest 0.7 beta which uses php-font-lib 0.4? I did a quick test using the stylesheet from the error in barryvdh/laravel-dompdf#191. I was not able to render the document with dompdf 0.6.2. With dompdf 0.7.0 beta 3 it rendered just fine.

**Comment by watercayman** [comment]
I no longer have the code, as I switched to wkthmltopdf... but I did do up a quick imitation of what I had, and downloaded the 0.7 beta version.  It seems to have successfully resolved the issue.  

Well done, and thank you.

**Comment by bsweeney** [comment]
Excellent, thanks for taking the time to follow up. I'll go ahead and close. Hopefully commit 240c2f2b10079629b2a6a9453e6cc3ebad8e8fc9 addressed the issue.
