### ISSUE TITLE
File size is quite large

### ISSUE THREAD

**Issue by xingxiaoyang** [dompdf/dompdf#1109]
When Chinese language is inclued in the HTML, the PDF file quite large , 15MB with just few words. It seems the file contains the entire .ttf (about 15MB).

Is there any way to reduce the size?

My code is following

```
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        @font-face {
          font-family: 'Firefly';
          font-style: normal;
          font-weight: normal;
          src: url(domainname/fireflysung.ttf) format("truetype");
        }
    </style>
</head>
<body>
     <p style="font-family: firefly, DejaVu Sans, sans-serif;">Chinese汉体书</p>
</body>
</html>
```

**Comment by efbiaiinzinz** [comment]
Yes, you can enable font subsetting, which embeds only used characters into the file.
You can set the option on creation
$dompdf = new Dompdf\Dompdf(array('enable_font_subsetting' => true));
or you can also set it later as
$dompdf->getOptions()->setIsFontSubsettingEnabled(true);

This makes the generation a bit slower because detailed font file parsing is needed, but this should not be so bad if you use the latest version of php-font-lib which has my optimization patches that make font parsing 55% faster.

**Comment by nikunjpagada** [comment]
add this code before generating PDF. it is working for me 

ini_set("memory_limit","850M");
set_time_limit('120');

**Comment by Mengxiangwo** [comment]
modify dompdf config, like this:
"DOMPDF_ENABLE_FONT_SUBSETTING" => true

**Comment by bernierayxu** [comment]
@indreka your solution is perfect!
saved my day

**Comment by mahesvaran** [comment]
@indreka thanks a lot...

**Comment by DTrendafilov93** [comment]
@indreka dude, i owe you a beer
