### ISSUE TITLE
Question : Is it possible to get my pdf without client-side download (or preview it for printer) ?

### ISSUE THREAD

**Issue by C0ZEN** [dompdf/dompdf#1117]
I wonder if dompdf can give me a pdf without download it on client-side.
In fact, I just need to direct print it.
Is there an official way to do it properly ?
Thanks.

**Comment by laxman1223** [comment]
no

**Comment by bsweeney** [comment]
Direct print from where?

If you want a site to directly print to a client's printer then no.

If you want to send the PDF to a printer available to the server it *should* be possible, though I haven't tried anything like that. You can get the rendered PDF using the `output()` method instead of the `stream()` method. You could then save to a file on the server or maybe push directly to a print service.

**Comment by C0ZEN** [comment]
Thanks for the answers.
There is no official way.
