### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by kvskkvsk** [dompdf/dompdf#1167]
Catchable fatal error: Argument 1 passed to Dompdf\FrameDecorator\AbstractFrameDecorator::copy() must be an instance of DOMNode, boolean given, called in D:\WebServers\home\localhost\def\pdf\dompdf_0-7-0_beta3\dompdf\src\FrameDecorator\Text.php on line 156 and defined in D:\WebServers\home\localhost\def\pdf\dompdf_0-7-0_beta3\dompdf\src\FrameDecorator\AbstractFrameDecorator.php on line 133

**Comment by bsweeney** [comment]
See #1124 (specifically [this comment](https://github.com/dompdf/dompdf/issues/1124#issuecomment-187880503). The issue was fixed by commit 8658648502acdc45e93d6e11f9f906ded5224aba.

Temporary fix is to make PHP internal encoding UTF8. Add `mb_internal_encoding('UTF-8');` somewhere before you use dompdf.
