### ISSUE TITLE
Pdf does not work on android

### ISSUE THREAD

**Issue by GiacomoK** [dompdf/dompdf#1177]
Hi,
I don't know why the pdf generated does not work on android. I got 2 problem:

Hi use this code:

```
$dompdf = new Dompdf();
$dompdf->set_option('defaultFont', 'sans-serif');
$dompdf->load_html('hello');
$dompdf->render();
$dompdf->stream("Ordine_num");
```

FIRST PROBLEM:
The downloaded file has this name:
Ordine_num.pdf; filename*=Utf-8"Ordine_num.pdf

you know why is so long?

SECOND PROBLEM:
I got the error "format not valid" when I try to open it on Android, and I can't see it. I don't have these problems on web browser.

Any help?
Thanks.

**Comment by bsweeney** [comment]
Which version of dompdf? Looks like you're using a fairly recent copy since the alternate file naming convention is used.

**Comment by GiacomoK** [comment]
I use last version, 0.7.0 if i am not wrong.

There is not web link available, but I use domdpf inside joomla.

**Comment by bsweeney** [comment]
OK. I'll see if I can set up a test environment to duplicate the issue.

**Comment by gjones604** [comment]
I'm also having issues with Android failing to download. My file names are all called "" and they never go past 0%

iOS, and desktop work fine.

**Comment by bsweeney** [comment]
@gjones604 this looks to possibly be a separate issue, you might try explicitly halting execution after streaming the PDF by calling `exit;`. Also might be worthwhile to include the file extension, though I can't imagine it would make a difference.

```
$html = '.... lots of stuf here .... ';
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->set_paper("letter", "portrait");
$dompdf->render();
$dompdf->stream('Stuff.pdf');
exit;
```

**Comment by bsweeney** [comment]
@GiacomoK FYI the filename issue is because of some additions we made to provide a fallback for file names that are UTF8 encoded (e.g. `$dompdf->stream('документ.pdf');`), see [Cpdf#3525](https://github.com/dompdf/dompdf/blob/v0.7.0/lib/Cpdf.php#L3525).

If you don't plan on using any characters outside iso-8858-1 for the file name you could replace that header with the following:

```
header("Content-Disposition: $attachment; filename=\"$fileName\"");
```

(which is what we had before the addition of a fallback).

I wonder if just adding back in the quotation marks would address the issue. If you are able to test at all that would be helpful. Also might be useful just to check if the fallback and filename are the same and, if they are, leave out the fallback.

I'm still not sure why you see nothing at all. If you haven't updated to the final 0.7.0 release you might try that and see if it helps.

**Comment by gjones604** [comment]
@bsweeney 
Those suggestions have not resolved the issue but I did discover that this problem seems to occur on my staging server, but not on my development one. Perhaps there is some kind of apache setting involved here. Any thoughts as to what it might be?

My staging server has a valid SSL cert and the file is served over HTTPS while on dev its using HTTP.

**Comment by bsweeney** [comment]
@gjones604 the only SSL-related info I see in the issue tracker are related to IE8, except for one related to an apache configuration. I don't really have any insight into what's going on. It seems like apache isn't sensing the end of processing of the file and so never sends down any content. If you have output buffering on you might try adding `ob_end_flush();` before the `exit;` statement.

**Comment by bsweeney** [comment]
I tweaked the code that generates the filename header when streaming the output. Anyone have time to test?

**Comment by bsweeney** [comment]
Please post back here if there are still problems.
