### ISSUE TITLE
last-child (and nth-last-child() ) selector not working properly

### ISSUE THREAD

**Issue by JustTsukihime** [dompdf/dompdf#1200]
E.g. 
table.lineitems tr:last-child td { border-bottom: 1px solid #f00; }

Renders all the bottom borders as red: (interprets every as last?) 
![screenshot from 2016-05-23 17 20 45](https://cloud.githubusercontent.com/assets/12938632/15473878/de96514e-210a-11e6-98c2-d3f87f086b56.png)

While it should: (in browser)
![screenshot from 2016-05-23 17 21 49](https://cloud.githubusercontent.com/assets/12938632/15473879/de9b991a-210a-11e6-908b-2c369d338242.png)

When using nth-last-child(1), it only applies the style to the first child, not the last.
Other than this little inconvenience your library saved me lots of time, thanks.

**Comment by bsweeney** [comment]
It's possible that the issue was addressed by the changes made to better support nth-child/nth-of-type (#543). At least, my limited testing appears to indicate as much.

Are you able to check your document against the latest develop branch to see if it work as expected? If you still see issues, can you supply some sample HTML?

**Comment by bsweeney** [comment]
This should be ok with the forthcoming 0.7.1 release.
