### ISSUE TITLE
Table avoid page-break-inside

### ISSUE THREAD

**Issue by ghost** [dompdf/dompdf#1223]
Hello,

avoid the page-break-inside a table doesn't work well.
Can somebody help me with this problem?

Thanks in advance.

```
    for($i=0; $i<20; $i++)
        $html .= '<table class="produkt" border="1" style="background-color:red; page-break-inside: avoid;">
            <tr>
                <td><br></td>
                <td><br></td>
                <td><br></td>
                <td><br></td>
                <td><br></td>
                <td><br></td>
            </tr>

            <tr><td colspan="6"> <br></td></tr>

            <tr><td colspan="6"><br><br><br><br><br> <br></td></tr>

            <tr><td colspan="6"> <br></td></tr>
        </table>
```

**Comment by bsweeney** [comment]
It's a problem, yes. There's quite a bit we can do to improve table handling. No timeline on a lot of these issues yet.

**Comment by Neograph734** [comment]
I have no idea what rtimo meant with `doesn't work well`, but I ran into below issue today and looking at the many `<br>`'s above I suppose it might be the same problem.

If an element (in my case it was a wrapper div) has a property of `page-break-inside: avoid;` and the element is too big for a single page, dompdf keeps attempting to place the element on a new page (until php reaches its max execution time because it will never fit).

Perhaps dompdf could make use of a simple check if a new page was already added, and if so, conclude that it could not be avoided and break the table anyway? Or perhaps at least throw an error that the conditions could not be met or something? It is pretty hard to debug because the HTML looked fine and I accidentally discovered this because I generated a PDF where my element was moved several pages down, where it did (just) fit (perhaps some weird issue with rounding to pixel values or something, really strange). 

Anyway, I hope this will help you in building this system further and make it even better :)

**Comment by bsweeney** [comment]
@Neograph734 thanks for the additional info. dompdf *should* stop after paging once, but that code may be buggy. We also have a max-paging check but I think it needs a bit more work (besides the fact that it wouldn't look right if you had a few hundred blank pages in your document).

Then there's also this: I don't believe page break declarations attached to table elements work are supported.

**Comment by Neograph734** [comment]
@bsweeney Thanks for the fast response. It might be something entirely different, but [this answer](http://stackoverflow.com/a/29536911/1293725) (suggesting to increase the page size) feeds my suspicion that it has something to do with pages overflowing. 

> I don't believe page break declarations attached to table elements work are supported.

I don't know, never tried. For div's they worked excellent until I broke it by adding too much content to the div...

**Comment by bsweeney** [comment]
I believe these issues have been addressed.
