### ISSUE TITLE
Autoload.inc.php is referencing files that do not exist

### ISSUE THREAD

**Issue by ryantheriot** [dompdf/dompdf#1267]
From autoload.inc.php:

require_once **DIR** . '/lib/php-font-lib/src/FontLib/Autoloader.php';
require_once **DIR** . '/lib/php-svg-lib/src/autoload.php';

these files do not exist in lib. The following structure exists:
lib
    - fonts
    - html5lib
    - res

**Comment by bsweeney** [comment]
That file is intended to be used only with the packaged version of dompdf that includes all the dependencies. I'll add a note to the file to make that clear.

If you're not using the packaged version we recommend using composer.

**Comment by Gnurps** [comment]
I don't understand "only with the packaged version of dompdf..." I downloaded the full, current package from github. Not using Composer because on shared hosting. So what's a guy to do without Composer?

**Comment by bsweeney** [comment]
@Gnurps what file did you download? The packaged version can be found on releases page, [dompdf_0-8-0.zip](https://github.com/dompdf/dompdf/releases/download/v0.8.0/dompdf_0-8-0.zip) for example.

**Comment by Gnurps** [comment]
I clicked the green Clone or Download button on the main dompdf github page.  What button goes to that releases page?

**Comment by bsweeney** [comment]
The clone button is to grab only the Dompdf source. When you do that you have to download the dependencies manually. On the main project page you'll see a link that says [releases](https://github.com/dompdf/dompdf/releases) that takes you to the list of releases. You can download packaged versions from this page.

FYI, you can still use composer on shared hosting. Just download the phar and run rather than install globally.
