### ISSUE TITLE
`white-space:pre-line` not working correctly

### ISSUE THREAD

**Issue by ThomasLandauer** [dompdf/dompdf#1315]
This might be related to https://github.com/dompdf/dompdf/issues/800

Sample code:
```html
<style>#foo {white-space:pre-line; }</style>
Zero
<div id="foo">One
Two
Three</div>
Four
```

Expected result (as shown in Firefox & Chrome):
```
Zero
One
Two
Three
Four
```

Actual result in dompdf 0.8.1:
```
Zero

One
TwoThree
Four
```

**Comment by nickwuk** [comment]
Also having issues with 'white-space: pre-line' when specified for a textarea inside a table cell. I have an example table with two columns and several rows, each row in the second column contains the same 2 paragraph content. When output to Pdf the 2nd paragraph starts on the next line, the space between the paragraphs is removed (I assume only the 1st newline character is preserved and the 2nd new line character is removed), and the 2nd paragraph is truncated to one line - because it looks like it is not wrapping.

This behaviour continues in the 2nd row, in rows 3-5 content is not truncated, then content in the last row #6 is again truncated. The extra line space between paragraphs is removed in all rows.

With 'white-space:  normal' all content is visible but there's no paragraphing, all new lines are removed.

**Comment by bsweeney** [comment]
Not much progress with anything for the last few months, but I'm going to try to get back into things.

**Comment by bsweeney** [comment]
I haven't looked at this yet, just a random thought ... perhaps better handled in the line box logic?

**Comment by tuananhcwrs** [comment]
I've got the same issue as @ThomasLandauer .
Would someone please share any tip?

**Comment by bsweeney** [comment]
specific case appears to be addressed with committed changes
