### ISSUE TITLE
PHP 7.1 "A non-numeric value encountered"

### ISSUE THREAD

**Issue by carduz** [dompdf/dompdf#1323]
Using php 7.1 I have error "A non-numeric value encountered" on https://github.com/dompdf/dompdf/blob/master/src/FrameReflower/Table.php#L577, because in my case delta = "auto".
I used dompdf via laravel cashier.

**Comment by bkuhl** [comment]
I ran into the same problem on https://github.com/dompdf/dompdf/blob/master/src/FrameDecorator/Page.php#L494 because `$margin_height` is "auto"

**Comment by bsweeney** [comment]
There are many places where this is a problem. This is due to a change in how 7.1 deals with non-numeric values used in calculations. We're currently working through them for the next release. In the meantime you can either suppress errors by prefixing the render call with an @, or you can modify error handling to not halt on warnings.

Follow #1272 for updates.

**Comment by BackuPs** [comment]
The issue also arrises on shortcodes in wordpress or when you initiate variable like this

	'paddingtopbottom' =>'5',
	'paddingleftright' =>'15',

If you then try to do something like this

$height=10;
$height=$height+(2*$paddingtopbottom);

You get the same warning. Now all has to be changed to

$height=$height+(2*intval($paddingtopbottom));

But shortcodes are build like this [shortcodename paddingtopbottom="10"] so it will be string all the time.

This is a huge impact on all plugins developers and theme developer.
