### ISSUE TITLE
Tag dependent if css tag will get noticed

### ISSUE THREAD

**Issue by KerwinSneijders** [dompdf/dompdf#1334]
Whenever I type this: 
`<p class="box"> text </p>`
with css:
`.box {
     height: 25px;
}`
it results different than:
`<span class="box"> text <span>`
with same css as above
If I make my own tag like `<box>`, it will too ignore the css.

**Comment by bsweeney** [comment]
You can't really modify the height of an inline element. If you want to do that you should use `line-height` instead of height. If you want the styled element to act more like block-level element you can style it with `display: inline-block`, but it doesn't work too well if the inline block wraps and there is normal text on either side of it.

As for the `box` tag, dompdf doesn't know what type of element that is so you'll want to give it a display styling.
