### ISSUE TITLE
$PAGE_NUM and $PAGE_COUNT showing as the same

### ISSUE THREAD

**Issue by Britic** [dompdf/dompdf#1354]
If I try the following code
```
if (isset($pdf)) {
  $font = $fontMetrics->getFont("Arial", "bold");
  $pdf->page_text(770, 580, "Page " . $PAGE_NUM .  " of " .  $PAGE_COUNT, $font, 10, array(0, 0, 0));
}
```

My document has matching page number and count on every page - such as
Page 1 of 1
Page 2 of 2
Page 3 of 3
etc

So `$PAGE_NUM` is always correct, but `$PAGE_COUNT` is not.

Is there a way to address this issue?

**Comment by bsweeney** [comment]
Those values are correct as of when that text is evaluated. What you want to do rather than interpreting the text on the current page is to insert the value after the document is rendered. Try the following instead:

```
if (isset($pdf)) {
  $font = $fontMetrics->getFont("Arial", "bold");
  $pdf->page_text(770, 580, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, 10, array(0, 0, 0));
}
```

Another option would be to use `page_script` instead, which evaluates the script on each page.
```
if (isset($pdf)) {
  $pdf->page_script('
    $font = $fontMetrics->getFont("Arial", "bold");
    $pdf->text(770, 580, "Page $PAGE_NUM of $PAGE_COUNT", $font, 10, array(0, 0, 0));
  ');
}
```
