### ISSUE TITLE
3 definitely and possible Switch..Case..Break problems

### ISSUE THREAD

**Issue by simonberger** [dompdf/dompdf#1364]
1. https://github.com/dompdf/dompdf/blob/master/src/Renderer/ListBullet.php#L42-L58
Not sure about these two missing breaks after uppercase. The name implies a bug. If it is no bug it's still not good regarding codeflow and performance. Instead the static added text of line 49 and 57 could be created in uppercase and that break be added.

2. https://github.com/dompdf/dompdf/blob/master/src/Renderer/ListBullet.php#L195-L244
Missing break before none doesn't seem intentional here. Otherwise none would be correctly placed before that block too.

3. https://github.com/dompdf/dompdf/blob/master/src/Renderer/ListBullet.php#L175-L185
Could be the only really intended case but not sure either.
I plan to add a phpdoc to supress the warning and tell everyone its intended.

**Comment by bsweeney** [comment]
> 1. https://github.com/dompdf/dompdf/blob/master/src/Renderer/ListBullet.php#L42-L58
> Not sure about these two missing breaks after uppercase. The name implies a bug. If it is no bug it's still not good regarding code flow and performance. Instead the static added text of line 49 and 57 could be created in uppercase and that break be added.

This isn't a bug it's a logic optimization (as opposed to a performance optimization). Since multiple scenarios use an uppercase version of the text the logic to switch case is further down in the method. I'm not too concerned about the usage, particularly since the results are cached. It is worth noting, however, that the `get_counter_chars` method doesn't actually appear to be used anymore so I'm going to mark it as deprecated and remove the method in a future release.

The `make_counter` method uses similar logic, and here I think modifying the logic makes sense. There's only one scenario where we need to switch case and that's for uppercase roman, since the helper method only returns lowercase.

> 2. https://github.com/dompdf/dompdf/blob/master/src/Renderer/ListBullet.php#L195-L244
> Missing break before none doesn't seem intentional here. Otherwise none would be correctly placed before that block too.

The current fall through doesn't harm anything, but does appear to be an oversight.

> 3. https://github.com/dompdf/dompdf/blob/master/src/Renderer/ListBullet.php#L175-L185
> Could be the only really intended case but not sure either. I plan to add a phpdoc to supress the warning and tell everyone its intended.

Indeed that one was intended but the specific logic for that one has changed and so the annotation is no longer necessary.
