### ISSUE TITLE
[version 8] Image really small inside table

### ISSUE THREAD

**Issue by Aphyxia** [dompdf/dompdf#1448]
Images stay really small when used inside table tags.
Example: https://gyazo.com/b6903f745632a69b71fef19a29fe3076

HTML: https://pastebin.com/2M0gEr59
No external CSS used.

After removing the table tags along with tr and td:
https://gyazo.com/092ef4c8794a000d1b4479c2746a6695

This is how it's supposed to look:
-- Link removed --

I've tried fiddling with much of the style but to no avail. The structure I would like to keep intact. Maybe it's something dompdf doesn't support.

PHP 7.0
Installed dependencies with composer today.

How I am creating the PDF:
```
$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('fontHeightRatio', 1);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
 $dompdf->render();
$pdf = $dompdf->output();
```

**Comment by OnkelTem** [comment]
Confirm this. Images are displayed as small as micro-icons. Can't find a way to fix it. 

Why don't you print on your main page the text:

**DOMPDF DOESN'T SUPPORT IMAGES INSIDE TABLES** ?

**Comment by dorozhkin** [comment]
I have the same problem. Still can't display normal image in table.
I can suggest not to use image with table in such cases, but use div with display:inline-block style if you nedd to display two columns.

**Comment by bsweeney** [comment]
The sample HTML from the OP:

```
<div id="body_content_inner" style='color: #737373; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 14px; line-height: 150%; text-align: left;'>
    <div class="ywgc-template style1">


        <div class="ywgc-preview" style="clear: both; max-width: 500px; margin: 0 auto; margin-bottom: 15px; border: 5px solid #F7F4F4; padding: 5px;">
            <div class="ywgc-main-image" style="max-width: 100%; height: auto; margin: 0 auto; display: block;">
                <img src="http://test.artmedia.ee/vspa/wp-content/uploads/2017/05/600volukaart-lyhike.jpg" id="ywgc-main-image" class="ywgc-main-image" alt="Gift card image" title="Gift card image" style="border: none; display: block; font-size: 14px; font-weight: bold; height: auto; line-height: 100%; outline: none; text-decoration: none; text-transform: capitalize; max-width: 100%; margin: 0 auto;">
            </div>
            <div class="ywgc-card-values" style="overflow: hidden; margin-top:360px; padding: 5px 0; display: table; width: 100%;">
                <div class="ywgc-logo-shop" style="width: 40%; display: inline-block; vertical-align: middle;">
                    <img src="http://vspa.ee/wp-content/uploads/2016/11/sitelogo.png" class="ywgc-logo-shop-image" alt="The shop logo for the gift card" title="The shop logo for the gift card" style="border: none; display: inline; font-size: 14px; font-weight: bold; height: auto; line-height: 100%; outline: none; text-decoration: none; text-transform: capitalize; max-width: 100%; max-height: 100px;">
                </div>

                <div class="ywgc-card-amount" style="text-align: right; padding: 10px; font-size: 25px; font-weight: bold; display: inline-block; width: 50%; float: right;">
                    <span class="woocommerce-Price-amount amount">10<span class="woocommerce-Price-currencySymbol"> EUR</span></span>			</div>
            </div>
            <div class="ywgc-card-code" style="padding: 10px; color: #9b9b9b; text-align: center; border-top: 1px solid #e6e6e6; border-bottom: 1px solid #e6e6e6;">
                Your Gift Card code:			<span class="ywgc-generated-code" style="font-weight: bold; display: block; font-size: 18px;">NWKF-99P0-ZOGG-OKSG</span>
            </div>
            <div class="ywgc-card-message">123545</div>
        </div>
    </div>
</div>
```

**Comment by bsweeney** [comment]
I did not have any trouble rendering the document in the released versions of dompdf. I'll note one thing that's a known issue: you modified the display styling of the image which is something Dompdf does not handle very well. See #693.

The only other potential issue, barring additional information, is that maybe the function that determines the height/width of the image was unable to read the image. But that seems unlikely if the image itself is embedded in the document.

This will make an interesting test case, though. Current dev doesn't render it correctly even though the released versions seem fine.

**Comment by agoradesign** [comment]
I can also confirm this issue. They are micro-sized inside tables and normal outside. I tried various things to bypass this problem. One approach was to set a style attribute on the img element, specifiying width and height in pt units. Interestingly, the height was accepted, but the width was still tiny, resulting in a completely blurred image.

After finding this issue and not having luck with my workarounds, I changed the markup into a tableless one.. However it still may get funny for me, because later in the document I will have to render some order items, which won't be easy to accomplish without tables...

**Comment by bsweeney** [comment]
So far I am still unable to reproduce the micro-size rendering if the image. Unless we can do that we won't be able to address the issue or offer potential work-arounds.

**Comment by agoradesign** [comment]
Really? Thought you can reproduce it on dev, but not on released versions? (Which sound weird because I wouldn't expect any troubles with the last commits since the release). It happened to me on 0.8.0 and I still had it with the current dev. If PHP version matters, it happened on 7.1.4

**Comment by bsweeney** [comment]
Sorry, I don't think I was clear on what I was seeing. The image is correctly sized on dev. I'm getting a different issue where the image is removed from the document flow (the following text is rendered on top of it).

**Comment by agoradesign** [comment]
I'll do my best to provide you with better details

**Comment by agoradesign** [comment]
I have actually found a way, how to reproduce it :)))

First of all, I have to mention that the original issue happened inside a Drupal 8 site using the entity_print module. I didn't seem at first sight, that the Drupal module is adding something harmful, as it is mainly configuring the DomPdf instance and let it render the HTML produced by Drupal. It is adding by default only a few lines of CSS (which can be skipped completely, if desired).

In order to be able to give you a better starting point, I then set up a custom PHP file loading Dompdf on the same server, but without any Drupal context. I configured it the same way (paper size A4 and orientation portrait, enabling the HTML5 support).

I started adding an image and a table with an image (having one row with two columns, the image in the first column and a short text in the second column) and rendered that markup. No problem occurred! Next, I have added the same wrapper elements in my HTML markup and copied the HTML head part (first, without CSS linked). Still no problem.

Next, I added the same CSS file that I was using on my Drupal page, when the problem suddenly arised!

Now it was rather clear to me, where the problem would live. And a few experiments later, I was sure that it was that:

By default, the entity_print Drupal module is adding this styles:

`
.page img {
  max-width: 100%;
  height: auto;
}
`

As soon as you remove the max-width part, the images inside tables are rendered correctly!

I was further playing around, re-added that line and tried to override it for tables with:

`
.page td img {
  max-width: auto;
}
`
What happens then, is also very interesting: the image size is ok, but it's parent table cell is somehow collapsing, so that it is overlapping the second cell.

Hope, this information helps you. At least, it should help everyone getting the same problem to find a workaround :)

PS: I'll open up an issue in the Drupal module too, linking to this issue here

**Comment by bsweeney** [comment]
Confirmed. Thanks for looking into it more @agoradesign. Looks like there are probably a few issues to address (particularly in dev).

I haven't looked at the code yet but best guess is that because column size is based on the content (if the width is not defined) the `max-width` on the image will be small. This is likely because without any other content in the cell the column size is being defined based on the "characters" present in the cell. And the image width is being defined before it is rendered, which is before the table cell is rendered. Or something like that.

Plus some other obvious issues around using `max-width` in tables.

Looks like the work-around for now is setting setting that styling to `max-width: none;` (the default).

**Comment by agoradesign** [comment]
@bsweeney 
thanks for the quick response and especially for the last sentence. I was mixing up the default of max-width. Good to know that we can reset it for tables specifically (and shame on me :D )

The rest of the explanation makes sense too, since width calculations are always different for tables. However, what I did have (and it didn't work), was setting 100% width on the table and 50% width on td (I had two cols). Also, during debugging I added a div element in the same cell (with a declared height and coloured background). This one was correctly sized, so the table cell should theoretically have it's size set even without image and at calculation time.

I'm happy to now know enough about the problem to be able to avoid it :)

**Comment by agoradesign** [comment]
just for the records, here is the corresponding drupal.org issue: https://www.drupal.org/node/2906839#comment-12247566

**Comment by mtsalcova** [comment]
I have same problem @Aphyxia! :(

But, @agoradesign thanks!! It works for me.

I added this line:

``
.page td img { max-width: none; width: 100% }
``

Thanks!!

**Comment by lenerdz** [comment]
I just had this problem and I solved adding `table-layout:fixed;` to the table style.

**Comment by jazen4p** [comment]
> I just had this problem and I solved adding `table-layout:fixed;` to the table style.

Wow, just like that. It works for me. Thanks @lenerdz

**Comment by cimoskill** [comment]
> > I just had this problem and I solved adding `table-layout:fixed;` to the table style.
> 
> Wow, just like that. It works for me. Thanks @lenerdz , But i suggest that you added this style for better position
> `table-layout: fixed; width: 100%;` or your want to add in the `table style` `table style="table-layout: fixed; width: 100%; text-align: center"`

Thank you very much! This worked for me on a large table with lot of images so a minimum fix to get it!

**Comment by bsweeney** [comment]
It looks like max-width with a value of auto seems OK with the current release but a value of 100% is still not rendering the appropriate size.

I believe the table collapse issue may have been addressed.

If anyone has sample HTML+CSS to reproduce the issue that would be appreciated.

I used the following for some quick testing:

```
<table style="width: 20%; border-collapse: collapse;" border="1">
    <tr>
        <td>
            <img src="http://placekitten.com/500/300" style="max-width: auto;">
        </td>
    </tr>
</table>
<table style="width: 20%; border-collapse: collapse;" border="1">
    <tr>
        <td>
            <img src="http://placekitten.com/500/300" style="max-width: 100%; height: auto;">
        </td>
    </tr>
</table>
```
