### ISSUE TITLE
PDF not showing Hebrew Characters on google viewer 

### ISSUE THREAD

**Issue by avikosta** [dompdf/dompdf#1500]
Hello, I have a weird issue, if I download the PDF to my computer, I can see the Hebrew characters, however, If I try to use Gmail pdf viewer or Google, I don't see the Hebrew, only the English characters. some other PDF apps show the Hebrew as weird characters with question marks.  here is example file with the issue - 
[attachment (16).pdf](https://github.com/dompdf/dompdf/files/1184011/attachment.16.pdf)

**Comment by simonberger** [comment]
There are some more open issues (#1433, #938).
It seems there are some problems in the way DomPDF saves the pdf.
Only some readers can handle it.

This as a information that it is known.
I am no font nor pdf file format expert.

**Comment by simonberger** [comment]
While I i can see the problem with the PDF you attached, I can't manage to reproduce the problem with a font and some HTML example-code I created myself.
Could you please provide the font file you used and a small html snipped with some Hebrew characters that then disappear for you?

**Comment by simonberger** [comment]
You stumbled over this bug #340. Actually the problem is the encryption you set.
I have no idea though why I could view it without input a password. There is some encryption information inside the PDF

**Comment by bsweeney** [comment]
Also, it's possible Dompdf thinks it's embedding the font but is not doing so. Or not doing it correctly. In this case I imagine it is possible some PDF viewers may be substituting a system font, where as others may not.

I'm not sure about the encryption issue. I would have to peek at the PDF source, which I have not yet done. Same for determining the font status.

**Comment by bsweeney** [comment]
Simon's probably right on this one. Something we should look at a bit more.

**Comment by simonberger** [comment]
Could you test on the newest develop branch if this bug has been fixed for you?

**Comment by adrienco88** [comment]
The newest develop branch still have this issue, happening with multiple languages. I also tried with different fonts but there are the same results, question marks instead of characters, even if I don't use encryption.

**Comment by simonberger** [comment]
You likely didn't include a font capable of displaying those characters.

Please have a look at:
https://github.com/dompdf/dompdf/wiki/UnicodeHowTo

Though this document is old and in the current version there aren't many steps you have to do.

**Comment by adrienco88** [comment]
Hi @simonberger 
I read the Unicode How To already.
I suppose that the font is capable (Arial Unicode) since it's working fine with dompdf 0.6 without encryption. 
With encryption, in Chrome browser I can't see the chars, but if I select and copy them, when I paste them I see the right chars, and in Adobe PDF Viewer I see just squares.

With the latest develop branch, I got question marks instead of the the chars in both browser and PDF viewer. I tried with DejaVu Sans and also with Courier and Arial/Arial Unicode.

I will try more, but if you have any idea it would be appreciated.

Thanks

**Comment by simonberger** [comment]
Did you notice a different behavior of an unencrypted document between 0.8.0 and current develop version? Or do you just compare 0.6.0 and develop?

It would be good if you could add a Demo-HTML of this problem. I have no idea otherwise-
You can also look at the example in https://github.com/dompdf/dompdf/pull/1505 and try/compare.
This works for me.

**Comment by adrienco88** [comment]
I was comparing 0.6 with the latest develop.
It seems to work ok now, but I had to re-load the fonts under a different font-name (using the same font files) using the load_font script. If I load them with the old font name: ArialUnicode for example it didn't worked for some reason even if I saw that the font_family_cache was updated. Now when I re-load them under ArialUnicodeNew name it seems to work as expected. 

Thanks for everything and Best Regards,
