### ISSUE TITLE
Huge File Size

### ISSUE THREAD

**Issue by LiamMcArthur** [dompdf/dompdf#1510]
I've been using FPDF for some time now and I'm to generate policy documents for our customers at 509KB in file size. The document itself has a full-size front cover background image and then a second-page containing text about their policy.

I've recreated this using dompdf but the outputted file-size is now 5,647KB - much larger than before. Everything is the same and the background image that I'm using on the PDF is only 444KB so I'm not quite sure how it's being produced that at such a size. Both my documents with DPDF and dompdf are 300dpi. Any thoughts?

**Comment by bsweeney** [comment]
My first thought is ... what font do you use for the document and do you have font subsetting enabled? Additionally, it's possible image processing that Dompdf performs could be producing larger image sizes. Are you using JPG or PNG? JPG images are inserted without additional processing.

Beyond that it would help to know more about the document. If you can supply a sample of the HTML+CSS and images we can take a closer look. You can also supply the PDF generated by Dompdf and we can break it apart to see what's taking up so much space.

**Comment by LiamMcArthur** [comment]
I'm using Open Sans in both, but I've removed the font from each and used the standard Arial font and the file size is still the same. After some testing, the file size greatly reduces when removing the background image - so that must be the culprit. I just don't understand how a 444kb image is adding over 5MB to the file size. I've created an example for you:

- [dompdf example](https://www.silkwave.co.uk/dompdf_example.pdf)
- [FPDF example](https://www.silkwave.co.uk/fpdf_example.pdf)

Both documents are embedding Open Sans - but even when removing this font - the file size is similar. Only when removing the background image do I start to see a real reduction.

**Comment by bsweeney** [comment]
Is your image a PNG? If so it's likely because dompdf is creating a new one based off the original. We do a lot of processing of PNG images to accommodate the features it supports that aren't available natively in the PDF 1.3 spec.

You might try using a JPG image instead. Those go in without being touched.

Can you share a sample of the HTML you're using and the image?

**Comment by LiamMcArthur** [comment]
Sure - here's all of the code I'm using:

```
<?php
require 'vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->setDpi(300);
$options->set('defaultFont', 'Open Sans');
$options->setIsFontSubsettingEnabled(true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml(file_get_contents("html.html"));
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("file.pdf", array("Attachment" => false));
exit(0);
```

HTML:
```
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<span class="cover-title">Custom<br>Document</span>
</body>
</html>
```

CSS:
```
@page {
    margin: 0;
}
html {
    margin: 0;
}
body {
    background: url("cover.jpg") no-repeat top center;
    background-size: 100%;
    margin: 0;
    width: 100%;
    height: 100%;
}
.cover-title {
    display: block;
    font-family: 'OpenSans';
    font-size: 48pt;
    line-height:0.7;
    color: #fff;
    font-weight: bold;
    padding: 230px 0 230px 120px;
}
```

**Comment by bsweeney** [comment]
Is the image you're using a PNG or a JPG? Based on the PDF object profile it looks like a PNG. If that's the case I believe it's probably the DPI of 300 combined with the complexity of the image. I don't recall off the top of my head because I haven't looked at that part of the code in a while, but I believe that Dompdf re-renders PNG images so that they are more compatible with the PDF 1.3 spec (as I mentioned before). I did a test with a similar image and had similar results. For an image such as yours you'll get better results using a JPG since Dompdf will insert the image as-is.

**Comment by LiamMcArthur** [comment]
Nope, it's definitely a JPG image!

**Comment by bsweeney** [comment]
I saw what you used in your sample, but when I look at the PDF source the object defined for your image matches what would be used if the image were a PNG. Can you upload the image used in the original PDF sample?

**Comment by LiamMcArthur** [comment]
Sure - I've uploaded the file [here](https://www.silkwave.co.uk/cover.jpg).

**Comment by bsweeney** [comment]
I see it now. It's because the image is used for a background and background images are re-generated from source so we can handle `background-repeat` styling. So the JPG rule doesn't work for background images.

You could work around this by using a positioned div containing the image rather than setting it as a background. It would take a bit more work to set up but should allow you to avoid the image re-generation penalty since you're not repeating in any direction.

**Comment by LiamMcArthur** [comment]
That's great - the [document](https://www.silkwave.co.uk/dompdf_example_nobackgrounds.pdf) I've managed to create using an absolute positioned image is 737KB. Thank you very much for your help with this!
