### ISSUE TITLE
caption border is not rendered - upgrade from 0.7 to 0.8

### ISSUE THREAD

**Issue by Kitcat711** [dompdf/dompdf#1515]
In my HTML I use this:

``<caption style="border: 1px solid #BEBEBE;  line-height: 250%; vertical-align: middle;" class="grey">
``

after migrating from dompdf 0.7 to 0.8 the border is not rendered anymore.
here is my css file for table and caption:
```
table {
	border-collapse: collapse;
}

caption {
	color: inherit;
	text-align: center;
	vertical-align: middle;
}

```

Did I miss something? Is it an issue (did not find anything about it so far)?
Thanks

**Comment by bsweeney** [comment]
Caption issues originally noted in #78.

**Comment by Kitcat711** [comment]
Thank you (sorry for the delay, was on vacation far far away from coding).
Workaround works fine

**Comment by cottton** [comment]
> Classes that define how to render such an element do not yet exist.

0.8.0 released this on Feb 19, 2017
Since then `<caption>` is broken.
It worked (afaik) perfectly at 0.7.0.

Now its mid 2019 and still broken?
We are forced now to upgrade to at least 0.8.0 due to composer requirements (PHP 7.2 ...)
and BAM - broken pdfs right in the face.

`display: block;` and|or `page-break-after: avoid;` suggestions do not work.

So this is now what we get: 

    <!DOCTYPE html>
    <html>
    <body>
    <table style="width: 100%;">
        <caption style="display: block; page-break-after: avoid;">
            1, 2, 3
            <br>
            4, 5, 6
            <div>7</div>
            <div>8</div>
        </caption>
        <thead>
        <tr>
            <th>one</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
        </tr>
        </tbody>
    </table>
    </body>
    </html>

![image](https://user-images.githubusercontent.com/13582504/61273378-a3260400-a7a9-11e9-9faa-0e4197808e27.png)

Can we expect a fix? Or should we forget about caption?

**Comment by Mellthas** [comment]
With #2722, `table-caption` elements will be properly treated as `block` elements, so borders and backgrounds render again by default. Full support for the display type would be even nicer, but this addresses the issue at hand.
