### ISSUE TITLE
(Failed to load PDF document.) in google chrome

### ISSUE THREAD

**Issue by raminsherwani** [dompdf/dompdf#1538]
how i can fix this problem (Failed to load PDF document.) in google chrome
file not showing in google chrome

**Comment by bsweeney** [comment]
Do you have a sample PDF or (preferably) link to a PDF on your site that does not load in chrome?

**Comment by raminsherwani** [comment]
thank you, problem fixed

**Comment by evseevnn** [comment]
@raminsherwani good but how?

**Comment by fantasticmachine** [comment]
Could you explain *how* this was fixed so that others might be able to solve the same problem?

**Comment by raminsherwani** [comment]
![inciodompdf](https://user-images.githubusercontent.com/13710563/30834049-2e77ded6-a25a-11e7-9119-7fa16a744246.png)

**Comment by sanishan** [comment]
I have same problem, Its because PHP error also included in PDF, open your Download PDF in notepad and you will there will be some errors.

Thanks,

**Comment by gcc32** [comment]
Same problem here!

**Comment by wimurk** [comment]
Anyone found a fix? Looks like chrome likes to destroy dompdf with every update

**Comment by tubbytoey** [comment]
I have same problem, Anyone found solution to fixed it?

**Comment by jannis24** [comment]
I have used dompdf in combination with wordpress and there occured the exact same problem. My solution was to stream the pdf before wordpress fires its hooking system. I have done this with including $dom->stream("dompdf_out.pdf", array("Attachment" => 0)); in my plugin construct instead of my 'wp' hook.

I guess Wordpress set's already some header parameters before that. 
If you still face the issue, try to fire the stream as early as possible. 

(I have also set an exit() after the stream)

**Comment by karthick4in** [comment]
add top of  your code.
date_default_timezone_set('Asia/Kolkata');

**Comment by SorenV** [comment]
Late to the game but this worked for me.  

Per this answer: https://stackoverflow.com/a/5982518.  Opening my pdf in a text editor the html was indeed included.

Referencing the documentation: https://github.com/dompdf/dompdf/wiki/Usage#php-example-with-ob_start
I was doing it wrong by using "ob_get_contents();" instead of "ob_get_clean();", which does not clear the output buffer thus including it in the pdf and causing chrome to consider it corrupted.

**Comment by sanishan** [comment]
> I have same problem, Its because PHP error also included in PDF, open your Download PDF in notepad and you will there will be some errors.
> 
> Thanks,


@SorenV I have already answered!

**Comment by Arbazbms** [comment]
> I followed multiple suggestions, but this was the answer in my case. Just add ob_get_clean() before calling the library code to stream the content.
> 
> > I was doing it wrong by using "ob_get_contents();" instead of "**ob_get_clean()**;", which does not clear the output buffer thus including it in the pdf and causing chrome to consider it corrupted.

This worked for me
