### ISSUE TITLE
dompdf isn't rendering the same way on localhost and on server

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#154]
_Original author: JiPi00 (May 03, 2010 19:53:34)_

Problem: 
Text superposition on wordwrap, it happens only on linux serveur(Centos,
PHP 5.2.1)... 
It's rendering fine on my windows dev computer (Wamp, PHP 5.3)....

DomPdf version: 0-6-0_beta1 ( Server and localhost)

See file : serveur.jpg = Text superposition bug
           localhost.jpg = Well rendered

What can cause this ?

Thanks for help

localhost:
![localhost](https://github.com/dompdf/dompdf/assets/485897/5411c6e0-560f-4b30-8c6e-f33b193ed2f3)

serveur:
![serveur](https://github.com/dompdf/dompdf/assets/485897/9d4ccc7d-7aba-44ff-a197-da5beb774244)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=148_

**Comment by sunco007** [comment]
Hello, good day, in May 2024 I am experiencing the same issue. On my Windows machine, it works fine, but not when I upload it to the server with Linux.

It does render, but the lines are not aligned and an image I upload does not respect transparency.

I was checking in the log.html file and I see that $this->currentFont is always empty.

I don't know if there is something to check if the necessary libraries are correct.

Unfortunately, due to force majeure, I cannot change the PHP version and I am using 5.6.40 and DomPDF version 0.8.3.

I know there have been a lot of changes since then, but maybe it is something specific to utf8 or something that another user has already resolved at some point.

This is the only font I use - <link href="https://fonts.googleapis.com/css2?family=family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

I am attaching 2 images.

![image](https://github.com/dompdf/dompdf/assets/622200/4286c5a7-0d6d-446f-9672-fc947a068616)

![image](https://github.com/dompdf/dompdf/assets/622200/81410d77-9cc6-403b-b54a-210f85516616)

**Comment by bsweeney** [comment]
@sunco007 recommend you [start a discussion](https://github.com/dompdf/dompdf/discussions/new/choose). But a quick piece of advice, I wouldn't upload Dompdf to your server I'd install it fresh. Or at least exclude the font family caching file (ompdf_font_family_cache.php, leave the .dist file) because those paths are going to have to be re-generated.

**Comment by sunco007** [comment]
Thanks man, that helps me. Now I see all aligned. Only thing still not work, is bold font. Will try some stuff I see in Issues part
