### ISSUE TITLE
Dynamic external css is not working

### ISSUE THREAD

**Issue by AndriusCTR** [dompdf/dompdf#1562]
If I use css file which is not physically stored in a directory, but it loads content dynamically (path leads to a php script which loads css content), then dompdf won't fetch the content of such file....

is there any way to make it work? any setting?

let's say $html contains such line:

`<link rel="stylesheet" type="text/css" href="/style.php">`

The styles won't be loaded....

**Comment by MichaelEugeneYuen** [comment]
@AndriusCTR I use

```
$content = file_get_contents('output.php');
$dompdf->loadHtml($content);
```

And I just have just tested output.php with

`<link href="pdf.php" rel="stylesheet">`

It worked fine with proper css

**Comment by AndriusCTR** [comment]
Ok, that's interesting....

Can you show me the content of your test code? what is inside pdf.php and the full code that you run? any settings / options?

I use:

```
	$dompdf = new Dompdf();
	$dompdf->loadHtml($page);
	$dompdf->render();
	$output = $dompdf->output();
	file_put_contents('Invoice.pdf', $output);
```

and it's not working for me....

**Comment by MichaelEugeneYuen** [comment]
My pdf.php (css)

```
@font-face {
  font-family: 'Droid';
  font-style: normal;
  font-weight: normal;
  src: url('dompdf/lib/fonts/DroidSansFallback.ttf') format('truetype');
}

* {
	margin: 0;
	box-sizing: border-box;
}

html {
	padding-top: 10px;
	background: #e6e6e6;
	text-align: center;
}

body {
	width: 730px;
	font-family: 'Droid', 'Helvetica';
	font-size: 14px;
	padding: 30px 40px;
	text-align: left;
	margin: 0 auto;
	background-color: #FFF;
}

.page_break { page-break-before: always; }

h2 {
	margin-top: 8px;
	margin-bottom: 15px;
}

table {
	border-collapse: collapse;
	margin: 8px 0;
}

table th, td {
	padding: 8px 14px 8px 14px;
	border: 1px solid #333;
}

.text-center {
	text-align: center;
}

img {
	max-width: 100%;
}
```

My output.php

```
```
<!DOCTYPE html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link href="pdf.php" rel="stylesheet">
</head>
<body> 
<div class="wrapper">
<div class="title" style="display: inline-block; position: absolute; top: -20px; left: 0; right: 0; text-align: center; margin: 0 auto; width: auto;">Title</div>
<table cellspacing="0" cellpadding="0" style="background-color: #c6c6c6; color: #FFF; table-layout: fixed; width: 100%;">
	<thead>
		<tr>
			<th class="text-center">Chinese</th><th class="text-center">Korean</th><th class="text-center">English</th><th class="text-center">Russian</th>
		</tr>
	<tbody>
		<tr>
			<td class="text-center">天空</td><td class="text-center">하늘</td><td class="text-center">Sky</td><td class="text-center">Небо</td>
		</tr>
	</tbody>
</table>
<p>page-break</p>
<div style="width: 100px;"><img src="http://brandongaille.com/wp-content/uploads/2013/07/Dell-Company-Logo.jpg"></div>
<h2 style="text-align: center; background-color: #6d80f5; color: #fff;">Something here</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, <strong>when</strong> an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<p></p>
<p></p>
<p>Why do we use it? <a href="http://google.com">External LInk<a></p>
<br>
<br>
<p><img src="image.jpg" style="float: right; width: 200px;">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
<br>
<br>
Where does it come from?<br>
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<br>
<br>
<p>Why do we use it?</p>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<br>
<br>
<p>Where does it come from?</p>
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
<br>
<br>
<p>Why do we use it?</p>
<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
<br>
<br>
<p>Where does it come from?</p>
<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
<div>

</body>
</html>
```

My index.php

<?php
ini_set('display_errors',1); // enable php error display for easy trouble shooting
error_reporting(E_ALL); // set error display to all
require_once 'dompdf/autoload.inc.php';
// require_once 'dompdf/lib/html5lib/Parser.php';
// require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
// require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
// require_once 'dompdf/src/Autoloader.php';
// Dompdf\Autoloader::register();

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$content = file_get_contents('output.php');

$dompdf->loadHtml($content);

$dompdf->set_option('fontHeightRatio', 0.6);
// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
// $dompdf->stream();

$output = $dompdf->output();
file_put_contents('doc.pdf', $output);

?>
```

**Comment by bsweeney** [comment]
Dompdf is an HTML+CSS parser. If you want to dynamically generate the CSS (in pdf.php) you'll need to do it before passing it to Dompdf. The way you would typically do this is to access it via your web server. If you load a file from the file system you'll just get the source of the file.

**Comment by AndriusCTR** [comment]
@bsweeney but MichaelEugeneYuen says it's working for him.... ? (dynamic css link inside html)

**Comment by MichaelEugeneYuen** [comment]
@AndriusCTR , spend some time to study my files. 
`$content = file_get_contents('output.php');`
when file_get_contents() is used, output.php will be executed and pdf.php will be called.

And don't forget to use proper header in pdf.php (css file)

```
<?php
    header("Content-type: text/css; charset: UTF-8");
?>
```

```
$dompdf = new Dompdf();
$content = file_get_contents('output.php');
$dompdf->loadHtml($content);
```

**Comment by bsweeney** [comment]
`file_get_contents("output.php")` would fetch the file output.php from the local file system. Because this doesn't go through any intermediaries there is no PHP parser involved and so you'll get just the PHP source code.

To get the the parsed PHP you need to go through an intermediary, typically your web server. I.e. `file_get_contents("http://example.com/output.php")`.

Same goes for Dompdf. If you load a document from a file on the local filesystem (`$html = file_get_contents("output.php"); $dompdf->loadHtml($html);` or `$dompdf->loadHtmlFile("output.php")`) you get the source of the file. Not a problem for HTML, but for PHP it will not be parsed. This holds for any resource references within the document as well. So a reference to a dynamically generated CSS file will still only fetch the source and not the parsed document.

This is because Dompdf uses the same protocol to load references as the original file. So if the original file is fetched via the file system then any resource references are also fetch via the local file system. Unless a specific protocol is specified in a fully qualified URI.

**Comment by AndriusCTR** [comment]
OK so I just had to add full absolute path to dynamic css and everything works.

    <link rel="stylesheet" type="text/css" href="https://myserver.com/pdf.php">

case closed.

**Comment by MichaelEugeneYuen** [comment]
@bsweeney , thanks for the update. You are correct. I didn't actually tested my pdf.php with variables.

**Comment by donjajo** [comment]
Well, I had to give write permission to dompdf/lib/fonts directory and everything worked. Both external font from Google and local fonts. Didn't know it has to download and cache the fonts

**Comment by bsweeney** [comment]
@donjajo yes if you are loading a font dompdf needs to be able to load it. Perhaps sometime in the far future we'll modify dompdf to support non-writable environments using memory streams or something like that. It'd be more memory-intensive, but would work regardless of file system permission.

At the same time we can hopefully build out support for low-memory systems using more filesystem read/writes (which would be slower).
