### ISSUE TITLE
Using dompdf

### ISSUE THREAD

**Issue by jejedu67** [dompdf/dompdf#1607]
Hi,

I upload the dompdf folder on my FTP, on the FTP I have an index.php page with:

```
<?php
require_once 'dompdf/autoload.inc.php';
// reference the Dompdf namespace
use dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
?>
```

But I have a server error 500 ...

Can you help me ?

Thank you very much.

**Comment by bsweeney** [comment]
500 errors are generated by your server when there's an exception. We'd need to know what the actual error is before we could offer much help.

Which version are you using? I see you have a use statement, but it should be `use Dompdf\Dompdf;` if you're using the latest release.

**Comment by jejedu67** [comment]
Thank you, it works with `use Dompdf\Dompdf;`

**Comment by Tactical-Gears** [comment]
Hello there, i am new to github, hope i can participate here.. I also upgraded to the latest version. I also added the dompdf folder via Ftp and replaced my older version with no problems, i did do a backup.... In my site when i try to download PDF invoice, it downloads a pdf with "hello world" from one of the require codes. (I think i need to call the right filename or something instead of hello world). I  found a seperate function on my functions.php file which needs updating perhaps (see below).. If any of you can make a little time to help me i really appreciate it as i know alot of you people are really busy.. Thanks in advance..

Where it gets the "hello world".
![screenshot 2018-02-04 at 06 39 02 am](https://user-images.githubusercontent.com/36129615/35777756-e2f5cee2-0978-11e8-993d-41c9cdf7c3a8.png)

Where i download PDF invoice.
![screenshot 2018-02-04 at 06 34 24 am](https://user-images.githubusercontent.com/36129615/35777768-126570a6-0979-11e8-97de-8708364207d1.png)

The function on functions.php file:
![screenshot 2018-02-04 at 06 34 47 am](https://user-images.githubusercontent.com/36129615/35777781-606e5e02-0979-11e8-86fd-52ebab11feff.png)

The PDF download "hellow world":
[document-6.pdf](https://github.com/dompdf/dompdf/files/1692794/document-6.pdf)
