### ISSUE TITLE
Rendering fonts in Questions Marks(?) except english font 

### ISSUE THREAD

**Issue by hridesh123** [dompdf/dompdf#1658]
Hello there, 
       I am using dompdf version 0.8.2 to generate pdf with english, arabic and russian fonts. Each characters appears in one round box like [a]. Now the problem is except english font, everything appears like this ????.
I have used css font-family: DejaVu Sans; but still problem exist. Would anyone help me out how to add ttf file for russian and arabic font.

**Comment by turboenator** [comment]
Same w Vietnamese :(

**Comment by bsweeney** [comment]
Old question, but I'll just note that you need to ensure your font has supporting glyphs for the characters you want to display. DejaVu is an improvement over the core PDF fonts (which only support Windows ANSI) but it's still a ways away from full Unicode support.

Beyond that tidbit, we would need to see your HTML to have a sense of what the issue is.
