### ISSUE TITLE
Strange internal problem

### ISSUE THREAD

**Issue by shawe** [dompdf/dompdf#1668]
It was happening to me using PHP 7.1.14 and 7.2.2, and I change dompdf from 0.8.0 to 0.8.2 to try if something happens different, but seems to be the same problem.

This error occurs to me when call new Dompdf object:
$dompdf = new Dompdf($options);
$dompdf = new Dompdf();

File: vendor/dompdf/dompdf/src/Adapter/CPDF.php
Line: 216
Message: Uncaught Error: Call to protected method Cpdf::getFirstPageId() from context 'Dompdf\Adapter\CPDF' in vendor/dompdf/dompdf/src/Adapter/CPDF.php:216 Stack trace: #0 vendor/dompdf/dompdf/src/CanvasFactory.php(57): Dompdf\Adapter\CPDF->__construct('letter', 'portrait', Object(Dompdf\Dompdf)) #1 vendor/dompdf/dompdf/src/Dompdf.php(294): Dompdf\CanvasFactory::get_instance(Object(Dompdf\Dompdf), 'letter', 'portrait')...

I change this protected method to public, and the error was change to another line, but still not working. 

File: vendor/dompdf/dompdf/src/Adapter/CPDF.php
Line: 477
Message: Uncaught Error: Call to undefined method Cpdf::setLineTransparency() in vendor/dompdf/dompdf/src/Adapter/CPDF.php:477 Stack trace: #0 vendor/dompdf/dompdf/src/Adapter/CPDF.php(521): Dompdf\Adapter\CPDF->_set_line_transparency('Normal', 1) #1 vendor/dompdf/dompdf/src/Renderer/AbstractRenderer.php(910): Dompdf\Adapter\CPDF->set_opacity(1) #2 vendor/dompdf/dompdf/src/Renderer/Block.php(32): Dompdf\Renderer\AbstractRenderer->_set_opacity(1) #3 vendor/dompdf/dompdf/src/Renderer.php(293): Dompdf\Renderer\Block->render(Object(Dompdf\FrameDecorator\Block)) #4 vendor/dompdf/dompdf/src/Renderer.php(101): Dompdf\Renderer->_render_frame('block', Object(Dompdf\FrameDecorator\Block))...

Any idea that what can be happening and how to solve it?

Some time ago, I test to generate a PDF in same way, and no problem was happening to me, simply works. And this time was based with same PHP version, and dompdf 0.8.0, I look to same previous code to re-use it now.

**Comment by hiboutik** [comment]
composer remove rospdf/pdf-php should help

**Comment by gozeller** [comment]
Same problem here. I have to upgrade a zendframework version 1 (zf1) application to version 3 (zf3). The application uses both dompdf and rospdf, which worked with zf1 (it didn't use composer nor autoloaders). 

The problem is that dompdf uses an old(?) or modified(?) version of rospdf with class Cpdf (/lib/Cpdf.php) without a namespace. But the autoloader loads the Cpdf version of rospdf - these classes are not compatible.

Wouldn't it be nice to add a namespace to Cpdf? \Dompdf\Adapter\RosPdf\Cpdf maybe or just \RosPdf\Cpdf or something? I think it wouldn't affect lot of people because Cpdf is instantiated internal as an adapter.
