### ISSUE TITLE
Table caption rendered seperatly from the table.

### ISSUE THREAD

**Issue by greasedonkey** [dompdf/dompdf#1708]
Hi,

I'm outputting multiple table with a caption element and sometime the caption and table will be on different page.  Is there a way I can force the caption and table to at least start on the same page without enforcing a page break on all caption?

Thanks

**Comment by bsweeney** [comment]
Dompdf does not currently support the table-caption display type and so caption display is not correct. We essentially render the caption above the table as a block element (or at least [that's what's _supposed_ to happen](https://github.com/dompdf/dompdf/issues/1515)).

Because of how we're currently handling captions, what you might try is styling the caption with `page-break-after: avoid;`.
