### ISSUE TITLE
file_exists(): open_basedir restriction in effect. 

### ISSUE THREAD

**Issue by Mathijs333** [dompdf/dompdf#1709]
i'm getting this error (website name replaced with websecret):

> file_exists(): open_basedir restriction in effect. File(/tmp/log.htm) is not within the allowed path(s): (/home/websecret/web/websecret.com/public_html:/home/websecret/tmp)

i suppose that public_html: shouldn't contain the ':', also there's no such folder in there called home.
The folder is in web, how come it's trying to access a non existing location?

**Comment by bsweeney** [comment]
And old one, but still relevant. I supposed the OP has resolved and/or moved on but for anyone else interested be sure to specify the appropriate directories for temp files before running dompdf. The relevant settings are:

 - tempDir
 - fontDir
 - fontCache
 - logOutputFile

I think we'll also look at resolving Dompdf's inability to write to the filesystem using #842.

**Comment by MatthiasKuehneEllerhold** [comment]
We've got a similar problem: If you're using images with local paths the Helpers.php (line 79) wants to realpath the root (/) and open_basedir restrictions lead to realpath returning false.
Any fix for this?

**Comment by bsweeney** [comment]
Since this is a configuration issue I'm going to close. File write paths should be appropriately configured as described in my earlier comment.

As for the specific error, we will disable writing to the Dompdf log by default in the 2.0.0 release (#2810). As indicated there you can work around this issue now by setting the log file option to an empty string (`""`).
