### ISSUE TITLE
PDF with custom font uses wrong character mapping

### ISSUE THREAD

**Issue by rukusphil** [dompdf/dompdf#1717]
After tinkering A LOT, I was able to configure DOMPDF to use a custom font. The key lynchpin was the inclusion of the .afm and .ufm files in my dompdf/lib/fonts directory. I used an online service (https://everythingfonts.com/ttf-to-ufm) to generate those metrics files.

Unfortunately, any text that is displayed using the custom font appears to use an incorrect character mapping. In other words, when the webpage is displayed in my browser, the text with the custom font looks like this:

![image](https://user-images.githubusercontent.com/28958823/39023096-aee6e4f6-4406-11e8-914c-0b7040a224b4.png)

But when I generate the PDF file using DOMPDF the same text looks like this in the PDF:

![image](https://user-images.githubusercontent.com/28958823/39023112-c446af3e-4406-11e8-91f3-a408b2533d76.png)

The rest of the text in the PDF that is not displayed with the custom font shows up fine.

When I copy and paste that custom font text from the PDF to a text editor, it shows up correctly (in this case it's the alphabet in lowercase):

![image](https://user-images.githubusercontent.com/28958823/39023221-61afe8ee-4407-11e8-9150-1fbf583f37a9.png)

Does anyone know what might be wrong with my setup? Could the afm/ufm files be to blame?

Thank you in advance.

**Comment by bsweeney** [comment]
The font metrics files shouldn't be causing this issue since they're used primarily to measure text dimensions. This looks like an incorrect mapping between the character and the glyph in the font file, which could be caused by an incorrectly generated font subset.

This is an old issue, guessing you don't need help anymore. Would need to get more details to determine exactly what's going on here.
