### ISSUE TITLE
bold style cannot be cache/parse from CDN/Google Fonts

### ISSUE THREAD

**Issue by rmondesilva** [dompdf/dompdf#1748]
I tried to use Google Fonts or this: https://h-ibaldo.github.io/Raleway_Fixed_Numerals/ by linking it in head tag of HTML Document.

<link href="https://cdn.rawgit.com/h-ibaldo/Raleway_Fixed_Numerals/master/css/rawline.css" rel="stylesheet">

It works on normal font-weight but not on bold.

Here is what my **dompdf_font_family_cache.php** looks like:
```
'rawline' => array(
    'normal' => $fontDir . '\e0ea57e71614f1ba166fdc2784b41109',
    'italic' => $fontDir . '\cb3adc31db7d2426d7f9b8da89dcf153',
),
```

bold and bold_italic is missing.

**Comment by Sattevelt** [comment]
I ran into this error too and have been able to determine what goes wrong.
Google fonts outputs font css weights as a number (multiple of 100. for example: 400 is normal, 700 is bold. There are other values too)

When parsing this css to register it in `dompdf_font_family_cache.php`, the font weight gets combined with the style to create a key to register it in said file. The regex used in `DomPDF\FontMetrics:getType` is `preg_match("/bold/i", $type)` to register it as a 'bold' or 'bold_italic' style. Since the weight is numeric, the regex fails and gets the style gets defaulted to 'normal'.

If you use two font of the same family, one normal and the other bold, only one of them will work (depending on which one you registered first) because they will both be marked as 'normal'.

The fix that works for me is to change this regex to `preg_match("/(bold:700|800|900)/i", $type)`. It will match the numeric values for bold weights and will be registered correctly as either 'bold' or 'bold_italic'.

I would make a PR, but i'm not sure if this fix is the desired one. 
In `Dompdf\Css\Style::get_font_family()` there is also logic to assume any numeric value equal to or bigger than 600 as 'bold'. I'm not sure if this would be okay.

**Comment by bsweeney** [comment]
The enhancement request for this feature can be found in #675.
