### ISSUE TITLE
Line break problem

### ISSUE THREAD

**Issue by ConstantMath** [dompdf/dompdf#1759]
Hi, any idea why I have line breaks appearing even if I put non-breaking spaces in my html source ?

Here is the html source 

 ![line break 1](https://cloud.variable.club/index.php/apps/files_sharing/ajax/publicpreview.php?x=1280&y=891&a=true&file=lb-2.png&t=xmDrH42dJQFbyM5&scalingup=0)

Here is the pdf result 

![line break 2](https://cloud.variable.club/index.php/apps/files_sharing/ajax/publicpreview.php?x=1280&y=891&a=true&file=lb-1.png&t=xti8sQ2oNYpXBjm&scalingup=0)

Thanks for your help ;-)

**Comment by bryndyment** [comment]
I am having a similar problem where line breaks are occurring between a character and a tag:

`(the “<span class="font-bold">Effective Date</span>”)`

The line break is appearing between `“` and `<span …`.

**Comment by bsweeney** [comment]
Looks like are text-splitting logic currently splits on nbsp as well as a regular space. Should be able to fix that up for the next release.

@bryndyment your problem is covered in the other issue you've commented in.

**Comment by kpijarski** [comment]
@bsweeney @bryndyment – could you please point me to the the other issue, regarding the "problem where line breaks are occurring between a character and a tag"? I am facing the same problem, is it solved? I am in final weeks of setting up a backend for a digital academic journal with automatic pdf output, and we are ending up with pdf's, where single periods, commas, parantheses end up in new lines because they are preceded by tags like </sup> </em>, but no space!

**Comment by bsweeney** [comment]
@kpijarski still no solution to the problem with text abutting inline element. The other issue references is #1036.

**Comment by kpijarski** [comment]
@bsweeney thank you for pointing me in the right direction. OK, so we wait :)

**Comment by bsweeney** [comment]
The nbsp issue is resolved. Follow 1036 for updates on the issue related to inline elements.
