### ISSUE TITLE
Resize html

### ISSUE THREAD

**Issue by josielmoraes** [dompdf/dompdf#1772]
my html page has width of 1024px how to resize to save in pdf with A4 sheet

**Comment by bsweeney** [comment]
Dompdf by default uses a DPI of 72, which matches 1-to-1 with the PDF pt resolution. The width of an A4 page is 595pt, or a little more than half of your HTML page. Quickest way to get it to fit the width (without changing to landscape orientation) would be to double the DPI. Dompdf will then translate 2-to-1 anything specified in PX units.

**Comment by arimourao** [comment]
@bsweeney Hi, I'm having an issue and your comment above could be my solution. I have a .dll that generates some HTML that I need to export to pdf. Everything is working fine but the pdf is cutting in half what the HTML shows in normal screen. I already tried to tweak with the CSS properties, but to no avail.
What I needed was some kind of "zooming out". If I could zoom out by 20 or 30% it would fit perfect. Sorry if this is not the appropriate channel for doubts but I'm running out of time. Any help would be greatly appreciated.

**Comment by bsweeney** [comment]
@arimourao since you were short on time I'm sure you've already moved on. If you do need help feel free to start a new issue or post to the support forum. Briefly, though, you set the Dompdf dpi via the setting method, e.g. `$dompdf->set_option('dpi', '300dpi');`. It's not perfect, but can help if your styling doesn't use PT units when defining lengths.
