### ISSUE TITLE
Romanian characters ar not displayed!

### ISSUE THREAD

**Issue by AndreiGhitan** [dompdf/dompdf#1793]
I am trying to get this fixed somehow. When I render the pdf, all the romanian characters like ' ăâșțî ' are completely missing.

Can anyone help me sort this out?

**Comment by dandinuro** [comment]
Same here :(

**Comment by bsweeney** [comment]
This seems more like an encoding issue than a problem with dompdf, but to start have you looked at the [Unicode How-to](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)?

**Comment by Cyrille37** [comment]
I need to generate pdf for many languages and I had to find many different fonts. What a pain in the ass !

A good one is "Deja Vu" but missing some languages like JP and KO.

I do not know about licence but I found the "[Arial Unicode MS](https://www.wfonts.com/font/arial-unicode-ms)" that works with all my needed languages, and also for Romanian.

**Comment by bsweeney** [comment]
Arial Unicode MS doesn't look to be freely licensed since the MS site links out to Monotype (https://docs.microsoft.com/en-us/typography/font-list/arial-unicode-ms).

[This post on SO](https://stackoverflow.com/a/34734338/264628) nicely described the dilemma. I think ideally what needs to happen is for us to implement #913, so be sure to subscribe to updates to that issue.
