### ISSUE TITLE
DOMPDF cant Change paper size 

### ISSUE THREAD

**Issue by romandahidayat** [dompdf/dompdf#1797]
Hello guys, i was create some project with printing media HTML to pdf using DomPDF, when i try to change to $this->pdf->Set_Paper(), result pdf still on legal size but i want to change size to  F4 21.5 cm x 33 cm but result is still 8.5x14.0 inc (21,59cm x 35,56cm), this is my code to load html page to download the pdf.

`$this->load->view('admin_surat/layout_surat/'.strtolower(url_title($layout['surat_template_name'],'_')).'/index',$data);
			$html = $this->output->get_output();
					
			// Load pdf library
			$this->load->library('pdf');
			$this->pdf->setPaper('f4', 'potrait');
			$this->pdf->set_option('isRemoteEnabled', TRUE);
			// Load HTML content
			$this->pdf->loadHtml($html);
			
			// (Optional) Setup the paper size and orientation
			//$this->pdf->setPaper('f4', 'potrait');
			
			
			// Render the HTML as PDF
			$this->pdf->render();
			
			// Output the generated PDF (1 = download and 0 = preview)
			$this->pdf->stream("'.$surat->surat_perihal.'.pdf", array("Attachment"=>0));`
I need help to solve this problem, thanks before

**Comment by bsweeney** [comment]
f4 isn't among the [supported paper sizes](https://github.com/dompdf/dompdf/blob/v0.8.2/src/Adapter/CPDF.php#L45) and, in fact, doesn't appear to be an official one either ([w](https://en.wikipedia.org/wiki/Paper_size#F4)).

Still, that doesn't mean you can use it, you just have to pass in the dimensions instead of the common name (`setPaper(array(0,0,609.4488,935.433), 'portrait')`).
