### ISSUE TITLE
Last page with special footer

### ISSUE THREAD

**Issue by ivolvicente** [dompdf/dompdf#1852]
I need to add a resume section on the bottom of the last page.

I can do that with `position: fixed` but this is for an invoice system, and sometimes the table (data) lines get overlaped by the resume section.

I have used empty lines and make some calculations for the lines to force a new page and worked (sort of)  but if the document get a bigger header information everything became out of place.

Any ideia? Can i get how much free/empty space left between the body (image: blue line) last section printed (image: red square) and the footer?

![image](https://user-images.githubusercontent.com/11926387/49451212-959daa00-f7d6-11e8-9f1a-e93d1bd780cb.png)

**Comment by macolmenero** [comment]
Hello,
I have the same problem. Did you get it?
I want to put the last footer a table with payment conditions
Thansk!
best regards
Miguel

**Comment by bsweeney** [comment]
Also, I guess I wouldn't use fixed positioning for last-page-only content. I'd use absolute positioning. But that's semantic since if it comes after all the other content it will only render on the last page anyway.

I think to truly support this we'd need to add some way to select the page. Maybe with a non-standard `@page :last {}` selector. Though adding non-standard selectors is low on the list right now.

More thought needed.

**Comment by macolmenero** [comment]
Hello,
Thanks for you help!
We have resolved calculating lines for page and page we need.
And whe we arrive at that line we alter we calculating if our table (it is a footer) insite or no. And this moment we insert  a break page <style="page-break-after:always;"></div> and then print the table.
This table we put in style position:fixed.
Probably is not the best solution, we begin to use today.
