### ISSUE TITLE
Autoloader missing in version 0.8.3

### ISSUE THREAD

**Issue by acicovic** [dompdf/dompdf#1862]
Hi,

The 0.8.3 release seems to be lacking a autoload.inc.php file. Is this on purpose?
Would copying the autoloader from 0.8.2 do the job?

Thanks!

**Comment by robdigital** [comment]
copying autoloader from 0.8.2 doesn't work, gives a further error, "dompdf/lib/php-font-lib/src/FontLib/Autoloader.php"

**Comment by robdigital** [comment]
Ok so I copied the autoloader from 0.8.2. as well as the following 3 folders in dompdf/lib/ 
1)php-css-parser
2)php-font-lib
3)php-svg-lib

And now it is working fine.

**Comment by 5280pixel** [comment]
@robdigital - Thank you! This was driving me crazy!

**Comment by bsweeney** [comment]
The autoloader was removed from the git repo because we don't provide all the necessary libraries. The readme does indicate what you need to do if you're using the git repo (though I do need to add information related to the CSS parser used by php-svg-lib).

I plan to add some of the things we removed to the utils project but haven't had a chance yet.

**Comment by bsweeney** [comment]
Added additional information to the README, with a link to the autoloader we use for packaged versions.
