### ISSUE TITLE
Fonts error

### ISSUE THREAD

**Issue by striderxfossility** [dompdf/dompdf#1863]
Greetings, 

I got a error with the new update, the font style was not loading, exception.

It is fixed by editing dompdf_font_family_cache.php by replacing all `\` to `/`.

i guess when i update the composer again this will be set back? please fix it.

**Comment by bsweeney** [comment]
Did you mean to close this? On what system are you running?

I was looking at the code and I think I see where things could be going wrong. We use `DIRECTORY_SEPARATOR` to delineate the path in the FontMetrics class. Really in this case it should be safe to use "/" for that. Additionally, since we write this information to a file to read in the future we should use `addslashes` to ensure we're escaping the strings prior to writing to the file. We do this for the font name but not for anything else written to the file.

**Comment by striderxfossility** [comment]
Greetings, i do not have this error anymore after updating everything, is that correct? :) if I have this error i can replace all the / into \ i did it the last 3 times when updating, but lately i dont have this problem anymore.

**Comment by bsweeney** [comment]
Yes, if you experience the error again try replacing `\` or `\\` with `/` in the generated dompdf_font_family_cache.php file. Or remove the file completely on the target system.
