### ISSUE TITLE
Not render html if it is big.

### ISSUE THREAD

**Issue by polereczkitamas** [dompdf/dompdf#1891]
Hi,
I'm using dompdf latest version to print my html, it works fine, but if my html is too big, than it's not working. My html attached.
my code:

```
require 'vendor/autoload.php';

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
//$dompdf->loadHtml($html, 'UTF-8');
$dompdf->loadHtml($html);

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
//$dompdf->stream();
$dompdf->stream($filepath, array("Attachment" => 0));
```

[print.zip](https://github.com/dompdf/dompdf/files/2836118/print.zip)

**Comment by bsweeney** [comment]
Don't necessarily need to review the code, but it would help to know what you mean by "not working." Do you get any errors from PHP or your web server?

**Comment by polereczkitamas** [comment]
The render line is not loading, the browser goes to error. How can I record the php errors?

**Comment by bsweeney** [comment]
You should read up on how to use logging with your configuration. It's a pretty basic necessity when you're trying to debug problems. Google is your friend there: 
https://www.google.com/search?q=php+error+logging

At the very least you can add `ini_set('display_errors', '1');` to the top of your PHP file, but that's not recommended for production systems.

**Comment by polereczkitamas** [comment]
Here is the error:
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 3072 bytes) in .../dompdf/include/text_frame_reflower.cls.php(376) : runtime-created function on line 1

any suggestion?

**Comment by bsweeney** [comment]
That's 32MB allocated for PHP execution. Not a small amount, but the document you're rendering obviously requires more. I'd try doubling or tripling it (if you have that level of control over your system).

`init_set('memory_limit', '96M');`

Otherwise we'd need to see the HTML you're attempting to render to see if there are any optimizations to the structure that would help.

**Comment by polereczkitamas** [comment]
It's working, thanks. My html attached to my first post if you want to see.

**Comment by bsweeney** [comment]
Ah, yes. Sorry, I managed to miss the attachment.

Your document isn't really all that large. I didn't quite reach that level of memory usage when I rendered, but that could just be because I didn't have access to some of the resources used (e.g. the logo image). Since the rendered PDF is compiled in-memory the more resources require more memory. I'd like to investigate alternatives for low memory situations (e.g. persisted to the file system) but those would come at the cost of performance. Also, it's a low priority right now.

I noted that you use fixed table layout, so you should keep an eye on #1432.

Glad you were able to get it working.
