### ISSUE TITLE
@page :first is having no affect

### ISSUE THREAD

**Issue by gavin310** [dompdf/dompdf#1898]
I'm using the latest version of DOMPDF. In my HTML I have:

```
<style type="text/css">
	@page {
		size: letter portrait;
		margin: 200pt;
	}
	@page :first {
		margin: 0;
 	}
</style>
```

The problem is that the `@page :first` style is having no affect on the margin. `@page {}` works fine, but the `:first` selector does not work. Any ideas why?

**Comment by bsweeney** [comment]
Looks like we broke something with the latest release. It also looks like starting with 0.8.0 margin collapse applies to the body, affecting page margins. More investigation is in order.

We'll take a look and patch for the next release.

**Comment by gavin310** [comment]
Thanks for the quick response. Do you have a rough estimation on when the next release might be? I know you maintain this package in your free time, so I really appreciate the work you put into it. Thank you!

**Comment by bsweeney** [comment]
Thanks for being understanding. Hard to say as far as time frame. I'm ever too optimistic so I probably shouldn't even hazard a guess. You can see what I've slated for the next release in the 0.8.4 milestone. Nothing overly aggressive in that list, and some things may push to the following release. The few CSS-related issues there I think I'm going to tackle first since right now they look to probably quick fixes. At that point you could download a nightly (if you're using the packaged version) or require dev-develop in your Composer configuration.

**Comment by gavin310** [comment]
Totally understandable. I'll keep an eye out for any updates and switch over to the nightly build. Thanks!

**Comment by bsweeney** [comment]
FYI I only just recently fixed up the nightly so let me know if you have any issues with it.

**Comment by bsweeney** [comment]
Well, the two bugs I found were both pretty easy to fix. The nightly download currently updates once a day so these changes should be available tomorrow.

**Comment by gavin310** [comment]
Awesome! Thanks!

**Comment by bsweeney** [comment]
I believe this has been sufficiently addressed by the referencing commits. Please post back if you find otherwise.
