### ISSUE TITLE
PDF output not looking same on live server

### ISSUE THREAD

**Issue by borianm** [dompdf/dompdf#1942]
Hello,
I have an issue where the PDF output is not the same on my local server and on the live server. I checked the requirements via PHPINFO on the live server and the extensions and versions are okay:

PHP version 5.4.0 or higher
DOM extension
GD extension
MBString extension

Here is how the output looks on the local server:
http://prntscr.com/nx49j1 (I censored a small part with the name, if someone asks :D)
http://prntscr.com/nx49va
http://prntscr.com/nx4a00
http://prntscr.com/nx4a32

Here is how it looks on the live server:
http://prntscr.com/nx4ayt

PDF output script: https://pastebin.com/pBvuanAq
"HTML" part: https://pastebin.com/4kJudDYT

I figure that it is just not including the second style, just the bootstrap part. I tried to put the style inline, to include directly with an absolute URL, but nothing really helped. Every solution worked okay locally, but on live nothing changes.

Thanks in advance for the help :)

**Comment by bsweeney** [comment]
Are you copying Dompdf from your local server to the live one? It looks like maybe Dompdf is having trouble finding the font metrics. You could try deleting the dompdf_font_family_cache.php file. It should regenerate on next run.

**Comment by MarkMaldaba** [comment]
I had similar issues after upgrading DomPDF, with lots of overlapping text.  This was fixed by removing all the temporary font files that DomPDF creates, and allowing them to be regenerated.  I'm not sure if that is the problem in your case, but it's worth checking.

Note that, whilst removing the temporary files fixed the overlapping issue, there were a number of other issues introduced by the upgrade, which I'm still working through...  so even if this helps, it may not be sufficient!

**Comment by anilsaini81155** [comment]
Try clearing the cache on the live server.
