### ISSUE TITLE
Replace broken image placeholder

### ISSUE THREAD

**Issue by sadi304** [dompdf/dompdf#1969]
Is there any way to replace this default image placeholder? Or other ways to handle broken image from the html itself?

![Screenshot from 2019-07-29 12-37-45](https://user-images.githubusercontent.com/8942965/62026774-bf8c5c80-b1fd-11e9-9e1a-51cf60740894.png)

I have found several PHP related workaround. And HTML related workaround like onerror on img element doesn't work in DOMPDF.

**Comment by RiccardoCampo** [comment]
This is still a problem!

**Comment by bsweeney** [comment]
The `onerror` attribute is for JavaScript, so I wouldn't look at that as a possibility.

A future version of Dompdf will include improved resource handling support so that you could build your own error handling. Until that enhanced functionality is available you can set the default broken image and message as follows:

```
\Dompdf\Image\Cache::$broken_image = "/path/to/image.jpg";
\Dompdf\Image\Cache::$error_message = "";
```

The image should be from the local filesystem.

Note: starting with Dompdf 3.0.0 the [error message will no longer be displayed](https://github.com/dompdf/dompdf/commit/9024efe143e4b879100e95993d5c90f1c2ac5867). And if there's an alt attribute that will be displayed in place of the broken image indicator.

Are you looking for more functionality than that.
