### ISSUE TITLE
Base64 image results in file_put_contents(): Filename cannot be empty

### ISSUE THREAD

**Issue by joeybab3** [dompdf/dompdf#1971]
I am generating a pdf using DOMPDF and PHPBarcodeGenerator, but for whatever reason, I am unable to get DOMPDF to generate a pdf with a base64 encoded image.

I am using PHP 7.1.8, and DOMPDF v0.8.3.

Here is my code:

```
<?php
$html  = '<!DOCTYPE html>
<html>
<body>
<div style="text-align:center;">'.$number.'</div>
<div style="text-align:center;"><img src="data:image/png;base64,' . base64_encode($generatorPNG->getBarcode($code, Picqer\Barcode\BarcodeGeneratorPNG::TYPE_CODE_128_C, 2, 120)). '">' . '</div>
</body>
</html>';
	
// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml($html);

$customPaper = array(0,0,384,576); //4x6
$dompdf->setPaper($customPaper, 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream("barcodes.pdf", array("Attachment" => true));
?>
```

The above creates a pdf that "can't be opened" and opening it in a text editor reveals the following lines have been added by php:

```
<br />
<b>Warning</b>:  file_put_contents(): Filename cannot be empty in <b>/Applications/AMPPS/www/barcode/vendor/dompdf/dompdf/src/Image/Cache.php</b> on line <b>113</b><br />
```

**Comment by joeybab3** [comment]
The other thing I've tried is to generate the image in a separate file(image.php) and set the src to that but now though it works fine in the browser output, the pdf generation creates a box that says:
`Image not found or type unknown`
![Screen Shot 2019-08-01 at 11 30 37 AM](https://user-images.githubusercontent.com/2829457/62318063-d32f0180-b44f-11e9-8cb8-ff0201423ff7.png)
![Screen Shot 2019-08-01 at 11 29 56 AM](https://user-images.githubusercontent.com/2829457/62318064-d3c79800-b44f-11e9-8819-36f2cedb72bd.png)

**Comment by bsweeney** [comment]
That line of code uses a filename produced by `tempnam`. The temp file should be created in the directory specified by the tempdir option (`sys_get_temp_dir()` by default). I'm guessing the process utilizing Dompdf does not have write access to that directory.

We can add a bit more exception handling so that instead of an error you see the broken image placeholder.

**Comment by bsweeney** [comment]
Presuming that this was a permission issue the commit referencing this issue should provide sufficient information to identify the issue. The actual solution would be to specify a temp directory that Dompdf is able to read from/write to.

For a more frictionless solution keep an eye on #842, which implements support for read/write to MemoryStream instead of the filesystem.
