### ISSUE TITLE
Rounded corners (border-radius) on table elements

### ISSUE THREAD

**Issue by kennydude** [dompdf/dompdf#2013]
I'm trying to get `border-radius` working properly on PDF outputs. DomPDF just seems to ignore how I'm trying to style my table.

Example HTML which doesn't seem to work for me:

```
<style>
table {
  margin-bottom: 2em;
  border-collapse: collapse;
  border-spacing: 3pt;
  border-radius: 15px;
}
th,td {
  padding: 10pt;
  border: 1px solid #502481;
}
</style>
<table>
<tbody>
<tr>
<th>Header</th>
<th>Heading</th>
<th>Heading</th>
</tr>
<tr>
<td>1</td>
<td>text here lorem ipsum dolor sit amet, consectetur adipiscing elit</td>
<td>text here</td>
</tr>
</tbody>
</table>
```

Preferrably it's something to do with the CSS that isn't rendering the rounded corners due to the HTML coming from our CMS

**Comment by bsweeney** [comment]
Border radius is generally not applied when border-collapse is set to collapse. Because the border between cells is collapsed all edges connect meaning there isn't an area around which to draw a radius.

Based on your sample I'm wondering if you want the table itself to have a radius and not the individual cells. Collapsing the borders also affects the table, and maybe we could improve the handling here. With Dompdf what you would have to do is use uncollapsed borders and render a radius on the corner cells:

```
<style>
  table {
    margin-bottom: 2em;
    border-spacing: 0pt;
    border-collapse: separate;
  }

  th,
  td {
    padding: 10pt;
    border: 1px solid #502481;
  }

  table tr:first-child th:first-child,
  table tr:first-child td:first-child {
    border-top-left-radius: 15px;
  }

  table tr:first-child th:last-child,
  table tr:first-child td:last-child {
    border-top-right-radius: 15px;
  }

  table tr:last-child th:first-child,
  table tr:last-child td:first-child {
    border-bottom-left-radius: 15px;
  }

  table tr:last-child th:last-child,
  table tr:last-child td:last-child {
    border-bottom-right-radius: 15px;
  }
</style>
<table>
  <tbody>
    <tr>
      <th>Header</th>
      <th>Heading</th>
      <th>Heading</th>
    </tr>
    <tr>
      <td>1</td>
      <td>text here lorem ipsum dolor sit amet, consectetur adipiscing elit</td>
      <td>text here</td>
    </tr>
  </tbody>
</table>
```
