### ISSUE TITLE
Where to put local font files

### ISSUE THREAD

**Issue by Vectrex** [dompdf/dompdf#2030]
After reading a gazillion or so howtos and tutorials I'm still at a loss when I want to use my own custom fonts.

Code

```php
$pdf = new Dompdf();
$pdf->setPaper('A4');
$pdf->setBasePath(Application::getInstance()->getRootPath());
$pdf->loadHtml(SimpleTemplate::create('pdf/events.php')->assign('events', $eventQuery->find())->display());
$pdf->render();
$pdf->stream();
```
The template looks like that

```html

<style>

@font-face {
    font-family: "Verb";
    font-style: normal;
    font-weight: normal;
    src: url("fonts/pdf_fonts/verbcondregular.ttf") format("truetype");
}

table {
    font-family: 'Verb', serif;
    font-weight: normal;
}
</style>

<table>
...
</table>

```

The table is always rendered in serif. The Basepath points to the directory where index.php resides (`/var/www/tvt/web/`). The absolute path to the font is therefore `/var/www/tvt/web/fonts/pdf_fonts/verbcondregular.ttf`.

Installation was via composer, no additional font conversion or other "extra steps" were taken. The pdf_fonts directory is writable for all.

**Comment by bsweeney** [comment]
And no errors or warning in the logs? You might try using an absolute path the the font file to avoid path translation issues. Or ... is that font accessible via the web server (since it's in /var/www)? Might want to try accessing via URL instead of local path.

Also make sure your process has read/write access to the temp and font directories.
