### ISSUE TITLE
Count on null depricated in PHP 7.2

### ISSUE THREAD

**Issue by jheagle** [dompdf/dompdf#2047]
While in the process of upgrading a product to PHP 7.2, we ran into an issue where Adapter/PDFLib::_set_line_style performs a count on $dash. In some cases, $dash is null instead of an empty array.

It appears that this method was called with null because the calling methods have $style defaulted to null in the parameter lists.

I can see two possible solutions to this:
1. Update Adapter/PDFLib::_set_line_style to cast $dash to array:
```
    /**
     * Sets the line style
     *
     * @param float  $width
     * @param        $cap
     * @param string $join
     * @param array  $dash
     *
     * @return void
     */
    protected function _set_line_style($width, $cap, $join, $dash)
    {
+       $dash = (array)$dash;
        if (count($dash) == 1) {
            $dash[] = $dash[0];
        }
```
2. Update the default parameters that cause the null to be empty array:
Four methods in Canvas: line, rectangle, polygon, circle
Ex:
```
- function rectangle($x1, $y1, $w, $h, $color, $width, $style = null)
+ function rectangle($x1, $y1, $w, $h, $color, $width, $style = [])
```
Four methods in Adpater/PDFLIb corresponding to the Canvas methods
Ex:
```
     * @param float $x1
     * @param float $y1
     * @param float $w
     * @param float $h
     * @param array $color
     * @param float $width
-    * @param null  $style
+    * @param array  $style
     */
-  public function rectangle($x1, $y1, $w, $h, $color, $width, $style = null)
+  public function rectangle($x1, $y1, $w, $h, $color, $width, $style = [])
```

Both of these above solutions appear to resolve the issue and I can create a PR with a solution, let me know which is preferred and if you would like me to create the PR.

**Comment by jheagle** [comment]
More info regarding the above, this occurs while using PDFLib adaptor and providing an anchor tag with an href as the content to render as PDF. It seems the href is what leads down this path to the count error, excluding the href attribute is a work-around.

**Comment by bsweeney** [comment]
Finally fixed up my dev box so I can render with PDFLib. I can confirm, will fix for next release.

**Comment by bsweeney** [comment]
We're not typing the arguments to any of our functions yet so there's no guarantee that the call will be an array (despite the default). There are a lot of areas of the code where we make assumptions about the type and addressing that globally is not trivial. I think it makes sense to type the arguments, and once we do that then defaulting to an array makes sense.

Since this particular issue is triggered through standard rendering, we'll go ahead and patch it now. It looks like we can sufficiently address the issue by ensuring it's an array before operating on it.
