### ISSUE TITLE
My local laravel project is showing the dompdf outcome, but with NGINX it gives an error: can't load pdf document

### ISSUE THREAD

**Issue by gdm-1718-onademuy** [dompdf/dompdf#2131]
I'm using a droplet via Digital Ocean with an Nginx server.

This is the function in my Controller, which works fine when I run this locally.

    $user = auth()->user();
    $resultsCosi = DB::table('users')->join('result', 'users.id', '=', 'result.id')->where('users.id', $user->id)->where('result.questionnaire_id', 1)->get();
    $fullname = $user->lastname . " " . $user->firstname;
    $data = [
        'name' => $fullname,
        'percentageKenner' => $resultsCosi[0]->percentage,
        'percentagePlanner' => $resultsCosi[1]->percentage,
        'percentageSamenwerker' => $resultsCosi[2]->percentage,
        'percentageBedenker' => $resultsCosi[3]->percentage,

        'percentageExpert' => $resultsCosi[4]->percentage,
        'percentageUitvinder' => $resultsCosi[5]->percentage,
        'percentageRaadgever' => $resultsCosi[6]->percentage,
        'percentageDoordrijver' => $resultsCosi[7]->percentage,
        'percentageRealisator' => $resultsCosi[8]->percentage,
        'percentageGangmaker' => $resultsCosi[9]->percentage,
    ];
    $fullnamewithout = str_replace(' ', '', $fullname);
    $pdf = PDF::loadView('PDF_COSI', array('data' => $data));
    return $pdf->stream('CoSI_'.$fullnamewithout.'.pdf');

How comes this outcome won't show when I run this via the Nginx server?

**Comment by simonberger** [comment]
You are using the laravel-dompdf package. Please move to https://github.com/barryvdh/laravel-dompdf. But looking at the information you provided I doubt someone can help you there.

**Comment by gdm-1718-onademuy** [comment]
Okay thanks! And what do you mean, which other info should I provide?

**Comment by bsweeney** [comment]
If it works locally but not on remote then it's likely a configuration issue on your host. "Can't load PDF document" is a pretty generic error, so that by itself isn't going to help much. There's probably an error during rendering. Your errors should be logged, so check your PHP logs for additional information you can share.

Also, sometimes error messages are caught in the PDF stream so save the PDF and open in a text editor to see if any non-PDF content, like system notices/warnings/errors appear at the start of the PDF file.
