### ISSUE TITLE
Japanese/Chinese Google Fonts import not working

### ISSUE THREAD

**Issue by ytokarchukova** [dompdf/dompdf#2146]
I am try use `Noto Sans JP` and `Noto Serif JP` from Google Fonts... Importing them via `@import`... 

DomPDF Options:
```
$pdfOptions->setIsHtml5ParserEnabled(true);
$pdfOptions->setIsRemoteEnabled(true);
$pdfOptions->setIsJavascriptEnabled(true);
$pdfOptions->setIsFontSubsettingEnabled(true);
```

`<meta charset="utf-8"/>` already exists. 
`font-family: 'Noto Serif JP', serif !important;` too.

But text display only `??????`. Have any ideas?

**Comment by simonberger** [comment]
This is not enough for us help you. Please add a short html example you can reproduce the problem with. and make sure the browser is also rendering your text in this font and no fallback font.

**Comment by ytokarchukova** [comment]
> This is not enough for us help you. Please add a short html example you can reproduce the problem with. and make sure the browser is also rendering your text in this font and no fallback font.

Example...

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700;900');
    </style>
</head>

<body class="" style="background-color: #fff">
    <h1 style="font-family: 'Noto Sans JP', sans-serif;">こんにちは</h1>
</body>
</html>
```

This code render `?????` only.

**Comment by simonberger** [comment]
Dompdf has no  unicode-range support.

**Comment by bsweeney** [comment]
Looks like Noto Sans is currently not available in truetype format. Or, at least when I tried to load via wget I got an OTF instead of a TTF. You can confirm that by looking at the file saved in your font directory.

I don't know of a way to indicate to Google Fonts that you want a truetype version. Since Dompdf does not currently support anything other than truetype at the moment you'll have to find another source. Follow #932 for updates on that enhancement.

FYI, downloading the font I did get a truetype version. So you could always self-host the font for Dompdf or install via command line.

**Comment by NathanSweet** [comment]
FWIW, I couldn't find Noto Sans in TTF from Google and online OTF to TTF converters produced garbage. However, I searched for `NotoSansJP.ttf`, `NotoSansKR.ttf`, and `NotoSansSC.ttf` and found them on other random websites. Works great!

**Comment by jgrossi** [comment]
@NathanSweet hey can you please share where did you get those ttf fonts on Google? thanks!

**Comment by NathanSweet** [comment]
@jgrossi I'm afraid I don't remember, but you can get them here: http://n4te.com/x/1518-Desktop.zip

**Comment by jgrossi** [comment]
@NathanSweet thanks so much 🙏
