### ISSUE TITLE
the downloaded file is cprrupt 

### ISSUE THREAD

**Issue by shiva-ship** [dompdf/dompdf#2196]

**Comment by bsweeney** [comment]
we'll need more info before we can provide any kind of help

**Comment by NiklasLazinbee** [comment]
I probably had a similar problem. When I tried to open the PDF with Acrobat I got a message:
"This file is damaged and cannot be repaired."

I suppose it's because of the size of the HTML document, with less code it worked. 

Anyway, I found a hint to the ob_end_clean(); function. With this function even larger amounts of code work:

https://stackoverflow.com/questions/20676160/cannot-open-pdf-file-generated-using-dompdf

Specifically it works like this:

`ob_end_clean();`
`$dompdf->stream($pdfName);`
