### ISSUE TITLE
Provide version of package without custom fonts

### ISSUE THREAD

**Issue by UVLabs** [dompdf/dompdf#2198]
Just the fonts alone add 7MB to the Dompdf package. Is there any way to exclude the fonts from being downloaded with composer? I basically just need 1 or 2 fonts. All the rest I wouldn't really need.

I imagine I can delete the fonts I don't want if i download the package manually, but I'm installing it via composer

**Comment by bsweeney** [comment]
We don't have a version of the package without the fonts. In truth Dompdf isn't nearly as useful without since the character set for the core PDF fonts is Windows ANSI.

I did find a [composer configuration on StackOverflow](https://stackoverflow.com/a/58135995/264628) that will delete files after update, though it still requires you to download the files to begin with:

```
"scripts": {
    "post-update-cmd": [
        "rm -rf vendor/aura/intl/tests vendor/cakephp/cakephp/tests"
    ],
}
```

**Comment by UVLabs** [comment]
I ended up just removing the dejavu fonts from the downloaded version of the library instead of using composer

**Comment by bsweeney** [comment]
Those are the core fonts that all PDF readers are supposed to support per the PDF spec. Those fonts only support Windows ANSI, so if you need additional character support they won't be sufficient. Just make sure you kept the AFM files for those fonts so that Dompdf has access to the character metrics.
