### ISSUE TITLE
0.8.6 breaks zero border on table cells

### ISSUE THREAD

**Issue by keksa** [dompdf/dompdf#2228]
There should be no border present.

### 0.8.6
![086](https://user-images.githubusercontent.com/7985651/92379355-9d0a8980-f107-11ea-8960-f3a5c2fa69bc.png)

### 0.8.5
![085](https://user-images.githubusercontent.com/7985651/92379364-a5fb5b00-f107-11ea-9b38-b5ebcf963474.png)

### browser
![browser](https://user-images.githubusercontent.com/7985651/92379375-aa277880-f107-11ea-93cc-c85b99b275e0.png)

### html
(simplified to minimal test case from our regular template)
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style type="text/css">
        table td {
            border: 1px solid #f00;
        }
        
        tbody > tr > td {
            border: 0;
        }
    </style>
</head>
<body>
     <table>
        <tbody>
            <tr>
                <td>lorem</td>
            </tr>
        </tbody>
    </table>
</body>
</html>
```

**Comment by bsweeney** [comment]
Something in the parsing of the unitless value from the border declaration. If you give it a unit (e.g. `0px`) it works as expected.

**Comment by bsweeney** [comment]
The underlying cause here is that when we parse the border properties for the width we look for a number followed by a unit. However, a value of "0" for a length is allowed to exclude the unit ([ref](https://www.w3.org/TR/CSS2/syndata.html#length-units)).

The logic for parsing out the border width hasn't changed significantly between releases, the previous behavior was actually a side effect of poor handling of partial property specification for the generic "border" style declaration. Before the change introduced in 3ad315e, all border properties were reset to their defaults before parsing the CSS value. As a result, in versions prior to 0.8.6 if you used the following style:

```
    <style type="text/css">
        table td {
            border: 1px solid #f00;
        }
        
        tbody > tr > td {
            border: 10px;
        }
    </style>
```

no border would be rendered because the border-style would be reset to none before parsing the width value.
