### ISSUE TITLE
0.8.6 Breaks all local assets on PDFs

### ISSUE THREAD

**Issue by dktcoding** [dompdf/dompdf#2229]
I understand that fixing security bug lilke #2152 it's very important, but I don't think that breaking all of the current user code is the most appropriate way to do it...

Since 0.8.6 all images, assets, fonts that were locally served are now unavailable.

![image](https://user-images.githubusercontent.com/709639/92407502-207ca880-f111-11ea-9d2c-846067d41667.png)

**Comment by bsweeney** [comment]
Is this something you’re unable to address by adjusting the chroot setting? If not do you have a proposed solution?

I’ll add more information to the release notes that this fix may be a breaking change depending on usage.

**Comment by bsweeney** [comment]
I have a few thoughts about how to make this work for everyone:

- add a new resource chroot setting
- allow multiple, delimited values in the setting similar to OS path statements.

**Comment by keksa** [comment]
> Maybe store internally as an array and allow array input to avoid potential confusion in that regard.
@bsweeney Just my two cents. 🙂 The first thought I had when reading this was simply always using an array as `chroot` option value. I don't think any kind of delimiter is really needed. To keep BC, you could simply allow both single path as a string like it's now or an array of paths.

**Comment by timmit-nl** [comment]
I have made an pull request just to make the chroot setting an array. I can make the setChroot so that is accepts string as well array, and explode the string on `,` so it converts to an array....
see:
https://github.com/dompdf/dompdf/issues/2233
and
https://github.com/dompdf/dompdf/pull/2232

**Comment by bravedave** [comment]
I've just come across this issue - thanks that's it's document here, and I've been able to downgrade to 0.8.6
Is there a requirement to set chroot in future ?

am I reading it right that without setting it, the default chroot is somewhere in the vendor folder ?

Thanks

**Comment by enumag** [comment]
@bravedave Default chroot seems to be [dompdf's src directory](https://github.com/dompdf/dompdf/blob/6782abfc090b132134cd6cea0ec6d76f0fce2c56/src/Options.php#L294).

**Comment by bsweeney** [comment]
Yes, if you're using local filesystem resources you should set the chroot value appropriately. Since we can't know the appropriate location of local files we set it the dompdf dir by default.

**Comment by bravedave** [comment]
Ok, cool, so great more secure ..
But this version breaks the https://github.com/dompdf/dompdf/wiki/DOMPDF-and-Composer-Quick-start-guide

So the best practice is .. ?

```
use Dompdf\Dompdf;

//generate some PDFs!
$dompdf = new DOMPDF();  //if you use namespaces you may use new \DOMPDF()

$dompdf->options->setChroot(__DIR__);

$html = 'other stuff... <img src="' . __DIR__ . '/img.png"> ...other stuff ';

$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream("sample.pdf", array("Attachment"=>0));

```

**Comment by christian-graf** [comment]
Hi,

i have the same issue after updating to version 0.8.7.

I could locate the issue (within my implementation) in the Dompdf/Helpers class on line 88.
In my case the function realpath() leads to an error because the designated "asset" has a base_path outside the restricted vhost directories.

The assets which are trying to resolve are "magic" style entries - i think added by the library itself:  url(none);

**Comment by bsweeney** [comment]
@christian-graf can you explain a bit more about the "magic" resource references. Are they, literally, rendered as `url(none)` in your source?

**Comment by Naveen1895** [comment]
@bsweeney @maije I had similar problem. I had set the "enable_remote" as TRUE and changed the "chroot" path to the directory where my file was located. It worked for me.
@bsweeney Is this how you wanted to specify ??

**Comment by maije** [comment]
> $dompdf->options->setChroot(__DIR__);

Hello @bravedave , I would say $options is a private variable, so you would need to call to the setter method which wraps it, something like: 

`$dompdf->set_option('chroot', __DIR__);`

But the images insertion is not working  for me, so I cannot say that's the best way of doing it :-)
Best,

**Comment by Naveen1895** [comment]
@maije I did something like this and it worked for me :- 

        ```
$dompdf = new Dompdf([
            'enable_remote' => true,
            'chroot' => /path/to/file/directory,
        ]);
```

**Comment by bravedave** [comment]
echo this, I thought I searched if this was viable, seems obvious now it is ...

> @maije I did something like this and it worked for me :-
> 
> ```
> $dompdf = new Dompdf([
>             'enable_remote' => true,
>             'chroot' => /path/to/file/directory,
>         ]);
> ```
> 
> @bsweeney let me know if this is the right way to solve this issue.

**Comment by timmit-nl** [comment]
Some mosterd after dinner (a dutch saying for: too little too late). But the 0.8.6 breaks totaly with semver (https://semver.org/). 

and that is normal to use with packagist.org/composer.

Maybe it is a good time to change the current version schema to Semantic Versioning 2.0.0....

**Comment by bsweeney** [comment]
@timmit-nl I don't know that I'd call a security update to an existing release a breaking change. I mean, yes, it broke something but also it's only broken primarily based on usage not because the current version is incompatible with the previous version. And for the most part a tweak of the settings corrects the issue.

But I do see your point. Honestly I'm not too happy with where we are with versioning. We're still sub-1.0 because the project is not feature-complete around standard HTML + CSS 2 functionality. But maybe it's time to move past that and recognize where the project is and where it's going developmentally.

**Comment by bsweeney** [comment]
@timmit-nl and @bravedave yes that's the configuration I would suggest. The next release will also support multi-path chroot for those installations where supporting resources may be in a variety of independent locations on your local filesystem.

**Comment by christian-graf** [comment]
> @christian-graf can you explain a bit more about the "magic" resource references. Are they, literally, rendered as `url(none)` in your source?

@bsweeney If you debug the class i mentioned, then you will find the resource "url(none)" within the rendering process. I called them magic because, there no css definitions with 'url(none)' made by me. So it seemed, this assets are generated by the library itself for some purposes.

**Comment by roberthenniger** [comment]
I was coming across this issue today and think it was a mistake by dompdf devs to include this in a "patch" update. This should have been included earliest 0.9.0 and not in 0.8.6. I wonder how many devs are loosing hours to find the solution to their missing css, font and image assets not getting loaded

**Comment by bsweeney** [comment]
An obvious oversight on my part and I'll try to keep in mind this type of potential problem in the future.

**Comment by danielMonroy96** [comment]
> @maije I did something like this and it worked for me :-
> 
> ```
> $dompdf = new Dompdf([
>             'enable_remote' => true,
>             'chroot' => /path/to/file/directory,
>         ]);
> ```
> 
> @bsweeney let me know if this is the right way to solve this issue.

it worked for me, thanks!!

**Comment by halfpastfouram** [comment]
> ..not because the current version is incompatible with the previous version...

Well, you changed an existing feature that now results in trouble in an otherwise working situation. That's backwards incompatible because our existing code needs changes before it will work again.

I would like to suggest not setting the chroot by default [here](https://github.com/dompdf/dompdf/blob/master/src/Options.php#L294) so users of DOMPDF who did not previously implement this feature will no longer get missing images. And the security fix would still work for those who did implement the chroot setting.

In my opinion the chroot setting should not be active unless explicitly configured.

**Comment by bsweeney** [comment]
@halfpastfouram I'm not comfortable decreasing the default level of security. Past experience has shown that Dompdf can provide a viable path for system infiltration. Perhaps less so in it's current iteration since we removed the dompdf.php script that could be used via the web, but it still seems preferable to maintain a higher level of security by default.

The change is already in place, anyone upgrading to the current release is going to experience the issue. Do you see a benefit disabling it for future releases?

**Comment by halfpastfouram** [comment]
The developers who use this library are themselves responsible for the way they use the library. If that means passing unfiltered user input into dompdf resulting in security issues that is their responsibility. This library provides a way to make such actions more secure by allowing you to set a chroot. I firmly believe this is the right thing to do and allows any developer to lower the risks, but they should still validate input themselves and should _not_ rely on dompdf to protect them.

Now, forcing a chroot for all applications that did not have it enabled results in unannounced bugs that require up to several hours to find out. That's a higher level of security that should not be up to the library to force down the user's throat, because the developer using the library is and should be responsible for validating the input.

Every developer must be able to rely on the integrity of the library. Not everybody uses non-validated user input for dompdf so just removing the risky file and not forcing the chroot would have done the job and would have prevented countless combined hours of time required for all the developers using this library to change their code that would have worked fine otherwise. That would not have changed anything about the level of security.

**As long as the following two criteria are not met I see no benefit in having this situation remain in the next releases:**
1. Chroot must support an array of multiple paths. Otherwise most developers will probably pick the most unsafe option and set the chroot to their project root. That way having the chroot wouldn't even make any sense and should just be optional.
2. The error displayed inside a rendered PDF should clearly indicate what the problem is to avoid confusion and debug time. Right now it just states `Image not found or type unknown`, nothing specific.

**Comment by bsweeney** [comment]
1. The next release will support multiple paths for chroot.
2. Dompdf used to provide more details information regarding why an image does not display. We modified that in the past for, you guessed it, security. Systems that allow user input could be exposed to system identification queries through the use of paths to well known system files.

You can get information regarding why a particular file is not loading through error logging. I realize our current logging scheme is not great, but we can at least update the documentation to bubble that type of information up a bit more.

**Comment by bsweeney** [comment]
Not to say I intended to push out a change that would cause headaches for so many people, but as [noted elsewhere](https://github.com/dompdf/dompdf/issues/2287#issuecomment-743935264):

> on projects below 1.0.0, breaking changes are [allowed on minor versions under semantic versioning](https://semver.org/#spec-item-4)

1.0.0 will include the multiple-path chroot option.
