### ISSUE TITLE
Uncaught Error: Class 'Dompdf\Cpdf'

### ISSUE THREAD

**Issue by bcheco** [dompdf/dompdf#2294]
I tried to update my Dompdf to 0.8.6 and now I am getting the following error Uncaught Error: Class 'Dompdf\Cpdf' not found in [Site directory]/vendor/dompdf/dompdf/src/Adapter/CPDF.php:199, I tried the changes suggested in issue #1173 but this did not work. I also tried to add 
```
require_once 'vendor/dompdf/dompdf/autoload.inc.php';
require 'vendor/dompdf/dompdf/lib/Cpdf.php'; 
```
but both these lines did not change anything. Any thoughts? or should I change my version?

**Comment by bsweeney** [comment]
Are you using the download version or Composer?

**Comment by bcheco** [comment]
@bsweeney I used the download version and now switched to Composer to install but got a different error so I will close this out.

**Comment by bsweeney** [comment]
Thanks for the update. I'll try to find some time to do some testing with the packaged version to see if there's a problem with the autoloader.

**Comment by phpfui** [comment]
Sometimes syntax errors cause the class not to load and PHP reports class not found. If you are on PHP 8.0, this might be the issue, as it is illegal:

~~~php
public_ function __construct($paper = "letter", $orientation = "portrait", Dompdf $dompdf)
~~~

due to the fact that you have default parameters before a non default.  So really all three parameters are required.  I don't see how the defaults were ever used, as $dompdf has to be passed, so you can't default the first two parameters.

The only real solution for this would be to put $dompdf as the first parameter, but not sure what that would break.  This is an issue for the PDFLib and CPDF classes.

**Comment by bsweeney** [comment]
@phpfui we're finalizing an update that will support PHP 8 (#2242).
