### ISSUE TITLE
DOMXPath::query(): Invalid expression on Render

### ISSUE THREAD

**Issue by dpDesignz** [dompdf/dompdf#2309]
I've just started using dompdf (ex MPDF user) and it all worked in my dev environment, but as soon as I put it on my server it's randomly giving me the following error:

```
Type: ErrorException;
Message: DOMXPath::query(): Invalid expression;
File: /public_html/system/storage/vendor/dompdf/dompdf/src/Css/Stylesheet.php;
Line: 1034;
```

The [line of this file](https://github.com/dompdf/dompdf/blob/8d8a529500a2e5e01152c9b99488adb815d568cb/src/Css/Stylesheet.php#L1034) is 

```php
$nodes = @$xp->query($query["query"]);
```

There is a [similar issue from 2014](https://github.com/dompdf/dompdf/issues/764) and I tried debugging using the code in the first post, but it didn't work.

I have all the required libraries, and I'm running PHP 7.4.12 with version 0.8.6 of dompdf.

The odd thing is if I use [filp/whoops](https://github.com/filp/whoops) I don't get any errors showing, but if I don't the error above comes up.

I couldn't find out in the dompdf documentation how to debug, so any help would be much appreciated :)

The code that I'm putting in to render is available to view [on my gist here](https://gist.github.com/dpDesignz/d7532d244fb5ad0f75f47d49e1ddd900), and my code I'm using to render it is as follows

```php

Options = new Options();
$dompdfOptions->set('isRemoteEnabled', TRUE);
$dompdf = new Dompdf($dompdfOptions);
$context = stream_context_create([
  'ssl' => [
    'verify_peer' => FALSE,
    'verify_peer_name' => FALSE,
    'allow_self_signed' => TRUE
  ]
]);
$dompdf->setHttpContext($context);
$dompdf->loadHtml($compiledContent);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('po-000013', array('Attachment' => 0));

**Comment by bsweeney** [comment]
The cause of the error being raised is because Dompdf is producing an invalid XPath while parsing the stylesheet. We prefix the XPath query with `@` error control handler so that Dompdf can continue past these types of errors. More than likely your normal error handler is still raising errors even when error reporting is 0 (which is how  the `@` suppresses errors). filp/whoops, on the other hand, must be honoring the error reporting level.

The underlying issue, however, appears to be a problem parsing the Google Font URL. I found if you remove the semi-colon from the Google Font stylesheet reference Dompdf does not run into any parsing errors.

So, instead of this:

```
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap');
```

use this:

```
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@600&display=swap");
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap");
```

Not as efficient, but produces the same results as far as I can tell. I don't think we'll address the parsing issue for the next release, but definitely look into it for the following release.

**Comment by dpDesignz** [comment]
@bsweeney thank you so much for that! I would never have even thought to check those links. Much appreciated 😄

**Comment by bsweeney** [comment]
Hey, all I did was throw all the queries in the log file until the bad one hit me in the face 😅. Just glad I was able to figure out the cause.

**Comment by dpDesignz** [comment]
@bsweeney much appreciated anyway. I'll remember that for next time!

Do you have a SO account? If so, do you want to also answer my original post there for points? If not, I'll post the answer myself 😄 

https://stackoverflow.com/questions/64641093/domxpathquery-invalid-expression-on-render

**Comment by bsweeney** [comment]
I do have an SO account. I'll post an answer over there as well. Thanks for the pointer.
