### ISSUE TITLE
CSS border is not working anymore in version 1.0.0

### ISSUE THREAD

**Issue by sorelio** [dompdf/dompdf#2331]
Hi, 
I have just upgraded to version 1.0.0, but even simple css like border: `1px solid black;`. You can reproduce this with simple `<div style="height: 50px; width: 50px; border: 1px solid black;">Broken border</div>`

Dompdf is installed using composer (exact version e53da1ccea4340832d0b864e383c4e2b2d141ca3)

**Comment by bsweeney** [comment]
Hmmm ... not sure how that got by us. Will try to get a new release out with a fix soon.

**Comment by dvdchn** [comment]
tried border-bottom. It doesn't work too.

**Comment by bsweeney** [comment]
It's and issue with how the property is being set. If there's no initial style then the computed value of the property becomes zero. Because the style class is attempting to shortcut the logic to set the value for that style property the border width isn't being recalculated when a new value is set.

If you move the style value to the front (e.g. `border: solid 1px black;`) the border is set as expected. I have a fix ready, so should be able to push out an update this week. Just want to review it with fresh eyes before I push it up.

**Comment by neonella** [comment]
I found that changes that cause issues with borders also cause issues with rendering font size for <sup> tag.

Temp fix:
File: dompdf\vendor\dompdf\dompdf\src\Css\Style.php

Replaced this:

```
if (isset($style->_props_computed[$prop])) {
    $this->__set($prop, $style->_props_computed[$prop]);
} else {
    // computed value not set, recompute use the specified value
    $this->__set($prop, $val);
}
```
with this:

`$this->__set($prop, $val);`

Wondering if it can be a permanent solution for future versions or there is a good reason to use existing values instead of precomputing them.

**Comment by bsweeney** [comment]
@neonella that's a different issue, can you post a new issue with an example?
