### ISSUE TITLE
Inline element with letter spacing results in exra space before the element

### ISSUE THREAD

**Issue by Mellthas** [dompdf/dompdf#2404]
This is the same HTML as in issue #2403:
```
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>Test</title>

<style type="text/css">
body {
	font-family: sans-serif;
	font-size: 1em;
	letter-spacing: 5pt;
}

p {
	margin: 0;
}
</style>

</head>

<body>
	<p>Lorem ipsum <b>dolor</b> sit amet, consectetur adipisici elit.</p>
</body>

</html>
```

See the attached output; there is extra space before the word _dolor._ If the text has standard letter spacing, the issue does not show up, and it seems to get worse with larger letter spacing:
[output.pdf](https://github.com/dompdf/dompdf/files/6109861/output.pdf)

**Comment by bsweeney** [comment]
Looking at the extra space between ipsum and dolor, I _think_ what may be happening here is that the letter spacing is applied to the space character (the end of the first chunk), then taken into account when specifying the position of the second chunk, since it's an inline element. So just a guess but retrieving the width of that first chunk must include the letter spacing and we must be applying it again when determining the position of the next chunk, even though it was already applied.

**Comment by Mellthas** [comment]
Phew! Went to the bottom of this. The problem is an error in the text-width calculation of the CPDF back end. Because the text width was reported incorrectly, inline elements would be positioned too far to the right. Pure text wouldn't really make this visible unless backgrounds or borders came into play and the text would span the entire width of the content box. See #2414.
