### ISSUE TITLE
All iamges showing but Some Images not showing properly why?

### ISSUE THREAD

**Issue by DeveloperGulam** [dompdf/dompdf#2471]
I

**Comment by 4DallasC** [comment]
Howdy @bsweeney

I was using version <6782abfc> and everything was working fine. It was loading the png image from the local hard drive with the full file path name. I upgrade to version 1.0.2 and now I getting the error:- Image not found or type unknown.

<img width="100%" height="auto" src="/var/www/test.mydomain.com.au/source/pub/media/sales/store/logo/default/logo-pdf.png" alt="Alt Text"/>

**Comment by 4DallasC** [comment]
Just confirming the issue, updating my composer.json file to:- 
```
  "require": {
        "dompdf/dompdf": "0.8.5"
    },
```
resolved this issue. So there's definitely a bug in the release v0.8.6 and above.

**Comment by bsweeney** [comment]
The issue is likely due to a change to require local resources fall under the directory(ies) specified for the chroot option (#2232). This was done to prevent potential information disclosure in shared environments. Try specifying your chroot when setting up Dompdf.

Something like:

```
$dompdf = new Dompdf(['chroot' => '/var/www/test.mydomain.com/au'])
```

**Comment by 4DallasC** [comment]
Howdy Brian,

I tried and still no luck. Although the error message was gone.

After stepping through the code, the issue is in \Dompdf\FrameReflower\Image::get_size(Frame $f, string $type). The issue is that it $f->get_style()->$type returns 'autopx' when the value for height is 'auto'. If I hardcode if($current_size == 'autopx') $current_size = 'auto', it all works again.

**Comment by bsweeney** [comment]
Ah yes, sorry. I missed that in your HTML sample. You're using non-standard units in your height/width attributes. You can follow #2240 for updates on resolution of the issue.
