### ISSUE TITLE
<style></style> seems to be ignored (at least for images size)

### ISSUE THREAD

**Issue by Sartoric** [dompdf/dompdf#2492]
I have an html (that's ok) with css defined in head <style> block
When rendered, the pdf seems to ignore the image sizes width (at least)

If I set width inline (both via style='' or width='' ) it works as expected

Any one has any ideas or can link some existing issues ? 
I've seen some issue related to css but not really this one and somewhere I read that someone is using <style> without any problem

Thank you

**Comment by bsweeney** [comment]
What version of Dompdf? Do you have a sample? When I use the following it seems fine:

```
<style>
.w300 { width: 300px; height: 300px; }
</style>
<img src="http://placekitten.com/500/750" class="w300" />
```

(purpose distorted to show that the style height is respected)

**Comment by Sartoric** [comment]
> What version of Dompdf? Do you have a sample? When I use the following it seems fine:

Yep, in fact it works. 
I've missed in the html (as it is a single line string) a `@media print {}` so in fact it wasn't rendered.

The question is, shouldn't "print" css section be taken in consideration anyway ? 
Most of the time the pdf is generated to be printed too (if not only)
Maybe I'm missing some dompdf option ?

**Comment by bsweeney** [comment]
"print" media selector isn't used by default. The [standard Dompdf media types](https://github.com/dompdf/dompdf/blob/v1.0.2/src/Css/Stylesheet.php#L155) are:
* all
* static
* visual
* bitmap
* paged
* dompdf

ignore the `$ACCEPTED_DEFAULT_MEDIA_TYPE` variable there looks like we're not actually using it right now.

Additionally, the styles targeted to the media type specified by the [`defaultMediaType` option](https://github.com/dompdf/dompdf/blob/v1.0.2/src/Options.php#L70-L82) is also included. That defaults to "screen" which has been the default since that setting was introduced in 0.6.0. If you want to utilize the print styles you would just need to set that option, for example:

```
$dompdf = new Dompdf(['defaultMediaType' => 'print']);
```

**Comment by Sartoric** [comment]
@bsweeney 
Thanks

Using this option is surely better than modifying the html source.

Since I'm not 100% sure I'll always get a @media print (so it could be screen too) do you think is viable to do something like this ? 
Stylesheet::$ACCEPTED_GENERIC_MEDIA_TYPES[]='print';
Or I could face some "issue" ?

**Comment by bsweeney** [comment]
There should be no harm in doing it that way. I'll also have to consider the use case of allowing the user to specify multiple media types in the configuration option ... though that is a bit of an edge case.

**Comment by Sartoric** [comment]
Thanks
Well, you're right this is an edge case :D 
In fact I didn't expect to receive a css @media enclosure for an html that should be just printed.
