### ISSUE TITLE
Compatibility Issues (?) With Symfony's MBString Polyfill On PHP 8.

### ISSUE THREAD

**Issue by GenieTim** [dompdf/dompdf#2493]
Hi and thank you for this library.

In PHP 8.0, on a server without mbstring extension, I get the following stack trace/error:

```json
{
    "class": "ValueError",
    "message": "Argument #1 ($substitute_character) must be \"none\", \"long\", \"entity\" or a valid codepoint",
    "code": 0,
    "file": "/var/www/vendor/symfony/polyfill-mbstring/Mbstring.php:605",
    "trace": [
        "/var/www/vendor/symfony/polyfill-mbstring/bootstrap80.php:69",
        "/var/www/vendor/dompdf/dompdf/src/FontMetrics.php:193",
        "/var/www/vendor/dompdf/dompdf/src/Css/Stylesheet.php:1553",
        "/var/www/vendor/dompdf/dompdf/src/Css/Stylesheet.php:1403",
        "/var/www/vendor/dompdf/dompdf/src/Css/Stylesheet.php:332",
        "/var/www/vendor/dompdf/dompdf/src/Dompdf.php:682",
        "/var/www/vendor/dompdf/dompdf/src/Dompdf.php:761",
```

The relevant code line is `mb_substitute_character(0x005F);`, meaning it lies outside the scope of user/developer input.
Looking at Symfony's polyfill, it is clear that any input other than `null` or `"none"` throws this error on PHP >= 8. 
Interestingly, using `mb_substitute_character(95);` instead works perfectly, meaning, I am missing something somewhere in my understanding. Any idea why the latter could work? And where to resolve this?

**Comment by bsweeney** [comment]
It looks to me like the [Symfony implementation of mb_substitute_character](https://github.com/symfony/polyfill-mbstring/blob/v1.23.0/Mbstring.php#L593-L606) in the polyfill is incomplete and appears to be incompatible with the PHP method. Really it does nothing useful so throwing an exception seems excessive since returning false would seem the best fallback behavior. Addressing the issues in that particular method would seem to be straightforward. Something along the lines of:

```php
private static $substituteCharacter = 63;
public static function mb_substitute_character($c = null)
{
    static $keywords = array('none','long','entity');

    if (null === $c) {
        return self::$substituteCharacter;
    }

    $lc = strtolower($c);
    if (in_array($lc, $keywords, true)) {
        self::$substituteCharacter = $lc;
        return true;
    }

    if (is_numeric($c) && $c >= 0x0000 && $c <= 0x10FFFF) {
        self::$substituteCharacter = $c;
        return true;
    }

    if (80000 > \PHP_VERSION_ID) {
        if (empty($c)) {
            self::$substituteCharacter = '';
            return true;
        }
      
      return false;
    }
    throw new \ValueError('Argument #1 ($substitute_character) must be "none", "long", "entity" or a valid codepoint');
}
```

The above isn't really thought through too much, but feel free to take that and submit a pull request to the project. Also, while that version addresses the base compatibility of this particular method additional changes would still have to be made. The polyfill doesn't utilize the substitution character.

Finally, MBString is listed as a requirement in the [documentation](https://github.com/dompdf/dompdf#requirements) and for [Composer](https://github.com/dompdf/dompdf/blob/v1.0.2/composer.json).

It's, perhaps, possible to do the type of string parsing we need to do without the extension, though I don't know that we'll make any changes related to that anytime soon.
