### ISSUE TITLE
Stylesheet parser does not honor media type in media query

### ISSUE THREAD

**Issue by AxelJarni** [dompdf/dompdf#2539]
Hi, I'm using dompdf to print a PHP page of a big Table with Data inserted from MongoDB.

First I had an issue about dompdf not using my CSS file and printing the table without any border and style.
Tried a lot of things but for now the only solution working is to put my CSS directly into my HTML code between <style> tags.
I would prefer to import my CSS file with a ```<link rel="stylesheet">``` for the sake of clean code but also have it loaded by dompdf when I print it, so if anyone have the solution about that, I'm interested.

My **main problem** right now is that:
Since the size of the Table is quite important I use a different style (block of lines) for my Table and activate it with a **Media Query** of a 1024px max-width.
The problem is that when I print my PDF, **I always get the style of the Media Query version**, even if I'm printing from a Desktop width (and realistically in the end I would need to always print the desktop version of the PDF even if I'm using the Mobile one).
[Here is a JSFiddle of my HTML and CSS code](https://jsfiddle.net/jkptb415/1/) so you can see of my Table style changes and what I used to code it.

And here is how I call for dompdf to print
```php
<?php
require 'vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;
 //My MongoDB query

ob_start();
?>

// My html code you can see in Fiddle (link above)

<?php
if(isset($_POST["pdf"])){
    $html = ob_get_contents();
    ob_end_clean();
    $dompdf = new DOMPDF();
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'landscape');
    $dompdf->render();
    $filename= "filename". date('d-m-Y') . ".pdf";
    $dompdf->stream($filename ,array('Attachment'=>1));
}
?>
```

Also not sure if it's important since I really want the Desktop version but even though it's only printing the mobile version it is **missprinting it**. Some lines label are not showing. And if a line doesn't have Data in it, it is not printing it.
[Here what the Mobile version really looks like](https://i.imgur.com/OpBNQIH.png) 
[And here is what is printed by dompdf](https://i.imgur.com/p7RWOil.png)

**Comment by bsweeney** [comment]
Dimensions for a4 are 595pt x 842pt. So in landscape mode that means you have 842pt max width. The evaluation of your media query is dependent on your DPI setting. PDFs use a fixed scale of 72pt/in. If your Dompdf DPI is 72 then document is rendered at 1px = 1pt. At that DPI the document is < 1024px and so will render in mobile view.

There are two ways to address your issue:

1. Increase the Dompdf DPI so that the PX to PT translation meets your needs. To get the dimensions of the document above your media query width you would need to figure out the ratio so you can set the appropriate DPI. I haven't done the math, but if you try 150 you get the expected render. Also note that changing the DPI impacts any lengths in units that are virtual (such as PX). There are a few ways you can set the DPI, but this is the easiest:

```
$dompdf = new DOMPDF(['dpi' => 150]);
```

2. Use the type query, e.g. `@meda (not dompdf) and (max-width: 1024px) { ... }`. Unfortunately it looks like this doesn't quite work the way it's supposed to. So to take advantage of this you would have to use an external stylesheet to host the mobile styles and target the right media type:

```
$dompdf = new DOMPDF(['defaultMediaType' => 'print']);
```

and in your HTML you would use CSS `@import` or a LINK element to target screen for the mobile styles:

```
<style>
@import url(mobile.css) screen;
</style>
```

**Comment by bsweeney** [comment]
Ideally you could address this more simply by using the following media query when Dompdf's default media type is print:

```
<style>
@media screen and (max-width: 1024px) { ... }
</style>
```

It's not your original issue but since you led me to a potential bug I'm going to address in relation to this ticket.

**Comment by AxelJarni** [comment]
> 
> Dimensions for a4 are 595pt x 842pt. So in landscape mode that means you have 842pt max width. The evaluation of your media query is dependent on your DPI setting. PDFs use a fixed scale of 72pt/in. If your Dompdf DPI is 72 then document is rendered at 1px = 1pt. At that DPI the document is < 1024px and so will render in mobile view.
> 

Thank you for helping me understand how dompdf page dimensions were working and helping me understand what was causing a problem for me.
Indeed, setting the DPI to 150 helped me get my style working as I wanted.
