### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [dompdf/dompdf#2564]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by bsweeney** [comment]
You can email security@dompdf.org with details of the issue.

**Comment by bsweeney** [comment]
Still validating the issue, but it looks like backwards-incompatible changes will be required. Will prioritize any work related to this issue for the 2.0.0 release. We'll re-shuffle milestones to prioritize that work.

**Comment by bsweeney** [comment]
this references something not addressed in 1.2.1

**Comment by greggles** [comment]
Is there a CVE for this?

**Comment by bsweeney** [comment]
There were four vulnerabilities discovered as part of this review, three of which have a CVE. Only one of the CVEs is published at this time, but details are available through [huntr.dev](https://huntr.dev/repos/dompdf/dompdf/) (through which the issues were reported).

---

Thanks for the reminder. I plan to update this ticket and other resources as the CVEs are published.

**Comment by greggles** [comment]
Thanks for the quick response. If an integration only uses the APIs that stayed the same is it safe to say that it is not vulnerable to the security issues fixed in this issue?

**Comment by greggles** [comment]
I'm asking because of the Drupal contributed project which relies on this library. We're trying to see if it is vulnerable to this issue (or any other vulnerabilities in the way it's implemented) or if we could update the dependency and not treat it as a security release.

In upgrading, the maintainers found that none of the APIs used by the module required changed, so I thought maybe that could help us determine if the module is vulnerable to this issue.

**Comment by bsweeney** [comment]
The API itself didn't change because the underlying functionality was modified to protect against the vulnerabilities. So I'd say that in most usage scenarios a system utilizing a previous release would be vulnerable. For example, can users upload files and reference them in the HTML used to generate a PDF document? Then that is definitely a risk for exploitation. The vulnerabilities are there, but determining the level of risk would be an exercise for the end user.

All the vulnerabilities require some kind of integration to expose. If you're writing your own HTML on your own system, using your own content, and generating a PDF using Dompdf then you're (probably) safe? What I mean is that you can't just load Dompdf core files via the web and exploit a system. But that's not really saying much since the primary use case for the library is within other systems.

I don't know what factors are involved in trying to determine whether to treat this as a security release for the Drupal module. However, from my perspective using an earlier Dompdf release is an exposure risk and I would advise all users to upgrade.

**Comment by greggles** [comment]
That's a super helpful explanation, @bsweeney. Thanks for taking the time to lay out the details like that.

**Comment by bsweeney** [comment]
Updated with summary information on the reported vulnerabilities as well as links to further information.
