### ISSUE TITLE
A non-numeric value encountered Style.php on line 1330

### ISSUE THREAD

**Issue by airplanenoise** [dompdf/dompdf#2660]
hi there - 

using the dompdf that's included in https://github.com/anttiviljami/wp-pdf-templates - I know it's a fairly unfollowed package. 
i have been trying to figure out if the issue I am running into is server related, wp-pdf-templates related or dompdf related... at this point the error I get is this: 

`A non-numeric value encountered in /var/www/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/Css/Style.php on line 1330` 

and it returns a totally blank PDF. the same exact code works just fine on a less restrictive host. i am starting to wonder if this is /tmp access issue --- but at this particular time the only error I get is the one above. 

thanks for any insights. you can see a lot more about my particular issue here: https://github.com/anttiviljami/wp-pdf-templates/issues/36 (I have been in touch with that author as well)

thanks!

**Comment by bsweeney** [comment]
Math operations are checked for non-numeric values starting with PHP 7.1. We have addressed the known instances of this particular type of issue. Since wp-pdf-templates specifies dev-develop as the preferred version I can't say which release of Dompdf you're working with. It doesn't look like the latest based on the line number so I'd try running `composer update` to get the current version.

FYI, we're not maintaining the develop branch moving forward. It's only slightly behind at this point but you'll need to alias updated releases (or dev-master) to continue receiving Dompdf updates. In your own composer.json add something like the following (completely untested) configuration option:

```
"require": {
    "dompdf/dompdf": "dev-master as dev-develop"
}
```

**Comment by airplanenoise** [comment]
thanks for that. i did what you said and added some try/catches to see what's going on. 

i was able to troubleshoot further. this is the error i get now: 

```
Stack trace:
#0 /var/www/wp-content/plugins/mfo-wp-pdf-templates/vendor/dompdf/dompdf/src/Dompdf.php(760): Dompdf\Dompdf->processHtml()
#1 /var/www/wp-content/plugins/mfo-wp-pdf-templates/wp-pdf-templates.php(404): Dompdf\Dompdf->render()
#2 /var/www/wp-content/plugins/mfo-wp-pdf-templates/wp-pdf-templates.php(263): _print_pdf('<html>\n<head>\n\t...')
#3 /var/www/wp-includes/class-wp-hook.php(303): _use_pdf_template('')
#4 /var/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /var/www/wp-includes/template-loader.php(13): do_action('template_redire...')
#7 /var/www/wp-blog-header.php(19): require_once('/var/www/wp-inc...')
#8 /var/www/index.php(17): require('/var/www/wp-blo...')
#9 {main}
  thrown in /var/www/wp-content/plugins/mfo-wp-pdf-templates/vendor/dompdf/dompdf/src/Dompdf.php on line 596

```

does that make sense to you?

**Comment by bsweeney** [comment]
What's the actual error generated for that stack trace? Is it the same? If so seeing the actual HTML+CSS would help determine if this is a new issue.
