### ISSUE TITLE
Suggestion: Display error message in the PDF if loading a font file with `@font-face` fails

### ISSUE THREAD

**Issue by ThomasLandauer** [dompdf/dompdf#2671]
When loading an image fails, you're getting a gray cross with this error message:

> Image not found or type unknown

When loading a font file via `@font-face` fails, you're not getting any error message; the text is just rendered in a fallback font. Would it be possible to display an error message in this case too?

About the error message itself: It would be nice if dompdf could include the file path in the message, e.g.

> Image not found at '/assets/foo.jpg'  or type unknown

This would help discovering the problem at https://github.com/dompdf/dompdf/issues/1567#issuecomment-489330871 - which I keep forgetting each time I create a new PDF ;-)

**Comment by bsweeney** [comment]
There was a security-related reason we limited the error message for the image though at the moment I can't pull that reason off the top of my head.

I think ideally we would go ahead and implement a better logging mechanism (#960) so that this type of information could be collected in a more sane manner.

**Comment by ThomasLandauer** [comment]
Yeah, even better, so I'm closing this.
