### ISSUE TITLE
Why `set_http_context` is not available from `Options()`

### ISSUE THREAD

**Issue by PaolaRuby** [dompdf/dompdf#2682]
Why is not available `set_http_context` on [Dompdf\Options](https://github.com/dompdf/dompdf/blob/master/src/Options.php)?
https://github.com/dompdf/dompdf/blob/61c86c04d2a483187ff9f6a73c50d42669be5b4d/src/Dompdf.php#L1252-L1255

**Comment by bsweeney** [comment]
The current Options class was built from the original dompdf_config.inc.php file, back when that was used to bootstrap Dompdf. When that HTTP context option was made available it was set as part of the Dompdf class instead of a configuration option for ... reasons? I'm not sure, actually. There are probably a few properties that could be appropriately moved to the Options class.

**Comment by fredsal** [comment]
It seems like a small and easy change.

**Comment by PaolaRuby** [comment]
@Mellthas is there a way to having this?
