### ISSUE TITLE
Can't set Content-Type for response

### ISSUE THREAD

**Issue by LocalHeroPro** [dompdf/dompdf#2739]
I thing default content type have to be: **application/pdf** and I think this have to be default option.
```php
$dompdf->stream();
```
Right now net tools telling me, I'm receiving in the response **Content-Type: text/html; charset=UTF-8**.
I try to change it in that way:
```php
$dompdf->stream(options: ['Content-Type' => 'application/pdf']);
```
but without required results on the end
![image](https://user-images.githubusercontent.com/42643563/149636898-c7dcdc38-cbd0-4714-9cc7-a5da23079365.png)

**Comment by bsweeney** [comment]
When you call `$dompdf->stream();` the correct content type is set. You might have something in between dompdf and your web server that's intercepting the content and modifying the output. For example, if you're using a PHP framework of some sort it may be using output buffering to capture content so that some operation can be performed prior to sending to the browser.

Suggest you try calling `exit;` immediately after you stream the PDF and see if that helps.

If you are using a framework and don't want to short circuit it's processes there's probably a way to tell it what type of content you're returning.
