### ISSUE TITLE
Not rendering css backgorund-image / position absolute divs

### ISSUE THREAD

**Issue by marmz** [dompdf/dompdf#2833]
As in subject , i am not able to render `div` with `background-image` css property, and/or `position:absolute` elements.

I just created git repo to show the exact case:
https://github.com/marmz/dompdf-test

File `chart.html` is well rendered in browser.
But if you run `index.php`, result is a blank pdf page.

Thanks in advance.

**Comment by marmz** [comment]
Update:
I just inserted the css code right inside the <style> tag, insteak of linking it as stylesheet file.

**Comment by bsweeney** [comment]
Since you're using `loadHtml` and the resource references aren't via HTTP you'll need to tell Dompdf that it's [OK to access resources](https://github.com/dompdf/dompdf/wiki/Usage#referencing-resources-like-images) from within the directories where resources may be located. You do this using the chroot option.

For this particular sample something like the following would work:

```
$options->setChroot([__DIR__]);
```
