### ISSUE TITLE
Way to prevent line break between regular text and superscript?

### ISSUE THREAD

**Issue by ameriel** [dompdf/dompdf#2845]
Hi, we have a document where a subscript character "attached" to regular text is being broken to a new line. In the web browsers I've checked it seem like there is some mechanism that prevents this from happening. Here is the HTML I am testing: [test.txt](https://github.com/dompdf/dompdf/files/8420492/test.txt) and you can see the behavior in the Debug Helper: https://eclecticgeek.com/dompdf/debug.php?identifier=a098cf8732872766001a52f3b06fc5c7 (see difference in the table's third column header between the "PDF" and "Source HTML" tabs).

I have tried using both "`<nobr />`" and the "zero-width-no-break-space character" (`&#65279;`) but it doesn't look like either of those are supported. However, wrapping with `<span style="white-space: nowrap;">` does fix the issue - so we have a workaround for this case but it's not something we want to make our non-technical end users do going forward.

This might be the same issue as this one: https://github.com/dompdf/dompdf/issues/879 If so, apologies but honestly I don't know enough to tell.

**Comment by bsweeney** [comment]
Which version of Dompdf are you using locally? I tried nobr and 65279 (with DejaVu sans) with 1.2.1 and both have the desired effect, though the output is slightly different.

I think your issue is related to 879, though that one is lacking detail that would make it easier for you to confirm without input. I'm going to close it in favor of #1036 which makes the issue a bit more obvious.
