### ISSUE TITLE
How to increase watermark transparency

### ISSUE THREAD

**Issue by Ademgenc53** [dompdf/dompdf#2898]
Hello,

How to increase watermark transparency
`$canvas->set_opacity(0.1,'Multiply');`
Is it possible to lower this value further?

Thank you

**Comment by bsweeney** [comment]
Have you tried a lower value, such as 0.01?

**Comment by Ademgenc53** [comment]
Thank you, yes it worked,

I am using the below code for page number, page bottom logo and watermark
https://www.codesenior.com/en/tutorial/Dompdf--Create-Watermark-and-Page-Numbers

I want to use separate transparency for page number
I want to use separate transparency for page bottom logo
I want to use separate transparency for watermark
Is it possible to give them transparency separately?

The transparency setting on line 22 for the page number
The page bottom is the code setting on line 25 for the logo, but the watermark is setting transparency in the text
Wouldn't it be possible to set the transparency for the bottom logo and the watermark text separately?

**Comment by bsweeney** [comment]
You're setting the watermark using the `page_text` method. This method doesn't actually write anything to the PDF. It stores the parameters you provided so that Dompdf can write the text to each page as the document is being output. Since the opacity setting is a separate operation, it isn't stored with the text command. As a result, the `page_text`-generated text would inherit the last set opacity, or `$pdf->set_opacity(0.2,"Multiply");` from the `page_script` executed immediately before it.

You'll want to set your text via `page_script` (and use the `text` method instead of `page_text` method) so that you have more control over the text appearance.

---

One last note. Your code includes the following comment next to one of the `set_opacity` lines:
> Multiply means apply to all pages.

To clarify, "multiply" in this scenario indicates the [blend mode](https://helpx.adobe.com/illustrator/using/transparency-blending-modes.html):
> Multiply: Multiplies the base color by the blend color. The resulting color is always a darker color. Multiplying any color with black produces black. Multiplying any color with white leaves the color unchanged. The effect is similar to drawing on the page with multiple magic markers.
