### ISSUE TITLE
subtotal on each page

### ISSUE THREAD

**Issue by Dasinfomedia2** [dompdf/dompdf#2936]
I am printing credit notes and want to show a total of each item on each page above the footer right aligned.
But not able to achieve this with dompdf, how to do it with dompdf?

**Comment by bsweeney** [comment]
What have you tried so far? Sounds like you could probably use an absolutely positioned element to position the content above the footer. Within the positioned element you can right-align.

**Comment by Dasinfomedia2** [comment]
<script type="text/php">
        if (isset($pdf)) {
            $x = 250;
            $y = 10;
            $text = "Subtotal : {$subTotal}";
            $font = null;
            $size = 14;
            $color = array(255,0,0);
            $word_space = 0.0;  //  default
            $char_space = 0.0;  //  default
            $angle = 0.0;   //  default
            $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
        }
    </script>

I am trying with php scripti. but the thing is how do I get the amount items counts in each page?

**Comment by bsweeney** [comment]
Embedded scripts are parsed by Dompdf during PDF rendering after the HTML has been generated by PHP. This means that the variables defined during PHP generation aren't available to the embedded script because they're no longer in scope. If you want to generate this particular content in this way you would need to push the variable into the `$GLOBALS` array and access it from there in your embedded script.

Generally we recommend not using embedded script where possible. Is `$subTotal` available when the document loads or is it tallied as you go? If it's available right away you can replace this with a fixed-position element at the top of the HTML document.

**Comment by Mellthas** [comment]
You should be able count elements per page using callback events, something like:

```php
$count = 0;
$dompdf->setCallbacks([
    [
        "event" => "begin_frame",
        "f" => function (AbstractFrameDecorator $frame) use (&$count) {
            if ($frame->get_node()->nodeName === "li" && !$frame->is_split_off) {
                $count++;
            }
        }
    ],
    [
        "event" => "end_page_render",
        "f" => function ($frame, Canvas $canvas, FontMetrics $fontMetrics) use (&$count) {
            $text = "Number of items so far: $count";
            $font = $fontMetrics->getFont("Helvetica");
            $size = 12;
            $fontHeight = $fontMetrics->getFontHeight($font, $size);
            $x = 20;
            $y = $canvas->get_height() - $fontHeight - 20;
            $canvas->text($x, $y, $text, $font, $size);
        }
    ]
]);
```
Counting the number of `li` elements here for demonstration purposes. Checking `$frame->is_split_off` to account for cases where the element is split into multiple frames due to a page break, e.g. if it contains multiple lines of text.

**Comment by Dasinfomedia2** [comment]
> Embedded scripts are parsed by Dompdf during PDF rendering after the HTML has been generated by PHP. This means that the variables defined during PHP generation aren't available to the embedded script because they're no longer in scope. If you want to generate this particular content in this way you would need to push the variable into the `$GLOBALS` array and access it from there in your embedded script.
> 
> Generally we recommend not using embedded script where possible. Is `$subTotal` available when the document loads or is it tallied as you go? If it's available right away you can replace this with a fixed-position element at the top of the HTML document.

It is tailed as you go.

**Comment by Dasinfomedia2** [comment]
> ```
> $frame->get_node()->nodeName === "li"
> ```

This is looks good. but it will not get amount which is printed in `<td>` tag, right?

**Comment by bsweeney** [comment]
I think adding a data attribute is a nice way to handle this. Dompdf doesn't do any kind of pre-paging, the page total isn't determined until the full document is rendered. Instead of using the end_page_render callback you could render your document then use the canvas page_script method to write out the subtotal to each page (except the last).

Since you're not writing the subtotal as the document is rendered you'll need to persist the page subtotals in an array so you can access later.

Something like the following:

```
$currentPage = 0;
$subtotal = [0 => 0];
$dompdf->setCallbacks([
    [
        "event" => "begin_page_render",
        "f" => function (AbstractFrameDecorator $frame) use (&$subtotal, &$currentPage) {
            $currentPage++;
            $subtotal[$currentPage] = $subtotal[$currentPage-1];
        }
    ],
    [
        "event" => "begin_frame",
        "f" => function (AbstractFrameDecorator $frame) use (&$subtotal, &$currentPage) {
            if ($frame->get_node()->nodeName === "span" && !$frame->is_split_off) {
                $subtotal[$currentPage] += floatval($frame->get_node()->getAttribute("data-amount"));
            }
        }
    ]
]);
$dompdf->render();
$dompdf->getCanvas()->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) use (&$subtotal) {
    if ($pageNumber === $pageCount) {
        return;
    }
    $text = "Subtotal: " . $subtotal[$pageNumber];
    $font = $fontMetrics->getFont("Helvetica");
    $size = 12;
    $fontHeight = $fontMetrics->getFontHeight($font, $size);
    $x = 20;
    $y = $canvas->get_height() - $fontHeight - 20;
    $canvas->text($x, $y, $text, $font, $size);
});
```

**Comment by Dasinfomedia2** [comment]
This is working.
can I append subtotal in a new `td` within `tr`?

**Comment by bsweeney** [comment]
>  can I append subtotal in a new td within tr?

It _may_ be possible to insert elements in that the methods Dompdf uses are mostly accessible. But actually doing it is ... challenging. There's a lot that Dompdf has done up to this point to process and organize the document internally and trying to insert a new element can break in spectacular ways.

In an ideal scenario this could be achieved entirely using HTML + CSS through a tfoot element with generated content and conditional visibility based on the page. So while you could tally the subtotal using counters, there is currently no support for correct tfoot handling (#25) nor for page-conditional styling (#1572).

So for now, I think the method we've outlined is your best (and only?) option.

---

Just for reference here's how you tally a subtotal using counters:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    .subtotal:before { content: counter(subtotal); }
  </style>
</head>
<body>
  <div id="wrapper">
    <div style="counter-increment: subtotal 600">600</div>
    <div style="counter-increment: subtotal 300">300</div>
    <div style="counter-increment: subtotal 50">50</div>
    <div style="counter-increment: subtotal 1000">1000</div>
    <div>Subtotal: <span class="subtotal"></span></div>
  </div>
</body>
</html>
```
