### ISSUE TITLE
Problem with Hungarian "ő" and "ű" letters

### ISSUE THREAD

**Issue by RitliRoland** [dompdf/dompdf#2947]
I experienced problems with some Hungarian letters which are part of utf-8. If I create a PDF from this:
áéíöóőúűÁÉÍÖÓŐÚŰ

It will be this:
áéíöó?ú?ÁÉÍÖÓ?Ú?

The library doesn't handle the "ő", "ű", "Ő" and "Ű" letters correctly.

**Comment by bsweeney** [comment]
If you're using one of the core PDF fonts bundled with all PDF readers (courier, helvetica, times) [character support is limited](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding). A lot of PDF rendering engines substitute a font with greater character support because of this, but Dompdf does not. You need to make sure you're [specifying a font that supports your characters](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo).

Try:

```
<span style="font-family: DejaVu Sans;">áéíöóőúűÁÉÍÖÓŐÚŰ<span>
```
