### ISSUE TITLE
Renedering Unicode-Symbol „∑“ (U+2211) in PDF

### ISSUE THREAD

**Issue by BISTCON** [dompdf/dompdf#2954]
Hi there,

I am currently trying to include the „∑“ symbol in one column of a table I render in a pdf document. However, all the time this Symbol gets to a "?" in the pdf document.
I already tried to replace the symbol by `&#8721;`, `&#x2211;` and `&sum;`. But this lead to the same result.

After a while, I have checked the files of dompdf. In "lib/html5lib/Data.php I found a reference table. Therefore I just tried to add a line here "0x91 => 0x2211". But that did not work as well.

Is there a way to include this symbol or am i missing out on something here?

**Comment by bsweeney** [comment]
Character support in the core PDF fonts is limited to those supported by Windows ANSI encoding. That's why most PDF generators don't actually use the core fonts, replacing instead with a Unicode variant. Dompdf does not currently do this replacement so you just need to make sure you specify a font that supports your characters. The bundled DejaVu fonts would work:

```
<span style="font-family: DejaVu Sans;">∑ &#8721; &#x2211; &sum;</span>
```
