### ISSUE TITLE
get_page_count() , {PAGE_NUM} / {PAGE_COUNT} last working in version 1.2.2

### ISSUE THREAD

**Issue by agenthero** [dompdf/dompdf#2971]
Page numbering in online demo
https://eclecticgeek.com/dompdf/debug.php
page_pages.html
not working anymore.
Instead use
https://github.com/dompdf/dompdf/issues/1636

**Comment by bsweeney** [comment]
I think you mean 2.0.0? That functionality still works but it's implementation changed. Page script and page text are now processed immediately rather than after document rendering is complete. That's noted in the release notes: https://github.com/dompdf/dompdf/releases/tag/v2.0.0

I updated that demo so that it works in 2.0.0 as well as older releases (just moved the script to the bottom of the document).

**Comment by TaiHV0211** [comment]
Hello @bsweeney i have problem with get_page_count only show 1
```
 public function pdfExport(Request $request){
        $jsonData = $request->input('filterJson');
        $jsonDataDecoded = html_entity_decode($jsonData);
        $events = json_decode($jsonDataDecoded, true);
        $currentTime = Carbon::now();
        $currentTime = $currentTime->format('Y/m/d (a) h:i');
        $export_pdf_data = PDF::loadView('frontend.sell.templatepdf', compact('events','currentTime'));
        $export_pdf_data->setPaper('A4');
        return $export_pdf_data->download('20230927.pdf');

    }
```
and file blade is :
```
<script type="text/php">

                if ( isset($export_pdf_data) ) {
                
                  $size = 6;
                  $color = array(0,0,0);
                  if (class_exists('Font_Metrics')) {
                    $font = Font_Metrics::get_font("Noto Sans JP");
                    $text_height = Font_Metrics::get_font_height($font, $size);
                    $width = Font_Metrics::get_text_width("Page 1 of 2", $font, $size);
                  } elseif (class_exists('Dompdf\\FontMetrics')) {
                    $font = $fontMetrics->getFont("helvetica");
                    $text_height = $fontMetrics->getFontHeight($font, $size);
                    $width = $fontMetrics->getTextWidth("Page 1 of 2", $font, $size);
                  }
                
                  $foot = $export_pdf_data->open_object();
                  
                  $w = $export_pdf_data->get_width();
                  $h = $export_pdf_data->get_height();
                
                  // Draw a line along the bottom
                  $y = $h - $text_height - 24;
                  $export_pdf_data->line(16, $y, $w - 16, $y, $color, 0.5);
                
                  $export_pdf_data->close_object();
                  $export_pdf_data->add_object($foot, "all");
                
                  $text = "Page {PAGE_NUM} of {PAGE_COUNT}";  
                
                  // Center the text
                  $export_pdf_data->page_text($w / 2 - $width / 2, $y, $text, $font, $size, $color);
                  
                }
                </script>
```
But this not working

**Comment by bsweeney** [comment]
With the latest release you'll need to place the `page_text` call at the bottom of the document for it to show on all pages. The object-related script should remain at the top. Other than that I don't really have much guidance since your sample only shows the script from the HTML template. Running that code on my test system is fine.

This issue is long closed I recommend you [start a new discussion](https://github.com/dompdf/dompdf/discussions/new/choose) to determine why you're having issues.

**Comment by TaiHV0211** [comment]
How to add page_text in blade file ? 🥲 
You can write for me 1 example html 🥺

**Comment by TaiHV0211** [comment]
You have setOptions([isEnablePhp=> true])?

**Comment by bsweeney** [comment]
I do, yes.

Recommending, again, that you [start a new discussion](https://github.com/dompdf/dompdf/discussions/new/choose).
