### ISSUE TITLE
Problems generating PDF

### ISSUE THREAD

**Issue by nanocarp01** [dompdf/dompdf#2986]
I am doing the generation of massive pdf (invoicing), and it generates between 50 or 60 pdf correctly, after that it generates the pdf as if it did not take the css styles!! What could be the problem?

**Comment by bsweeney** [comment]
I've seen similar reports before but have been unable to reproduce the issue. Can you provide more details? Any errors in the PHP logs? Are you generating 50 PDFs or a PDF with 50 pages ... or both? What is the control logic like?

**Comment by nanocarp01** [comment]
no, in the php logs it doesn't show anything!! I am generating individual invoices of 6k clients, and as I mentioned, it generates 50 or 60 pdf of a single page well and from there it generates them badlly

so it looks right
![WhatsApp Image 2022-08-20 at 9 58 01 PM](https://user-images.githubusercontent.com/71789047/185794984-01725e10-47d5-4530-ab03-addad2c75fc3.jpeg)

and so when it starts to generate bad
![WhatsApp Image 2022-08-20 at 9 58 52 PM](https://user-images.githubusercontent.com/71789047/185795003-6210d340-d473-45ba-b8cc-003000963f69.jpeg)

**Comment by nanocarp01** [comment]
In short, and perhaps it is better understood, when the massive invoice is generated (an invoice is generated per client), these are saved in a local folder, to later be sent by mail, and there it is as I said, it correctly generates between 50 and 60 and then it starts to generate them as if it didn't take the css styles

**Comment by bsweeney** [comment]
Because I'm unable to reproduce the issue (for example, I am able to generate 400 PDFs without issue) I will need more information on your particular setup to be able to provide any guidance.

Are the resources (css, images) internal to the HTML document or externally linked? Can you provide a sample of the HTML + CSS?

What is the control structure? Is it along the lines of:

```
foreach invoice
  create new Dompdf instance
  render PDF and save
  unset Dompdf instance
end foreach
```

If so you might try externalizing the actual rendering to a separate process:

```
foreach invoice
  save invoice HTML to disk
  exec PHP script to render individual invoice
  delete invoice HTML
end foreach
```

where the exec line calls another PHP script and you pass in the HTML document as an argument. This isolates the rendering of each individual document so it less likely to experience errors due to resource reuse or static variables.

**Comment by nanocarp01** [comment]
in these 3 files are the parts separately

Here I create the structure of the PDF with html and css
[html structure.txt](https://github.com/dompdf/dompdf/files/9389901/html.structure.txt)

in this I call the function generate pdf with the content of the database
[function call.txt](https://github.com/dompdf/dompdf/files/9389905/function.call.txt)

in this other I generate the pdf with the previous content
[generate pdf.txt](https://github.com/dompdf/dompdf/files/9389903/generate.pdf.txt)

**Comment by bsweeney** [comment]
Shouldn't be causing your issue but I see in the `htmlToPDF` function you're calling `$dompdf->output()` to capture the PDF, then later calling `$dompdf->stream()`. Right now if you're using the CPDF back end you can only call one of those methods one time. Calling either method again will produce a corrupted PDF.

It will take a bit of time to parse through the logic to see if I can identify the cause of the issue.

What version of Dompdf are you using? If you're not yet using 2.0.0 you might try upgrading to see if that helps.

**Comment by nanocarp01** [comment]
According to what I can see, it is version 1.2.1 that I am using! I'll try what you tell me to see if it fixes the problem. thanks for replying

**Comment by nanocarp01** [comment]
could it be because the server runs out of memory?

**Comment by bsweeney** [comment]
It seems if that were the case then the whole process would die? But I wouldn't entirely discount it as a possibility. You might also check on disk storage. I have an issue with the temp mount on one of my systems where it fills up and so things appear to be running but fail in unfortunate ways because there's nowhere to write temp files.

**Comment by nanocarp01** [comment]
I haven't updated dompdf yet because I'm waiting for confirmation from my project manager. When I confirm and if the problem is solved I'll comment so you know it's solved!

**Comment by nanocarp01** [comment]
I was able to solve the problem, it was an error in the css, in the div that looked bad it was missing a margin

**Comment by bsweeney** [comment]
huh, ok ... thanks for the update

**Comment by nanocarp01** [comment]
thanks to you, for the predisposition to find the solution to my problem
