### ISSUE TITLE
span style margin-left not working 

### ISSUE THREAD

**Issue by samvidhik** [dompdf/dompdf#2991]
`<span style="margin-left:50px;"> </span>`  was working in earlier version but not working now.

**Comment by bsweeney** [comment]
What version are you using and what's the context of your usage? I tried the following in 2.0.0 and it seems fine:

```
<div style="border: 1px solid orange;">
  <span style="margin-left:50px;">dompdf</span>
</div>
```

**Comment by samvidhik** [comment]
I am using version 2.0.0. `<span style="margin-left:50px;"> </span>` with only single space as innerHTML was earlier giving indentation but not anymore. The same span element i.e. with only single space as innerHTML, is giving indentation in chrome browser.

**Comment by bsweeney** [comment]
But how do you know it's not working if all you have is a span with a space? Context is important. I modified my example and can see the issue now:

```
<div style="border: 1px solid orange;">
  <span style="margin-left:50px;"> </span>dompdf
</div>
```

Looks like maybe the span is optimized out of the layout since it has no content. You can work around the issue for now by using a non-breaking space instead:

```
<div style="border: 1px solid orange;">
  <span style="margin-left:50px;">&nbsp;</span>dompdf
</div>
```

**Comment by samvidhik** [comment]
Thanks.

**Comment by bsweeney** [comment]
I'm going to keep this issue open so we can address the underlying bug for a forthcoming release.
