### ISSUE TITLE
Fonts and borders? Issue with table borders and external fonts not loading

### ISSUE THREAD

**Issue by HeadStudios** [dompdf/dompdf#2997]
Hi, so not sure if I'm doing it correctly but I have this at the start of my 'HTML' that gets passed to DomPDF:

```
<style>
                @font-face {
                    font-family: "Roboto";
                    src: url("https://headstudios.github.io/handshake/fonts/Roboto-Regular.ttf") format("ttf"),
                    }
                table { width: 100%; border-collapse: collapse; border: 1px solid black;  }
                td, th {
                    border: 1px solid black;
                }
                html,body,table,td,th { font-family:Roboto; }
                </style>
```

However the font doesn't look like Roboto.. and there's no table borders - https://share.getcloudapp.com/7KukvlBR

Any input much appreciated.

Thanks!

**Comment by bsweeney** [comment]
What version of Dompdf are you using?

I'm seeing table border just fine so some other aspect of your HTML + CSS could be impacting the rendering.

As for the Roboto, the format should be "truetype" instead of "ttf".

**Comment by HeadStudios** [comment]
Thank you - apprecaite the truetype feedback - am I doing it better?

<style>
                @font-face {
                    font-family: "Roboto";
                    src: url("https://headstudios.tiiny.site/Roboto-Regular.ttf") format("truetype"),
                    }
                table { width: 100%; border-collapse: collapse; border: 1px solid black;  }
                td, th {
                    border: 1px solid black;
                }
                html,body,table,td,th { font-family:Roboto; }
                </style>

Now I'm getting a weird error wut the... no idea where that file format came from:
https://share.getcloudapp.com/jkuWqkQP

Ohh well... as far as tables go I can create a blank version to test to demonstrate issue because my one has some functions in it...  as far as version of Dompdf... one sec it's saying version2.0.0 is that outdated? 
https://share.getcloudapp.com/bLu5rLRz

Thank you for all your help and your quick replies!

**Comment by HeadStudios** [comment]
Ok so you're right... borders are my bad - https://share.getcloudapp.com/o0uXj0eX (just tested separate)... so all that's left is just Roboto text setup... I keep getting that error and yeh.. just trying to make my font not lame you know.

**Comment by bsweeney** [comment]
2.0.0 is the current release so you're good.

You might be running into an issue writing temp files. When you reference a remote file Dompdf write it to disk, along with a font metrics file, using a filename similar to what you're seeing there. Dompdf thought it was able to write the file, but it actually did not, that would be a problem. Or if you're copying your project from one system to another then the font path recorded may be incorrect.

**Comment by HeadStudios** [comment]
Got ya.. yeh I had a feeling that was what it is... I'm using Laravel and I'm on a localhost - I guess I can ask the Laravel reddit community (they're always helpful) about any obstacles in the way of writing temporary files... I imagine that because the issue seems to be write that it can access the file.. it just can't write it. Any input you have on a fix would be much appreciated - thank you for your help!

**Comment by bsweeney** [comment]
You can specify different directories for temp files and/or font files. Might start there to see if it helps. Info on changing configuration here: https://github.com/barryvdh/laravel-dompdf#configuration

I don't use laravel so I may not be able to provide much help. But I do know that storage/fonts is the typical location for user fonts.

If you have incomplete font metrics for some reason you can reset the dompdf/lib/fonts directory back to it's newly-installed state and remove everything from storage/fonts. The main thing is to remove the installed-fonts.json file (if it exists). Leave the installed-fonts.dist.json since that's used for the fonts distributed with the library.

**Comment by HeadStudios** [comment]
Got you, thank you so much! I have stuff to go on with and investigate... I wonder if I can just leave the ttf file in storage/fonts and just have it be found automatically.. then again i still have to define it in... the actual HTML.. ugh well you know that's where testing comes in. Thanks again for equipping me on my journey so I'm not completely stumbling in the dark. Chrs!

**Comment by bsweeney** [comment]
Always happy to at least be a sounding board while you work through your issues. Sometimes I may even have helpful advice lol.

Unfortunately automatic font loading doesn't exist (though it has been requested). It'd be a good feature request though requires some planning so we're not constantly looking for new files.

**Comment by HeadStudios** [comment]
Hey! So.. no Arial or Tahoma as standard or anything? https://share.getcloudapp.com/o0uXvL4N - still trying to figure out how to load some fonts I was hoping I could at least do some Tahoma even if I didn't fix my whole woff/ttf thing :(

**Comment by HeadStudios** [comment]
New problem lol:
https://share.getcloudapp.com/qGuxKbN0

Code: .. I don't think I can attach files here so.. https://gist.github.com/HeadStudios/a5f7df1a4766390af876f94705254301 .. and the OpenSans (I tried with Roboto too) file is here: https://fonts.google.com/specimen/Open+Sans ... and... it's inside static>OpenSans>OpenSans-Medium.ttf ... man I thought I was so close to fixing the font issue lmfao.. oh well back to square one

**Comment by HeadStudios** [comment]
I'll just keep trying different fonts I guess..

**Comment by HeadStudios** [comment]
https://headstudios.com.au/wp-content/uploads/fonts/agreement-example.pdf - this is even for Montesserate Black - it uses the same non standard font each time and then cuts up the lines :( - I actually wouldn't mind using this font if it didn't get cut.

**Comment by HeadStudios** [comment]
Wait... I just realised it's all squares.. I guess downloading from browser is a no go lol - ohhh man this is overwhelming one sec

**Comment by HeadStudios** [comment]
!!!!! It works when I download it - just not in preview when I stream to browser!!! Yaaaaay!! **disco time**

**Comment by bsweeney** [comment]
Standard fonts are Helvetica, Times, Courier (or just use the generic names sans-serif, serif, monospace). We also bundle the DejaVu Sans fonts which has better character support. System fonts can't be used unless you've installed them for Dompdf, so referencing Tahoma (for example) won't work unless you have a corresponding `@font-face` declaration.

WOFF fonts aren't supported at all yet, but (most) TTF fonts should be. Sometimes php-font-lib has trouble parsing a font, though I haven't had time to look into the issue. I was able to load Roboto from your system and it works fine so the issue is likely configuration-related. Have you enabled remote resource support (isRemoteEnabled)? That would be required for accessing resources via HTTP(S).

Your Montesserate sample is ... something else. I think you're running into a font corruption issue there that we've seen before. One cause could be using both `stream` and `output` on the same render. I also think there's a possible issue with font subsetting but have not had a chance to look into it yet.

...

Just realized you closed the issue and saw that it's disco time smh. Info above still relevant, though I guess not necessary to digest at this point.
