### ISSUE TITLE
Road map question

### ISSUE THREAD

**Issue by micker** [dompdf/dompdf#3030]
Hello did you plan to add :
- box-shadow
- table of content 

in next version ?
an other question what is the best html code (for best render) for a column display ?
thanks for your works

**Comment by bsweeney** [comment]
Plans? Sure. Road map? Nope.

Box shadow is covered by #1197 and any updated will appear there. I'll put that issue in the 2.1.0 milestone, but note that issues associated with a milestone would not be guaranteed for that release until they have been completed. As we get closer to preparing a release unfinished issues get moved to a later milestone.

What do you mean by table of contents? Do you mean as a page within the PDF? That's covered by #217. Probably not going to be working on that anytime soon. There is some code floating around that can help you generate one using callbacks and page scripts.

As for multi-column display ... Dompdf can't handle this right now, unless the entirety of your document can fit on a single page. That's because of the way Dompdf renders a document at present. It will take a bit of re-architecting before Dompdf can do something like that. Watch #589 for updates.
