### ISSUE TITLE
Draw rectangle with canvas

### ISSUE THREAD

**Issue by Whip** [dompdf/dompdf#3052]
I want to create a footer which is some box that contains page numbers. I have the page numbers displaying but there is no rectangle option mentioned in Wiki > Usage. I could create a hollow box using 4 lines but I would really prefer if I could have a proper rectangle with a color filled in.

Is there a method that can do this or a workaround? Seems like a common scenario.

**Comment by bsweeney** [comment]
The wiki documentation doesn't currently provide full documentation for the Canvas interface. At some point I'll produce that, but in the meantime the [Canvas interface source](https://github.com/dompdf/dompdf/blob/master/src/Canvas.php) can get you the info you need since it's not cluttered up with any logic.

Here's the relevant bit for [drawing a rectangle](https://github.com/dompdf/dompdf/blob/master/src/Canvas.php#L112):
```
/**
 * Draws a filled rectangle at x1,y1 with width w and height h
 *
 * @param float $x1
 * @param float $y1
 * @param float $w
 * @param float $h
 * @param array $color Color array in the format `[r, g, b, "alpha" => alpha]`
 *                     where r, g, b, and alpha are float values between 0 and 1
 */
function filled_rectangle($x1, $y1, $w, $h, $color);
```
