### ISSUE TITLE
BUG: nth-child(1) not working

### ISSUE THREAD

**Issue by Marcvdc** [dompdf/dompdf#3056]
```
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<style type="text/css">
		#test .test1:nth-child(1) {
			color: red;
		}
		.test1 {
			color: green;
		}
	</style>
</head>

<body>

	<div id="test">
		<div class="test1">test</div>
		<div class="test1">test</div>
		<div class="test1">test</div>
	</div>

</body>
</html>
```

![image](https://user-images.githubusercontent.com/89011949/200340544-39148561-a12b-472a-8f66-18b273b24808.png)

**Comment by bsweeney** [comment]
`nth-child(1)` works but there's an issue around class selectors combined with nth-* selectors. That issue was previously brought up in #2222.

There appears to maybe also be a specificity issue since adjusting the styling to the following is still rendered incorrectly:

```
div div:nth-child(1) {
  color: red;
}
.test1 {
  color: green;
}
```

but when leaving out the `.test1` styling the first div is colored red.

**Comment by Mellthas** [comment]
#3059 fixes the `nth-child` handling and the initial sample, but not the specificity issue. Here is another variation of the initial sample exhibiting that issue with the PR applied:

```css
#test .test1:nth-child(1) {
    color: red;
}
#test .test1 {
    color: green;
}
```
