### ISSUE TITLE
Texts are not showing properly using dompdf and ar-php library

### ISSUE THREAD

**Issue by shaycoder** [dompdf/dompdf#3081]
I have used the following code:

        require_once 'ar-php/src/Arabic.php';
        $Arabic = new ArPHP\I18N\Arabic();

        $html = يقول الله عز وجل :(وكلوا واشربوا ولا تسرفوا إنه لا يحب المسرفين) الأعراف

        $p = $Arabic->arIdentify($html);

        for ($i = count($p)-1; $i >= 0; $i-=2) {
            $utf8ar = $Arabic->utf8Glyphs(substr($html, $p[$i-1], $p[$i] - $p[$i-1]));
            $html   = substr_replace($html, $utf8ar, $p[$i-1], $p[$i] - $p[$i-1]);
        }

but its coming like لا يحب المسرفين) الأعراف يقول الله عز وجل :(وكلوا واشربوا ولا تسرفوا إنه

Pls any help would be appreciated.

**Comment by bsweeney** [comment]
I'm going to be of minimal help since I do not read Arabic nor use ArPHP. So just looking at the text I can't tell exactly what's wrong with it. However, utf8Glyphs is capable of handling English characters (per the documentation) so for that bit of content you shouldn't need to run through arIdentify and can just parse the entire string.

Presumably, though, you're going to want to parse an entire HTML document. I can't say how well this method will work in that use case.

At any rate it looks like you're opened the same issue with the ArPHP project. They're the appropriate persons from whom to seek support for that library.

**Comment by shaycoder** [comment]
Hi @bsweeney sir, Thank you for your reply.
