### ISSUE TITLE
'object_fit' is not a recognized CSS property.

### ISSUE THREAD

**Issue by dinhbang** [dompdf/dompdf#3093]
Hello everybody.

I am using generate pdf from html&css with images. I am using object-fit. But, It is show error below:

> 'object_fit' is not a recognized CSS property.

Could you help me?

Best regards,
Bang.

**Comment by bsweeney** [comment]
As indicated by the error message that particular property is not yet supported. I'll flag this for a future release. I imagine we should be able to re-purpose existing logic from the background image renderer.

**Comment by dinhbang** [comment]
@bsweeney Thank you so much! I hope you will release soon new update. The object-fit is important property for scale image

**Comment by kaamui** [comment]
I think this issue is a duplicate of #2278

Also, `object-fit` support was initially planned for 2.0.2, then 2.0.3, now 2.0.5 and this new issue it is planned for 2.1.0 ... is it that the feature is really hard to implement ? Do you think it is possible for it to be available for 2.0.5 ?

Thank you for your work on this cool library.

**Comment by bsweeney** [comment]
Thank you for pointing that out @kaamui. I haven't looked at the issue more so I can't say when I could work on it. I will bump it up a bit since, as discussed in 2278, the logic seems similar to what we use for background sizing. No guarantee it'll get done for the next release, though.
