### ISSUE TITLE
Is CSS Transform Being Handled Correctly?

### ISSUE THREAD

**Issue by oleibman** [dompdf/dompdf#3096]
Please see attached zip file. It contains 3 other files - an html file, a php program that converts the html to pdf using dompdf, and the output pdf file of the php program. The html file contains a table with one very wide row. The table is "naturally" too wide to fit on the page. As a result, I apply the following css: `table {transform: scale(0.7);}`. I believe this is the appropriate way to scale the table - it has the desired effect in browsers and at least one other pdf renderer. The CSS compatibility table at https://github.com/dompdf/dompdf/wiki/CSSCompatibility says that `transform` is supported "Except for 3D transformations", of which this is not an example. Nevertheless, it is not working as I expected with dompdf - the table may (or may not) be scaled, but it is translated to the right to such an extent that it still does not fit on the page. Is dompdf handling this correctly? If yes, is there some other way that I can get my desired result?
[testdompdf2.zip](https://github.com/dompdf/dompdf/files/10334101/testdompdf2.zip)

**Comment by bsweeney** [comment]
Dompdf is working as expected. Your table dimensions as defined are 2002.75pt. At a scale of 0.7 that's 1401.925. A letter size page (the default for Dompdf) is 612.00pt x 792.00pt (portrait). So even scaled down your table width is almost twice the width of a landscape page. You would need to set your page to landscape and scale by a factor of around 0.35 for the element to even fit on the page.

Additionally, transformation is applied _after_ the element is positioned in the document. It does not take up less space just because you made it appear smaller. The default transformation origin point is the center point of the element, so when you scale it scales around the center point. You can see this in the browser as well, that's why the table appears centered on the page. If you don't want the element to be shifted to the right so much you have two options: 1) modify the transform origin so that it transforms around the left edge; 2) translate towards the left side of the page.

Try the following HTML:

```

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Test Table and CSS Transform</title>
<style type="text/css">
@page { size: letter landscape; }
td {border: 1px solid black;}
table {transform: scale(0.35); transform-origin: 0% 0%;}
</style>
</head>
<body>
<div>
    <table>
        <tbody>
          <tr class="row0">
            <td class="column0 style0" style="width:120.75pt">a123456789.0</td>
            <td class="column1 style0" style="width:229.5pt">b123456789.0</td>
            <td class="column2 style0" style="width:165.25pt">c123456789.0</td>
            <td class="column3 style0" style="width:165.25pt">d123456789.0</td>
            <td class="column4 style0" style="width:165.25pt">e123456789.0</td>
            <td class="column5 style0" style="width:165.25pt">f123456789.0</td>
            <td class="column6 style0" style="width:165.25pt">g123456789.0</td>
            <td class="column7 style0" style="width:165.25pt">h123456789.0</td>
            <td class="column8 style0" style="width:165.25pt">i123456789.0</td>
            <td class="column9 style0" style="width:165.25pt">j123456789.0</td>
            <td class="column10 style0" style="width:165.25pt">k123456789.0</td>
            <td class="column11 style0" style="width:165.25pt">l123456789.0</td>
          </tr>
</tbody>
</table>
</div>
</body>
</html>
```
