### ISSUE TITLE
Skipping page 1 stopped working

### ISSUE THREAD

**Issue by pud-micha** [dompdf/dompdf#3107]
Hello,

```
$pdf->getCanvas()->page_script('
	if ($PAGE_NUM > 1) {
		$font = $fontMetrics->getFont("helvetica", "normal");
		$size = 10;
		$color = [ 0, 0, 0 ];
		$word_space =
		$char_space =
		$angle = 0.0;

		$x = 4.5*16;
		$y = 48;
		$text = "Page {PAGE_NUM} of {PAGE_COUNT}".$PAGE_NUM;
		$pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
	}
');
```

This is now on all pages. Before the update from 1.1 to 2.0 the first page was skipped. `$PAGE_NUM` in the text is all page numbers at once.

Thank you.

**Comment by bsweeney** [comment]
You should be using `$pdf->text()` instead of `$pdf->page_text()`. page_text adds the specified text to every page of the document. So you are adding the same text to the document for every page greater than 1: 2 pages = 1 time; 3 pages = 2 times, etc.

You should note that how Dompdf handles scripts [changed with 2.0.0](https://github.com/dompdf/dompdf/releases/tag/v2.0.0). You'll want to move that declaration _after_ the `$dompdf->render()` statement.

I might also suggest [using a function](https://github.com/dompdf/dompdf/wiki/Usage#page_script) instead of text. It'll be easier to maintain.

```
$dompdf->getCanvas()->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
	if ($pageNumber > 1) {
		$font = $fontMetrics->getFont("helvetica", "normal");
		$size = 10;
		$color = [ 0, 0, 0 ];
		$word_space = $char_space = $angle = 0.0;
		$x = 4.5*16;
		$y = 48;
		$text = "Page {$pageNumber} of {$pageCount}";
		$canvas->text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
	}
});
```
