### ISSUE TITLE
Right margin gap on right aligned span tag on PDF

### ISSUE THREAD

**Issue by HeadStudios** [dompdf/dompdf#3124]
Please find my PDF HTML below:
https://dev1.rrdevours.monster/playwithme

And here is the output of the PDF please notice the gap after the date:
https://www.docdroid.net/ILZvITX/shakashaka-4-pdf

Any input or advice on my issue would be much appreciated. Thank you!

**Comment by bsweeney** [comment]
This is happening because you're floating to elements that bump up against each other. The layout in the browser is slightly different. That may just be due to slightly differing line height calculations. For this particular use case it might be better to just `text-align: right`.

```
<div style="text-align: right">
<span style="float:right;" class="monts">Kosta Kondratenko</span>
<br>
<span style="float:right;" class="monts">Feb 2, 2023</span>
</div>
```

Or, if you want to stick with floats, instead of a `<br>` you should use the clear property.

```
<div style="text-align: right">
<span style="float:right;" class="monts">Kosta Kondratenko</span>
<br>
<span style="float:right; clear: both;" class="monts">Feb 2, 2023</span>
</div>
```

(normally you wouldn't need the `<br>` when clearing the prior floats but Dompdf doesn't appear to handle this correctly if there's no content between the two floats.

**Comment by HeadStudios** [comment]
Thank you I can confirm this has fixed my issue.

**Comment by bsweeney** [comment]
FYI you did expose an issue, which I documented in #3125

**Comment by HeadStudios** [comment]
> FYI you did expose an issue, which I documented in #3125

Thank you for letting me know and I'm glad I could be of assistance in improving the package.
