### ISSUE TITLE
Very long pdf generation when setIsRemoteEnabled() is set to true

### ISSUE THREAD

**Issue by FBL-dev** [dompdf/dompdf#3147]
I just switched my project to docker with Caddy web server (I was previously using Nginx).
With Nginx, everything was working fine.
Now, with Caddy, I get the following error when I generate and stream a pdf:
{"level": "error", "ts":1678207379.2687008, "logger": "http.handlers.reverse_proxy", "msg": "aborting with incomplete response", "error": "http2: handler wrote more than declared Content-Length"}

When setIsRemoteEnabled() is true, the generation of the pdf is extremely long. When it is set to false, the pdf is generated very quickly.

Do you know how to fix this error?
Thanks

**Comment by bsweeney** [comment]
Is there an error at the PHP level?

I haven't seen this particular error before. What version of Caddy are you running? Seems there was an [issue with compression](https://github.com/caddyserver/caddy/issues/38) that was fixed a while ago.

**Comment by FBL-dev** [comment]
No, I see the error on the Caddy image on docker.
On the level of PHP, I have no error.

After checking, I always get this error when setIsRemoteEnabled() is set to false.
So I think this error has nothing to do with my problem of slow generation of pdf.

I don't understand why it takes so long to generate the pdf just by setting setIsRemoteEnabled() to true.

**Comment by bsweeney** [comment]
Without more information it's hard to say. As a guess? Maybe the remote requests are timing out, so the PDF generation is failing just due to going over the allowed execution time.

You can try to get more info out of Dompdf by [enabling additional debug messaging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf).

**Comment by FBL-dev** [comment]
Indeed, the problem is fixed when I delete the remote request:
`<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">`

I have enabled additional debug messaging but I only get :
`<span style='color: #000' title='Frames'>   465</span><span style='color: #009' title='Memory'>  12288.00 KB</span><span style='color: #900' title='Time'> 120444.56 ms</span><span  title='Quirksmode'>  <span style='color: #0d0'>OFF</span></span><br />`

The curl extension is enabled and the setting allow_url_fopen is set to true

**Comment by bsweeney** [comment]
Note that the current release of Dompdf will have some issues processing that URL due to deficiencies in the parser. I'm working on an update for the next release. Though I don't think that's the cause of your issues, you check by simplifying your font import by choosing a single variant.

Could there be something intercepting your outbound requests and causing them to just ... die? Maybe try disabling allow_url_fopen. If allow_url_fopen is enabled then file_get_contents is used, otherwise curl is used (if available).

**Comment by FBL-dev** [comment]
Indeed, when allow_url_fopen is disabled, it works.
I tested file_get_contents from my docker image and it is indeed this function that takes a long time to run (while outside my docker image, it is almost instantaneous).

I close this issue because it's not a dompdf problem (but if you have a solution to fix my file_get_contents problem, I'd like it :) )

Thanks

**Comment by bsweeney** [comment]
I have no idea, though [this looks related](https://forums.docker.com/t/docker-breaks-php-file-get-contents-and-http-s-stream-wrappers/132885):

> Can also confirm disabling Automatic proxy detection solved this issue.
