### ISSUE TITLE
When generating font, installed-fonts.json is created but code loadFontFamilies looks for installed-fonts.dist.json

### ISSUE THREAD

**Issue by dhamaris** [dompdf/dompdf#3192]
Hello, I am using dompdf v2.0.1, with php 8.1 and drupal 9.5.2 and I needed to add support for cyrillic fonts, so I did the following steps:

- Download https://github.com/dompdf/utils and copy load_font.php to /src (at the same level as vendor)
- Install php-font-lib: composer require phenx/php-font-lib (see https://github.com/dompdf/php-font-lib)
- Copy DejaVuSerif.ttf from vendor\dompdf\dompdf\lib\fonts/fonts to /src

At this point, I have an **installed-fonts-dist.json** with lots of fonts but no absolute paths, something like: 

```
    "dejavu serif": {
        "bold": "DejaVuSerif-Bold",
        "bold_italic": "DejaVuSerif-BoldItalic",
        "italic": "DejaVuSerif-Italic",
        "normal": "DejaVuSerif"
    }
```

- generate **installed-fonts.json** calling (from src) this command: php load_font.php "dejavu serif" DejaVuSerif.ttf

At this point a installed-fonts.json gets generated with just DejavuSerif font, using absolute paths:

```
{
    "dejavu serif": {
        "normal": "C:\\Users\\Public\\Dev\\euromod_website\\src\\vendor\\dompdf\\dompdf\/lib\/fonts\/DejaVuSerif",
        "bold": "C:\\Users\\Public\\Dev\\euromod_website\\src\\vendor\\dompdf\\dompdf\/lib\/fonts\/DejaVuSerif",
        "italic": "C:\\Users\\Public\\Dev\\euromod_website\\src\\vendor\\dompdf\\dompdf\/lib\/fonts\/DejaVuSerif",
        "bold_italic": "C:\\Users\\Public\\Dev\\euromod_website\\src\\vendor\\dompdf\\dompdf\/lib\/fonts\/DejaVuSerif"
    }
}
```

If I leave it like that, it does not work because in code it searches for installed-fonts.dist.json. In FontMetrics.php I see this:

```
    /**
     * Name of the user font families file
     *
     * This file must be writable by the webserver process only to update it
     * with save_font_families() after adding the .afm file references of a new font family
     * with FontMetrics::saveFontFamilies().
     * This is typically done only from command line with load_font.php on converting
     * ttf fonts to ufm with php-font-lib.
     */
    const USER_FONTS_FILE = "installed-fonts.json";
```

and this:

```
    /**
     * Loads the stored font family cache
     *
     * @see FontMetrics::saveFontFamilies()
     */
    public function loadFontFamilies()
    {
        $file = $this->options->getRootDir() . "/lib/fonts/installed-fonts.dist.json";
        $this->bundledFonts = json_decode(file_get_contents($file), true);

        if (is_readable($this->getUserFontsFilePath())) {
            $this->userFonts = json_decode(file_get_contents($this->getUserFontsFilePath()), true);
        } else {
            $this->loadFontFamiliesLegacy();
        }
    }
```

so I do this:

- rename installed-fonts.dist.json as installed-fonts.dist.jsonold
- make a copy of installed-fonts.json and rename as installed-fonts.dist.json on fonts folder 
-Set default font
$options->set('defaultFont', 'dejavu serif');

Now it works but this is no clean solution, do you know what I might be doing wrong?

**Comment by bsweeney** [comment]
installed-fonts.dist.json is always used because it contains information about the fonts distributed with Dompdf. That is why that file has a hard-coded reference. Also, the .dist file is expected to always be in the same location relative to the project and that is why a file path is not necessary (there is a related request for installed fonts, see #2953).

I'm not quite sure what is not working here since all you did was re-install the DejaVu font and then say it didn't work. You do not need to reinstall the bundled fonts you only need to reference them in your CSS (or set a new default, as you did after renaming some files).

**Comment by dhamaris** [comment]
Thank you for your swift reply. You mean that the only needed change I need to make is this one? 

`$options->set('defaultFont', 'dejavu serif');`

Because that did not work until I did the installation of dejavu serif...
You explained about .dist, but what about installed-fonts.json? Why there are reference to both names in the code?

**Comment by bsweeney** [comment]
Setting the default font (without having done anything else you described) will make that the font used for text in the PDF if no other font is specified in the document. You can also just specify the font via CSS (e.g., `* { font-family: DejaVu Sans, sans-serif; }`).

As for the two files. The .dist file is _always_ read because it references the fonts distributed with Dompdf. The other file is read to access fonts installed by the user.

**Comment by dhamaris** [comment]
My bad, there was a style being applied to some element inside the wysiwyg that I was not seeing.
Thank you for your help
