### ISSUE TITLE
German letter ẞ in upper-case not showing

### ISSUE THREAD

**Issue by aiichaa** [dompdf/dompdf#3193]
![image](https://user-images.githubusercontent.com/20442885/236500766-1f8c1d1c-906f-43d8-b8a7-9f29f9b9765d.png)

the german letter ẞ in upper-case turns into a square box, and the problem is only with this letter.
when I select the box in the pdf and copy/past i do get the correct letter, it's like a display problem in the generate pdf, but i'm not sure.

Thanks

**Comment by bsweeney** [comment]
Have you set an appropriate font? The core PDF fonts (Helvetica, Times Roman, Courier) only support characters included in Windows ANSI encoding. Same goes for the generic font families (sans-serif, serif, monospace) since those are aliases for the core fonts.

Current release of Dompdf includes the DejaVu fonts for greater character support.

```
<div style="font-family: DejaVu Sans">...</div>
```

There's more information in the wiki:
- [About fonts and character encoding](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding)
- [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)
