### ISSUE TITLE
Issue in chrome android

### ISSUE THREAD

**Issue by arachmn** [dompdf/dompdf#3200]
why when I download a pdf on chrome android, the download results have html extension
for example
result.pdf.html
while on Windows it doesn't, but when I use other Android browsers like Opera it doesn't have a problem
I'm using codeigniter 4

**Comment by bsweeney** [comment]
I'm not sure on this one. This could just be standard operation for chrome on andriod. Or it could be that maybe something in the logic flow is modifying the content-type header after it was set by Dompdf, which could lead chrome to decide that the file extension should be html despite the filename provided in the file-disposition header.

Can you inspect the HTTP headers received by the browser?

**Comment by NimeCloud** [comment]
If the link redirects to another link then the pdf file renamed as pdf.html and if you remove the .html extension from the end the pdf will be open. I think it's a Chrome Android bug. Opera on Android or Chrome on Windows have no issues.

The problem is that the webserver adds header as the link is text-html. I was the owner of the webserver so I've added the custom header "Content-Type", "application/pdf" and fixed the problem.

Chrome Android looks for header and Chrome Windows looks for .pdf file extension to save the file.

**Comment by tajsoft4u** [comment]
> why when I download a pdf on chrome android, the download results have html extension for example result.pdf.html while on Windows it doesn't, but when I use other Android browsers like Opera it doesn't have a problem I'm using codeigniter 4

any solution did u got ?
