### ISSUE TITLE
Unable to render images

### ISSUE THREAD

**Issue by DEV7163** [dompdf/dompdf#3208]
Hey everyone, the company I'm working for has this legacy app where we need to embed some graphics in a PDF document.

Dompdf version: 448
PHP version: 5.3.29

The problem is the library refuses to render the images, I have tried both jpg and png. (Image not readable or empty)
If I directly render the images in the screen it works just fine.

Also tried with all possible paths, relative, absolute and remote (DOMPDF_ENABLE_REMOTE is set to true).
Case 1 and 3 it can't find the files, case 2 even weirder it renders a wrong image, some other random image which is already rendered in the document (created on the fly by using php images handling functionality).

I won't post the full code because it's a nasty mess but basically it's like this
```php
<?php ob_start();
session_start();
$prefix = 'tmp_graph_' .$_SESSION['company_id'] .'_*';
$path = getcwd().'/tmp/'.$prefix;
$files = glob($path);
foreach($files as $file) {
	echo '<div><img src="'.$file.'"></div>';
}
require_once("dompdf/dompdf_config.inc.php");
$dompdf = new DOMPDF();
$dompdf->load_html(ob_get_clean());
$dompdf->set_paper('a4');
$dompdf->render();
$pdf = $dompdf->output();
?>
```

Any idea?

**Comment by kordianurban** [comment]
```
$options = $dompdf->getOptions();
$options->set('isRemoteEnabled', true);
```

**Comment by DEV7163** [comment]
> $options = $dompdf->getOptions();
> $options->set('isRemoteEnabled', true);
> $dompdf->setOptions($options);

I don't think this old version has such functionality

`PHP Fatal error:  Call to undefined method DOMPDF::getOptions()`

Remote enabled here seems to be defined through a constant in a config file

```php
define("DOMPDF_ENABLE_REMOTE", true);
```

**Comment by bsweeney** [comment]
Local JPG with correct paths should be the easiest to figure since that scenario should not require any additional processing.

For case 1 & 2, the trick is ensuring the path is correct. Based on the sample code you shared the relative path would be relative from the executing script. Absolute path is always relative to the filesystem root. For HTTP access, make sure the script has read/write access to the temp directory.

Case 3 might be a problem with caching if the "name" of the image doesn't change between generation. Something I believe we still need to accommodate.

I'm not sure which version of Dompdf you're using. 448 ... is that a SVN revision? Running on PHP 5.3 you should be able to run [Dompdf 0.8.0](https://github.com/dompdf/dompdf/releases/tag/v0.8.3) so you might try downloading a copy of that version.

I'd be remiss if I didn't tell you to try and get your client to upgrade to a more modern version of PHP. They are probably, as I'm sure you are aware, highly susceptible to exploit.

**Comment by DEV7163** [comment]
@bsweeney thank you. 

DOMPDF 0.6.0 beta 3 seems to be the actual version according the changelog, 448 is  @version in the class file.

I'm going to process all what you suggested and reply back.

About they porting the code to a modern PHP version, absolutely, it was the first thing I suggested when I took this position, but they have other priorities, it's their call.

**Comment by DEV7163** [comment]
It seems jpg plus an absolute local path makes it, the thing is this generates me another problem, since the image is generated at runtime by using a format without transparency support I would have to re draw the background which I presume can be tricky.

Any particular reason this isn't working with png images? Anything else I can try?

**Comment by DEV7163** [comment]
Again, thank you.

```html
<span style='color: #000'>313 frames</span>	<span style='color: #900'>20,224 KB</span>	<span style='color: #090'>2,963.06 ms</span>	<span style='color: #009' title='Quirksmode'><span style='color: #c00'>ON</span></span><br />
```

This is the generated log.
Anyways, got back to the case #2 I mentioned before where the rendered image is not the right one.
 I don't want to waste your time here since it's probably not related with this library but just in case I'll attach the code where that other image is generated, I'm not really familiarized with PHP images handling functionality.
 
 ```php 
		$image = imagecreatefrompng($row_logoempresa[logo]);
		$bg = imagecreatetruecolor(imagesx($image), imagesy($image));
		imagefill($bg, 0, 0, imagecolorallocate($bg, 255, 255, 255));
		imagealphablending($bg, TRUE);
		imagecopy($bg, $image, 0, 0, 0, 0, imagesx($image), imagesy($image));
		imagedestroy($image);
		$quality = 50; 
		imagejpeg($bg, "./img/logo_temp_".$_SESSION['RGPD_id_empresa'].".jpg", $quality);
		imagedestroy($bg);	
 ```

**Comment by bsweeney** [comment]
If this were a dynamically-generated image over HTTP (e.g., http://example.com/image.jpg) it would be a Dompdf caching issue. In that scenario Dompdf reads the image once then uses the cached value for all references.

In your scenario where you're writing to a file it looks like a generation issue. I presume this is done in a loop (for each row crate a logo image)? If so, since the resulting image is written out to the same file each time based on the session id there's only a single image to read. The images are all generated prior to Dompdf rendering the document and written to the same file over and over. So, whatever image is written last is the one that Dompdf renders with.

I think you just need to tweak the logic ever so slightly to add a variable to the image naming convention:
```
imagejpeg($bg, "./img/logo_temp_".$_SESSION['RGPD_id_empresa']."_".logo.".jpg", $quality);
```
... or something like that.

Of course, you'll also have to update the generated HTML so the image references use the correct name.

**Comment by DEV7163** [comment]
Yes, it definitively seems to be a cache issue, I disabled the part where that other image was generated (it's not a loop by the way) and now I get all the graphics I'm trying to embed all rendered with the image of the first one, even worse, they all rendered as black and white when the original images are all in colors.

**Comment by DEV7163** [comment]
Good morning!

Sadly when I ported the code to the production server the problems started again, even with the library version you suggested and I was using in development, which seemed to fix all the problems.

Now I'm back again to the point where the wrong image is rendered which you mentioned would be a cache issue.
Please note I'm not generating these images with php functionality, I just read them from the file system and output them.

```php
$prefix = 'tmp_graph_' .$_SESSION['RGPD_id_empresa'] .'_*';
$path = getcwd().'/tmp/'.$prefix;
$files = glob($path);
foreach($files as $graphic) {
	echo '<div><img src="'.$graphic.'"></div>';
}
```

It think the problem is dompdf just can't find them.
I tried all the options:

1- With absolute local path: The problem mentioned above, the wrong image is rendered
2- With external path: I get "Image not found"
3- With relative local path: "Image not readable or empty"

In all the cases the paths I'm passing are valid, I triple checked, plus outputting directly to the screen shows the images correctly.

If there is anything else I can try please let me know, thanks!

**Comment by TasneemWahdan** [comment]
in the view I used this and the images now appear
<img **src="data:image/jpg;base64,{{$logo}}"** style="max-width:70%;">

**Comment by bondif** [comment]
You should `chroot` the root directory of your images. In your case, I guess it's: `getcwd() . '/tmp/'`

```
$imagesRootDirectory = getcwd() . '/tmp/';
$options = $pdf->getOptions();
$options->setChroot($_SERVER['DOCUMENT_ROOT'] . $imagesRootDirectory );
$pdf->setOptions($options);
```

Reference: https://laracasts.com/discuss/channels/laravel/dompdf-image-not-found-or-type-unknown-2?reply=646354
