### ISSUE TITLE
SVG with colors and transparency not respected?

### ISSUE THREAD

**Issue by glowenthal** [dompdf/dompdf#3245]
When using dompdf via Entity Print module in Drupal 9, my SVGs render out without the color defined and also without the transparency. It's almost like the tag within the SVG is being ignored. I am using SVG Image Field module which renders fine on HTML output, but not through dompdf Entity Print.

Steps to reproduce
Upload a svg with colors or transparency within the image to Drupal, see it render as black and your transparent pieces black.

Proposed resolution
Provide appropriate render support for SVGs with transparency and colors. Example: https://db.linpi.org/acmi 'deer resistant' svg icon is a deer with a circle and cross in it. If you go to the pdf render it will be a solid circle and a very sad black deer :( https://db.linpi.org/print/pdf/node/196

**Comment by glowenthal** [comment]
I rebuilt the template using PNGs so my test links won't work for you anymore, but the issue remains re SVG

**Comment by bsweeney** [comment]
If you can upload the original SVG here we can do some testing.

**Comment by fan711** [comment]
Not sure whether this is the same issue. But some of my SVG files are rendered just black instead of color while others are not visible at all. I could not figure out what is different to the files that work well so I attach samples here. In the browser they all look normal though.

![app_logo](https://github.com/dompdf/dompdf/assets/13937640/94d82590-bde1-4d6c-ad9f-b5754d833e05)
![logo](https://github.com/dompdf/dompdf/assets/13937640/cc4940ba-8342-44d6-a643-d55c09074eaa)

**Comment by bsweeney** [comment]
@fan711 at least one of your samples is affected by dompdf/php-svg-lib#98. Not sure about the other, though I suspect both will be addressed by the next release of SvgLib.

**Comment by bsweeney** [comment]
SvgLib 0.5.3 was just published. If you're using composer and update you should see this issue fixed.
