### ISSUE TITLE
Table td height PX suffix

### ISSUE THREAD

**Issue by 1ucay** [dompdf/dompdf#3262]
Hello, I dont know why, but if I have simple table with height, there is strange difference in height. 40px is ok, but 40 without px suffix is not.
<tr><td height="40"></td> </tr>

<tr><td height="40px"></td> </tr>

**Comment by bsweeney** [comment]
Is not OK how? Sample HTML?

**Comment by 1ucay** [comment]
Sorry, I forgot.

    <!DOCTYPE html>
    <html lang="en">

    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>

    <body>
      <table bgcolor="#EEEEEE" cellpadding="0" cellspacing="0" width="100%">
        <tbody>
          <tr>
            <td>
              <table cellpadding="0" width="100%" cellspacing="0">
                <tbody>
                  <tr>
                    <td class="spacer" height="40" style="width: 100%; background-color:  red;"></td>
                  </tr>
                  <tr>
                    <td class="spacer" height="40px" style="width: 100%; background-color: white;"></td>
                  </tr>
                  <tr>
                    <td class="spacer" height="40px" style="width: 100%; background-color:  red;"></td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </body>
    </html>

**Comment by bsweeney** [comment]
This is due to unit conversion. In this scenario Dompdf is treating "40" (without a unit) to "40pt" (PT being the native PDF unit). The widths with a unit are translated into PT during rendering. If the Dompdf DPI is configured at anything other than 72 (the fixed resolution of PDF documents) then the rendered size of pixel-based lengths will be smaller than point-based lengths.

So, your work-around is a viable solution. You could also set the Dompdf DPI to 72.

I'm considering allowing users to specify the default value for unitless length values. Follow #3054 if you're interested.

**Comment by 1ucay** [comment]
Hello, thank you for your reply. It's a little confusing. So Dompdf is set to 96 dpi by default? So I have to set it to 72? But for me table is much bigger than in browser in 72 dpi. Couldn't, unless the user manually sets it, these units be taken as px? I think, that library for many users is simple html => pdf convert, so it should be same as browser. But it is up to you of course.
