### ISSUE TITLE
Images are not showing in rendered PDF using Dompdf 2.0.3

### ISSUE THREAD

**Issue by DevDenAms** [dompdf/dompdf#3276]
I am using the code below, but the jpg image is not showing in the PDF. 
Instead I get the message "Image not found or type unkown". With a previous version of Dompdf, this code did work.

If anybody has any suggestions, they would be more than welcome!

    $dompdf_options = new \Dompdf\Options();
    $dompdf_options->set('chroot', "/images/");
    $dompdf_options->set('defaultFont', 'helvetica');

    $pdf = new \Dompdf\Dompdf($dompdf_options);
    $pdf->setPaper("A4", "portrait");
    ob_start();
    ?>
    <html>
        <head>
    <?php
    ?>
        </head>
        <body>
            <header>
                <img src='/images/scc_logo.jpg' >
                <span class='motto'>Place motto text here</span>
            </header>
            <footer>
                Page footer text
            </footer>
        </body>
    <?php

    $html = ob_get_clean();
    $pdf->loadHtml($html);
    $pdf->render();
    $output = $pdf->output();

**Comment by bsweeney** [comment]
Since this worked in a previous release is it safe to assume that "/images" is in the root of your filesystem? If so, it looks like you're doing what you need for this to work. From which version did you upgrade?

You can try to get more information about what's going on by [enabling additional debug messaging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf).

**Comment by DevDenAms** [comment]
Hi Brian,
Thank you very much for your swift reply. In answer to your questions in that reply:
- '/images' is in the root of the webproject folder. Is that what you mean?

- In the previous situation I used Dompdf 0.8.2 in combination with PHP 7.4.9
  Now I'm using Dompdf 2.0.3 in combination with PHP 8.2.1

- I switched on the debug messaging you suggested, and the log file that was produced from that only shows the following line:
   456 12288.00 KB 492.72 ms OFF

I have no idea where to go from here. Do you perhaps have any other suggestions?

**Comment by bsweeney** [comment]
Since you are loading the HTML using loadHtml Dompdf will read the path /images as from the root of the filesystem. It's possible that 0.8.2 interpreted this differently ... but I don't think so. You can confirm by updating the path (and chroot) to match the filesystem path to the /images directory.

**Comment by DevDenAms** [comment]
Hi Brian,
Once again, thanks for the support. 
It was indeed a path issue. I inserted $_SERVER['DOCUMENT_ROOT'] in front of the reference to the '/images/' folder in both the chroot and the actual img src, and that did the trick.
