### ISSUE TITLE
Dompdf 2.0.1 page count issue

### ISSUE THREAD

**Issue by BartGlim** [dompdf/dompdf#3279]
Hi,

I recently updated my DomPDF from 0.8.6 to 2.0.1 (using laravel dompdf but dont think that matters here). In 0.8.6 the following snippet worked perfectly as inline pdf:

```
    <footer>
        <script type="text/php">
            if (isset($pdf)) {
                    $x = 550;
                    $y = 820;
                    $text = "{PAGE_NUM} / {PAGE_COUNT}";
                    $font = $fontMetrics->get_font("helvetica");
                    $size = 9;
                    $color = array(0,0,0);
                    $word_space = 0.0;  //  default
                    $char_space = 0.0;  //  default
                    $angle = 0.0;   //  default
                    $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
            }
        </script>
    </footer>
``` 
This gave me perfect page numbering in combination with the page-break css options.
However after updating it produces the following:
![image](https://github.com/dompdf/dompdf/assets/48058881/cc4ed1e0-2638-4aea-9f38-6c90a798c8f8)

As you can see the PAGE_COUNT prints all page numbers on top of eachother. Only the final page renders it correctly (e.g 3/3). I can't really find what changed in the package. 

I did find advice in the issues pages to use FPDF/FPDI or merge packages to render the pages one by one and merge them, I'd like to keep that option as a last resort.

Could someone please give me some pointer as to where I need to change the code to make it work again? So far searching the web didn't really give me answers.
Thanks in advance.

**Comment by bsweeney** [comment]
Is the footer a `position:fixed` element? It's possible a change in how we render embedded script is now causing it to render with each instance of the footer. I'd have to go back to review the relevant architectural changes to be certain.

Since embedded script is rendered out of band from HTML content, I'd move that outside the footer element. Also note that in the latest release `page_text` is rendered immediately rather than after document rendering is complete, so you'll want to move that to the very end of the document.

**Comment by BartGlim** [comment]
Thanks @bsweeney, moving the footer to the bottom of the document and removing ```position:fixed``` fixed the rendering.
