### ISSUE TITLE
unable to load font from filesystem

### ISSUE THREAD

**Issue by EvEggelen** [dompdf/dompdf#3281]
I am unable to load fonts from my local server filesystem. I am also unsure where the files need to be located when using relative path. So far assumed the setBasePath was used also tried the fontDir without luck. Remote loading ( with url ) seems blocked due to CORS policy. Did I misunderstand something ?

```
 $options = new \Dompdf\Options();
            $options->set('defaultFont', 'Courier');
            $options->set( 'isRemoteEnabled', true);
            $options->set( 'dpi' , '96' );
            $options->set( 'chroot' , $_SERVER['DOCUMENT_ROOT']);
            $options->set( 'rootDir' , $dompdfDir );
            $options->set( 'fontDir' , $fontDir ); 
            $options->set( 'fontCache' , $fontCache );
            $options->set( 'logOutputFile' , $s_OutputDir . "/dompdf.log" );
            $options->set( 'tempDir' , $tempDir );
            //$options->set( 'defaultFont', 'Gobold Regular' /*'Courier'*/); 
            $options->set( 'isHtml5ParserEnabled', true);

            // instantiate and use the dompdf class
            $dompdf = new \Dompdf\Dompdf($options);
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->setBasePath( $PDFROOT /* $_SERVER['DOCUMENT_ROOT'] */ );
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title> Nieuwe font</title>
    <style>
    
       @font-face {
         font-family: 'fly2';
         font-style: normal;
         font-weight: normal;
         src: url('fonts/GoboldRegular.ttf') format('truetype');
       }

       @font-face {
         font-family: 'GoboldRegular';
         font-style: normal;
         font-weight: normal;
         src: url('http://example.com/fonts/firefly.ttf') format('truetype');
       }
       
       .test1 {
          font-family: fly2;
          font-size: 25pt;
          font-weight: 900;
       }
       
       .test2 {
          font-size: 36pt;
          font-weight: 900;
          font-family: GoboldRegular;
       }
       
    </style>

  </head>
    <body>
       <div class="test1">
            The quick brown fox jump over the lazy dog<br>
            ONTWIKKELSCAN<br>
            Ontwikkelscan<br
       </div>
       <div class="test2">
            The quick brown fox jump over the lazy dog<br>
            ONTWIKKELSCAN<br>
            Ontwikkelscan<br>
      </div>
    </body>
</html>
```

**Comment by bsweeney** [comment]
First I'll summarize some relevant configuration knowledge:

- resources loaded via HTTP require the `isRemoteEnabled` option to be set to true
- resources load via filesystem must be under one of the paths specified by the `chroot` option
- filesystem resources referenced relatively determine the path based on the path of the HTML document, unless loadHtml is used then they are based on the executing PHP script
- filesystem resources referenced absolutely (beginning with a "/") are read from the root of the filesystem
- the process requires read/write access to the temp directory and to the font directory
- you must supply a relevant font weight when loading fonts, Dompdf is fairly strict in this regard
- Dompdf does not support CORS at this time

Your sample doesn't indicate how you are loading the HTML, so it's hard to say much about local file references. You are setting the base path and so that would prefix any relative resource references. I.e., `"fonts/GoboldRegular.ttf"` translates to `$PDFROOT . "fonts/GoboldRegular.ttf"`.

Your remote reference in the sample (`http://example.com/fonts/firefly.ttf`) is invalid, but presumably that's not the actual URL you are trying. Note that if the URL is HTTP but redirects automatically to HTTPS that the current release of Dompdf does not follow redirects.

Those two things out of the way ... where the font handling will definitely fail to find a match is on the font weight. Your `@font-face` declarations specify that the imported font has normal weight. Meanwhile the text is styled with a weight of 900. As a result Dompdf will not find a match. The [font matching algorithm](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-matching-algorithm) defined in the W3C spec is a bit more advanced than what Dompdf provides right now so your font properties (style, weight) must match that of the text.

**Comment by EvEggelen** [comment]
Thanks for the quick response. Indeed the mismatch in font-weight was the cause. Browsers can handle loading a font and changing the weight afterwards. So I assumed this was legal and also supported by dompdf. 

I retrieved the webloading code from the wiki of dompdf. The example does not work ( anymore ) due to CORS. So maybe a warning regarding not supporting CORS could be helpful for people like me. https://github.com/dompdf/dompdf/wiki/UnicodeHowTo

**Comment by bsweeney** [comment]
Can you explain more about the problem caused by CORS? That's typically implemented by user-facing clients (web browsers) so I wouldn't expect it to cause issues for fetching resources via PHP. Unless your target server requires requests to include CORS headers, which I haven't seen.

**Comment by EvEggelen** [comment]
First, I cannot express enough appreciation for all the work that you have done on dompdf and the support around it.

I noticed that by default most servers do NOT want to serve fonts to other sites (also my own with the default webhoster settings). At least this is what I understood ( not an expert ). You need to change the configuration to make this work ( or at least change the default in my case). The example on the wiki refers to a font url that fails due to CORS. At least the example did also not work with a local html file loaded in chrome. In chrome developer tools I could see that it was due to the CORS policy. 

So my point is that 2 options are offered on the wiki. The load_font.php method does typically not work with hosting accounts ( no ssh access ). I assumed the other example url worked before, but does not anymore. So maybe good to indicate that.  Or add an option to add fonts from the file system ( this is what I am doing now). Then at least you have an example that works out of the box.

Dompdf is really great, but for a beginner like me it sometimes it is hard to figure out if you made a mistake, it is a limitation of dompdf or is just not supported yet. In my case I received an html file ( that works in browsers) with the request to make an pdf out of it. Also in the case of the fonts, I do not really getting an warning or so in the logging.

Anyway, I make a wrapper around load_font.php to be used on hosting accounts ( without ssh access).  Not really safe of course if you leave it on the server after loading the fonts, but are you interested in that adding that here at github ( https://github.com/dompdf/utils ) ?

**Comment by bsweeney** [comment]
FYI the example URL in the wiki is just that, an example. It's not meant to be taken literally as a URL you can use to test font loading. The example.com domain is a system hosted by the W3C that can be used for example links. You can see that by going to the URL directly: http://example.com/fonts/firefly.ttf

If you want an HTML document with reference to actual font to test out font loading try the following from the [debug helper](https://eclecticgeek.com/dompdf/debug.php):

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
<link href='http://fonts.googleapis.com/css?family=Give+You+Glory&v2' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Wallpoet&v2' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister&v2' rel='stylesheet' type='text/css'>
<style type="text/css">
	body {
		font-family: sans-serif;
	}
	p {
		font-size: 2em;
		background: #eee;
		padding: 1em;
	}
	
	h2 {
		color: #999;
	}
</style>
</head>
<body>

<h2>Give You Glory</h2>
<p style="font-family: 'Give You Glory', sans-serif;">
  Grumpy wizards make toxic brew for the evil Queen and Jack
</p>

<h2>Wallpoet</h2>
<p style="font-family: 'Wallpoet', sans-serif;">
  Grumpy wizards make toxic brew for the evil Queen and Jack
</p>

<h2>Love Ya Like A Sister</h2>
<p style="font-family: 'Love Ya Like A Sister', sans-serif;">
  Grumpy wizards make toxic brew for the evil Queen and Jack
</p>

</body>
</html>
```

As for CORS, that's a browser technology. So while it may impact what resources can be retrieved in Chrome it will not impact Dompdf.

As for logging, you can try to enable additional logging per the [wiki page on debugging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf).
