### ISSUE TITLE
imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile PHP 8.2.1

### ISSUE THREAD

**Issue by swbittib** [dompdf/dompdf#3295]
Hello, we have this error:

_**imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile**_

on PHP 8.2.1 and DomPdf 2.0.3

Thanks

_Originally posted by @swbittib in https://github.com/dompdf/dompdf/issues/2718#issuecomment-1755423009_

**Comment by bsweeney** [comment]
Warnings should be suppressed since 1.2.0. What is the full error provided (looking fro the line number)? And do you have a sample image?

**Comment by bsweeney** [comment]
The profile might have been stripped out when generating that Base64 version because I'm not seeing the warning when attempting to render it on 1.1.1? I do still see the warning on 1.1.1 with the image cited in the original issue. I do not see any warnings on 2.0.3.

Are you using Dompdf within another framework? It's possible that framework is capturing and reporting warnings separately. If so you'll want to tweak the reporting configuration for your framework. Suppressing errors only works if the error handler honors the suppression.
