### ISSUE TITLE
CSS inherit issue with tables

### ISSUE THREAD

**Issue by Nuranto** [dompdf/dompdf#3333]
Hi,

`font-size: inherit;` is not processed for tables (maybe for other tags too, I did not checked).

**Steps to reproduce :** 

CSS : 
```
table, tr, td, th {
    font-size: inherit;
}
```
HTML : 
```
<p><span style="font-size: 18pt;">Text at 18pt</span></p>
        <p><span style="font-size: 18pt;">&nbsp; <table style="border-collapse: collapse; width: 100%;;" border="1">
            <thead>
                <tr>
                    <th style="width: 33.3333%;height:19px;">Date</th>
                    <th style="width: 33.3333%;height:19px;">Type</th>
                    <th style="width: 33.3333%;height:19px;">Montant</th>
                </tr>
            </thead>
            <tbody>
                        <tr>
                <td style="width: 33.3333%;height:19px;">16/11/2023</td>
                <td style="width: 33.3333%;height:19px;">Autre</td>
                <td style="width: 33.3333%;height:19px;">156,00 €</td>
            </tr>
                <tr>
                <td style="width: 33.3333%;height:19px;">16/11/2023</td>
                <td style="width: 33.3333%;height:19px;">Autre</td>
                <td style="width: 33.3333%;height:19px;">140,00 €</td>
            </tr>
                       
            </tbody>
        </table>
</span></p>
```

**HTML Result (Expected PDF Result) :**

Both text and table are displayed with same font-size (18)
![Capture d’écran 2023-11-16 à 19 20 17](https://github.com/dompdf/dompdf/assets/1633463/df6fd106-23af-4287-902d-abf2b65f5528)

**Actual PDF Result:** 

Text is displayed with correct font-size (18), but table is not.
![Capture d’écran 2023-11-16 à 19 20 34](https://github.com/dompdf/dompdf/assets/1633463/e262c117-beb7-4951-9eb9-a8c2cd30147f)

**Additional information**

The HTML is generated via tinymce using variable (placeholder/shorcode). So I cannot change the HTML to set the font size on `table` or `td`.

**Comment by bsweeney** [comment]
What browser renders your HTML like that? When I tested, I get the same results in both the browser and Dompdf.

The reason you're getting these results is that the HTML itself is syntactically invalid. The table element is set as a child of a span element. The [span element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-span-element) should only contain [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2), of which tables are not.

What this means is that the following:

```
<p><span><table>...</table></span></p>
```

is fixed up by the HTML5 parser to the following:

```
<p><span></span></p><table>...</table>
```

You can see the same in a web browser if you inspect the document after render.

Because the HTML document is run through the HTML5 parser prior to applying styling (e.g., `span > table { display: inline-table; }` there's not really a work-around you can apply solely in the HTML document.

You _can_ provide your own DOMDocument instead of using Dompdf's. Instead of calling `$dompdf->loadHtml(...)` you would generate your own DOMDocument and call `$dompdf->loadDom(...)`:

```
$doc = new DOMDocument("1.0", "UTF-8");
$doc->preserveWhiteSpace = true;
$doc->loadHTMLFile(...);
$doc->encoding = "UTF-8";
$dompdf->loadDom($doc);
```

That does render your document as expected, though really you should see if you can fix up whatever tinymce is doing so that it doesn't generates such poorly formed HTML. Main reason I would focus on fixing up the source is that while Dompdf appears to be able to parse this particular HTML, there are likely some invalid HTML documents that would Dompdf would be unable to process (and likely throw an exception).

**Comment by Nuranto** [comment]
Chrome does, but you're right about invalid HTML... I'll work on that indeed.
