### ISSUE TITLE
file_exists(): open_basedir restriction in effect. File(\/.ufm) is not within the allowed path(s)

### ISSUE THREAD

**Issue by Farooq-Khan** [dompdf/dompdf#3356]
Hello everyone 
Hope you guys are doing well. I am using dompdf in my laravel project to generate pdf documents and i also want to show page number like 1 / 2. So i have enable_php : true as well. But when i enable php it gives me error "file_exists(): open_basedir restriction in effect. File(\/.ufm) is not within the allowed path(s)" on server. Can someone please help what i am doing wrong.

Thank you

**Comment by bsweeney** [comment]
php is restricting where you can read/write files (ref [open_basedir documentation](https://www.php.net/manual/en/ini.core.php#ini.open-basedir)). However, the real issue appears to be an incorrectly parsed font because dompdf is trying to access `/.ufm` which isn't a real file. You should check your open_basedir configuration and ensure that any configurable paths for Dompdf (e.g. tempDir, fontDir) are under that directory. You will also probably need to reset Dompdf so that the installed fonts are recorded correctly.
