### ISSUE TITLE
There is a misspelling in the Khmer text output.

### ISSUE THREAD

**Issue by kongheng-glean** [dompdf/dompdf#3367]
My PDF file displays correctly with the [Kantumruy Pro](https://fonts.google.com/specimen/Kantumruy+Pro?query=kantumruy+) font style applied, however the spelling is incorrect.

The text is supposed to show: 
### វិក្កយបត្រអាករ

but it rendered like the screenshot below.

> Screenshot

![misspelling](https://github.com/dompdf/dompdf/assets/123917527/b11bae97-964e-4a33-91b2-334fbcbb8697)

**Comment by bsweeney** [comment]
The issue is that Dompdf does not currently support complex text layout, primarily shaping in this case. You would need to pre-process your text so that shaping is performed before rendering by Dompdf. I do not know of any programs at this time that will perform this operation for Khmer text.

Watch #2900 and #2619 for updates.
