### ISSUE TITLE
3.0 does not apply styles on thead/tbody/tfoot

### ISSUE THREAD

**Issue by curry684** [dompdf/dompdf#3456]
In 2.0 the following design had lines between the elements, in 3.0 not a single one. It doesn't matter whether the table sections are explicit or implicit, they are no longer styled at all it seems.
```html
        <table class="invoice">
            <tr><th>Omschrijving</th><th>Bedrag</th></tr>
        </table>
        <div class="lines">
            <table>
                <tbody>
                  <tr><td>1</td><td>2</td></tr>
                </tbody>
            </table>
        </div>
        <table class="totals">
            <tbody>
            <tr><td>Subtotaal</td><td>€ 42,-</td></tr>
                  <tr><td>1</td><td>2</td></tr>
            </tbody>
            <tfoot>
            <tr><td>Totaal te voldoen</td><td>€ 42,-</td></tr>
            </tfoot>
        </table>
```
```css
thead, tbody {
  border-top: 1px solid black;
}
```

**Comment by curry684** [comment]
For completion's sake: they are most certainly meant to be styled: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

![image](https://github.com/dompdf/dompdf/assets/1455673/0bb459bf-7cd2-4520-bb4d-fa9ce3a9230f)

**Comment by bsweeney** [comment]
I think this was introduced when attempting to address rendering of _separated_ table borders (`border-collapse: separate;`) (#3304). It looks like we neglected to vary the rendering logic based on the border style.

**Comment by curry684** [comment]
Heh, reading the comments I'm pretty sure you're right: https://github.com/dompdf/dompdf/pull/3304/files#diff-db236d5900820d6b99db1cfa8422e28ebdf4ada428ba231aa6d5cb455fb6dfcaL30

**Comment by Mellthas** [comment]
The change works as intended: When using the separated border model (`border-collapse: separate`, which is the default), borders for row groups are not drawn anymore; this is now consistent with the spec and other browsers.

> The `_render_border` call flat out disappeared there.

This is because borders never need to be drawn for row groups specifically. The are ignored in the separated model, and implicitly handled during table-cell rendering in the collapsed model.

Here is a full sample document based on your initial sample. This should make the difference clearer:

```html
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
<style>
table {
    margin-bottom: 10px;
    border: 1px solid black;
}

thead, tbody, tfoot {
    border-top: 1px solid black;
}

.collapse {
    border-collapse: collapse;
}
</style>
</head>

<body>
    <table class="separate">
        <tbody>
        <tr><td>Subtotaal</td><td>€ 42,-</td></tr>
        <tr><td>1</td><td>2</td></tr>
        </tbody>
        <tfoot>
        <tr><td>Totaal te voldoen</td><td>€ 42,-</td></tr>
        </tfoot>
    </table>
    <table class="collapse">
        <tbody>
        <tr><td>Subtotaal</td><td>€ 42,-</td></tr>
        <tr><td>1</td><td>2</td></tr>
        </tbody>
        <tfoot>
        <tr><td>Totaal te voldoen</td><td>€ 42,-</td></tr>
        </tfoot>
    </table>
</body>

</html>
```

**Comment by bsweeney** [comment]
Looks like I misspoke 😞. I had not yet looked into the problem so was intending to indicate that if an issue was introduced that would have been where it occurred.

@curry684 if you have a full example, we can provide better guidance. I should note that the border styling has "top" instead of a color as the last part which, if that's what you have in your code, would be a problem. I replaced that with "black" and it appears to render as expected.

**Comment by curry684** [comment]
Thanks for the responses guys, I've got a pretty easy sample case (local test project which I can easily swap between 2 and 3) so I'll investigate in the coming days.

**Comment by curry684** [comment]
Ok, did some more digging, and it would appear that indeed 2.0 is wrong and 3.0 is right, see Codepen:

![image](https://github.com/dompdf/dompdf/assets/1455673/61d80899-2108-446a-863b-1f9a701af138)

I've patched my templates and they're now "similar enough". We can close the issue as working as intended now, but leaving it open as I would recommend adding this to the upgrade guide as a breaking change even though it was wrong to begin with.

**Comment by bsweeney** [comment]
I wouldn't consider it a breaking change since it wasn't an intentional feature.

Adding a detailed list of rendering updates is probably a good idea. I'll see what I can put together.

**Comment by curry684** [comment]
FIxing something that was reliably broken is still a breaking change to previous behavior  😉   but yes, that's just semantics, and it's ok in a major, so a 'rendering changes/gotchas' list is fine  👍
