### ISSUE TITLE
What is the purpose of PDFLib?

### ISSUE THREAD

**Issue by bergstar** [dompdf/dompdf#3465]
Is it necesery to have the commercial license? Or is it possible to use PDFLib Lite?

Since its part of options it looks like it is necessery also since support for PDFLib 10.x has been improved.

But it is unclear what the point of integration is.

**Comment by bsweeney** [comment]
Dompdf was designed to be agnostic with regard to the output generation back end. The project is mostly built around Cpdf rendering library. PDFLib support was historically included to provide improved rendering performance. Dompdf can also export to PNG via GD.

While we support usage of PDFLib, it is not a requirement. The bundled Cpdf library is used by default.

If you want to use PDFLib, you have to supply a license otherwise your PDFs will render with the PDFLib trial watermark. To enable you would change the backend via options. There are a few ways to do that but one is to pass the option in during instantiation, e.g. `$dompdf = new Dompdf(['pdfBackend' => 'PDFLib']);`
