### ISSUE TITLE
background-image: url("data:image/png,base64, ...") doesn't work anymore in Dompdf 3.0.0

### ISSUE THREAD

**Issue by P-ZeN** [dompdf/dompdf#3482]
Hi,

I recently upgraded DomPdf to v3.0.0 in two projects (to use new css var capabilty wich works great, bravo !) and now the base 64 encoded in my css files are no longer rendered anymore.
The exact same code used to work flawlessly from v0.0.7 to v2.0.8.

In the debug dom_pdf.html, I find : 

```
(novalue charset=binary)(novalue base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAEJJREFUeNpiYGBg+A/ECQyEQQJULZyRQITiBJwC+BTjkyBoO7KCBGL9B1OIVTETA4WAJCeR5GmSgpXkiCMpaQAEGACcKyQtYAq11wAAAABJRU5ErkJggg=="))(background-repeat:=no-repeat)(background-position:=top left)_parse_properties]#input[type="radio"]:checked+span#section]_parse_sections] [_parse_sections[section[_parse_properties(display:=inline-block)(position:=relative)_parse_properties]#.zqpm_range_input_box#section]_parse_sections] [_parse_sections[section[_parse_properties(content:="")(position:=absolute)(box-sizing:=border-box)(top:=1px)(width:=12px)(height:=12px)(background-image:=url("data:image/png)
[_image
Array
(
    [0] => file://
    [1] => 
    [2] => ./
    [3] => none
    [protocol] => file://
    [host] => 
    [path] => ./
    [file] => none
    [resource] => 
)


none
```

=> why "novalue" in the beginning ?

and : 

```
  specificity 0x30000202
  [
    parent_font_size:12;
    Props [
      specified [
        background_image: url("data:image/png;
        background_repeat: no-repeat;
        background_position: top left;
      ]
      computed [
        background_image: none;
        background_repeat: no-repeat;
        background_position: Array
(
    [0] => 0
    [1] => 0
)
;
```
The statement "background_image" is broken with closing quote and parenthesis lacking...

I managed to circumvent easily with urls to actuals files, but I thought you might be interested.
Anyway, DomPdf is an awsome project!
Regards,

**Comment by bsweeney** [comment]
That does appear to be the case. We did make some changes to stylesheet parsing and must have missed this during testing. I'll try to take a look soon.

**Comment by bsweeney** [comment]
Looks like the RegEx we're using works, so long as the data-uri isn't too big. I think we can do better, at worst going back to what we had before.

**Comment by bsweeney** [comment]
I found a few issues to address:

1. The current logic incorrectly parses the background-image property when a base64-encoded data-uri is present. This is due to the semi-colon in the data-uri string, which is treated as a CSS property delimiter.
2. We are unable to parse an overly large data-uri in the stylesheet using current logic. This is due to limits inherent in regex.

I'm going to add some extra logic to help out with this issue, but it's really only a temporary solution because we've pushed our ability to use regex about as far as we can. Ultimately what needs to happen is for us to implement a true CSS parser (#697) instead of using regex pattern matching.
