### ISSUE TITLE
Duplicate content-length header line in Pantheon LIVE server

### ISSUE THREAD

**Issue by yihuangpx** [dompdf/dompdf#3489]
Good day,
One of our the dompdf function used in our Drupal site return duplicated header error from the nginx log.

`upstream sent duplicate header line: "Content-Length: 535348", previous value: "Content-Length: 32118" while reading response header from upstream`

The function we used is:
`$dompdf->stream("PDF-name");`
It might triggered by the stream() function in the `lib/Cpdf.php `file.

This is happened in Pantheon LIVE multi appserver.
Did anyone saw this issue before or familiar with it?

Thanks.

**Comment by bsweeney** [comment]
Dompdf does set a content-length header when you call the stream method.
- [via Cpdf](https://github.com/dompdf/dompdf/blob/v3.0.0/lib/Cpdf.php#L4720)
- [via PDFLib](https://github.com/dompdf/dompdf/blob/v3.0.0/src/Adapter/PDFLib.php#L1403)

Your application is sending a header either before or after Dompdf. When using the stream method, it's recommended to end program execution after the call since Dompdf has, at this point, set the relevant headers. If you want your application to fully manage the communication you should use the output method instead and pass the returned value to your application's handler.

**Comment by bsweeney** [comment]
No specific format. It really depends on whether or not you need your app to do anything further after it's transferred the PDF. Easiest method is to just call `exit` after sending the PDF to the user.

There may also be some application-specific means within Drupal of telling it you've sent content, not to modify the headers, and end processing but I don't use Drupal so I won't be of much help there.
