### ISSUE TITLE
PDF password protection does not work.

### ISSUE THREAD

**Issue by tarzinio** [dompdf/dompdf#3499]
I have a class that handles pdf generation for me. Everything works fine except the ability to put a password on the pdf. For testing, I skipped the classpath and typed the
```

use Dompdf\Dompdf;
$dompdf = new Dompdf();
$dompdf->setPaper('A4');
$dompdf->getCanvas()->get_cpdf()->setEncryption('a1234', 'a1234', ['print', 'modify', 'copy', 'add']);
$dompdf->loadHtml('safasf');
$dompdf->render();
$dompdf->stream();
```

but it does not work properly. the pdf downloads but is not password protected. I am using DOMPDF version 3.0.0.

**Comment by bsweeney** [comment]
Due to a quirk in the way Dompdf manages the Cpdf canvas adapter if the page size differs from the page size specified in the Options when Dompdf is initialized, then Cpdf is re-initialized on render. You can work around the issue by either:

1. set the password after the document is rendered
2. initialize Dompdf with the desired page size set to the default (e.g., `$dompdf = new Dompdf(["defaultPaperSize" => "A4"])`)

follow #3417 for updates
