### ISSUE TITLE
Dompdf does not calculate total page size when setting margin 0

### ISSUE THREAD

**Issue by vieirafb** [dompdf/dompdf#3509]
I have a ready-made HTML template that my client created and I just inject this HTML into dompdf to render. The fact that I set the HTML tag margin to 0 is because the client's template already comes with margin and padding configured. What happens is that the right margin is larger than expected, cutting off the content in version 2.0.0, which did not happen in version 0.8.6.

**Comment by bsweeney** [comment]
Do you have a sample document I can use to reproduce the issue? And what is the particular configuration you're using (page size, dpi, etc)?

**Comment by vieirafb** [comment]
> Do you have a sample document I can use to reproduce the issue? And what is the particular configuration you're using (page size, dpi, etc)?

The size is A5 and orientation is landscape, and the versions used are specifically 0.8.6 and 2.0.8.

```html
<style>
    html {
        margin: 0;
    }
</style>
<div
    style="text-align: justify; width: 100%; padding-top: 300px; padding-left: 160px; padding-right: 240px; padding-bottom: 30px; page-break-after: always;">
  <p></p>
  <div style="font-size: 21px;">A Faculdade SPRINT de Minas Gerais -<b>Faculdade SPRINT</b><span
      style="font-size: 21px;">, certifica que <strong syle="font-size: 21px;"><span style="text-transform: uppercase;"><b>Fulano de Tal</b></span></strong><span
      style="font-size: 21px;"> concluiu toda a carga horária exigida de <b>300 horas</b> no curso de </span><span
      style="font-size: 21px;text-transform: uppercase;"><span style="text-transform: uppercase;"><b>ADMINISTRAÇÃO - PHP-SELENIUM - OFICIAL.</b></span></span><span
      style="font-size: 21px;">.</span></span>
    <p></p></div>
  <div style="font-size: 21px; text-align: center; padding-top: 80px;">Cidade/ES, <strong>30 de agosto de 2024</strong>
  </div>
  <div style="text-align: center;height: 50px;"><p>Assinatura</p></div>
  <div style="text-align: center;">_______________________________________<br><b> NOME DO RESPONSÁVEL<br>TÍTULO</b>
  </div>
  <div style="position: fixed; top: 650px;right: 950px;text-align: center;">
      <img src='data:image/png;base64, ' style='width: 100px; height: 100px;'>
      <br>B1926690-3CF834AA-BAFDB66A-5E14D465
  </div>
</div>
```

**Comment by bsweeney** [comment]
First thing to note is that when you specify the width of an element it is specifying the width of the content box only. Border and padding values are separate and _increase_ the total width of the element. That is, unless you style the element with `box-sizing: border-box` in which case the width specifies the total width when taking into account content + padding + border. Unfortunately, Dompdf does not yet support the box-sizing declaration (#669).

So in your use case, when you specify that your container DIV has a width of 100% that means the content of the element be as wide as the page. When you add in padding the content area of the DIV is shifted outside the bounds of the page. You'll see the same issue if you print that HTML from a browser.

Normally you would just switch to border-box sizing, but since that's not available yet you'll need to work around current limitations. There are two work arounds that you can use with your sampmle:

1. Upgrade to Dompdf 3.0.0 or higher and subtract the padding (`width: calc(100%-400px)`). You need to use Dompdf 3.0.0 or higher because that's when support for the calc function was introduced.
2. Use `width: auto;` which also seems to work fine with your sample.

The Dompdf 0.8.6 render was not actually correct. In that release, when you specify a width of 100% it [renders the element as if you had specified a width of auto](https://github.com/dompdf/dompdf/blob/v0.8.6/src/FrameReflower/Block.php#L192).
