### ISSUE TITLE
Dompdf Error: "UnableToOpenConfigureFile `coder.xml'" - Possible ImageMagick Configuration Issue

### ISSUE THREAD

**Issue by alexmigf** [dompdf/dompdf#3510]
We're encountering an error when using Dompdf in our plugin. The error message is as follows:

```
Exception: UnableToOpenConfigureFile `coder.xml' @ warning/configure.c/GetConfigureOptions/685

../vendor/dompdf/dompdf/lib/Cpdf.php (5723)
```

From our investigation, it appears that the issue may be related to the `coder.xml` file, which is an [ImageMagick configuration file](https://imagemagick.org/script/resources.php). We suspect that the file might be missing or there could be incorrect permissions set within the ImageMagick setup. However, we don't believe the issue is directly connected to a [recent change](https://github.com/dompdf/dompdf/pull/3185) made in Dompdf, as the "**UnableToOpenConfigureFile**" error doesn't seem to point to that.

Could you please provide guidance on how to resolve this issue? Any insights or suggestions would be greatly appreciated.

**Comment by bsweeney** [comment]
I have not seen this particular issue before and will need to do a bit of research. Probably more of a system issue, but I'll need to see if anything in the [configuration load logic](https://raw.githubusercontent.com/ImageMagick/ImageMagick/600708ca1e9122cfe61ec8afc35b5fc179be87d9/MagickCore/configure.c) provides insight.

I see you're attempting to provide [support for this issue elsewhere](https://wordpress.org/support/topic/exception-unabletoopenconfigurefile-coder-xml/). Can you find out if ImageMagick updated on the impacted system? Are the users able to switch to an earlier version of Dompdf to see if the issue is present before that change? And, of course, if they can disable the IMagick extension that should at least get things running again.

I've been considering making IMagick usage optional, recent issues are definitely pushing me in that direction.

**Comment by alexmigf** [comment]
It appears that the issue was related to a hosting service, which affected a few customers. The problem has now been resolved on their end, so we are closing this for the time being.

**Comment by bsweeney** [comment]
Appreciate the follow up. I'm still looking at making IMagick usage optional but at least this particular issue does not need to drive that decision.
