### ISSUE TITLE
[FONTs]:  custom font not work properly 

### ISSUE THREAD

**Issue by wdshahadat** [dompdf/dompdf#3518]
This plugin is very helpful for html to pdf. I have been using it for a long time. But now the custom font doesn't work properly. My typing font is Nikosh.ttf or solaiman-lipi.ttf, a Bengali font. It is very necessary to support Koranu. please help

**Comment by bsweeney** [comment]
What do you mean when you say it doesn't work properly?

**Comment by guyinpv** [comment]
My custom font stopped working as well.

I was using Anton from Google Fonts with the "@import" rule. After a recent update of dompdf, it reverted to default font.

I tried styling the font with header "link" tags to Google instead, didn't work. I tried using an "@font-face" with local referenced file, nope.

I checked the font cache and other options and everything seems correct for loading fonts. I even convert the ttf file to afm and put it in the font cache folder, it still didn't pick it up.

The implementation of dompdf is in a tool called MainWP in their Pro Reports system that generates PDFs. The font worked fine until the latest update which included a dompdf update.

It's possible a recent update introduced a bug in custom font loading?

**Comment by bsweeney** [comment]
I would need to see the actual rule you were using.

**Comment by guyinpv** [comment]
The issue has been fixed in the app that was using dompdf (MainWP Pro Reports). 

It turns out there is some kind of cache where if dompdf converts a new font one time, it will not convert it again if anything changes in the system.
In other words, if I upload a new font and it generates the cache folder with the afm files, if those afm files are deleted, it will not convert them again. To fix this, I had to re-upload my font with a new filename to get it to convert and cache as a new font file.

There were other nuances as well, as MainWP put out multiple updates trying to fix this.

For anybody who seems to be having this problem, just try renaming your font file and upload it again and see if it will convert files and work. Be sure to use the right folders for storing things, and reference the font with a local @font-face rule.

**Comment by bsweeney** [comment]
@guyinpv this is correct. Font parsing can be a lengthy operation and so once a font has been "installed" Dompdf won't re-parse it (based on the font name and/or originating URL). You don't necessarily have to rename the font to trigger a reparse. You can also remove the relevant files from the font_dir/font_cache directories as well as the entry in the installed-fonts.json file (or just remove the file entirely).

Highly recommend modifying your runtime options to set a directory for the font directories so that you can just clean them to reset the font state.

One potential change I'm considering is to make a "leave no trace" setting where generated artifacts like these do not persist across runs. It will slow down document rendering, but would prevent this particular scenario.
