### ISSUE TITLE
Cannot get footer only printing on last page with correct height

### ISSUE THREAD

**Issue by Adesin-fr** [dompdf/dompdf#3532]
Hi,

I can't manage to have my footer (showing totals) only printing on last page: 

If I set it on "footer", it will print on every page.

So I tried to put the totals in a DIV with absolute positionning.

it correctly show at the bottom of the page, but if the contents is too long, no page-break occurs and the totals are overwriting on the contents.

If I set a margin bottom on the `@page`, it will affect every page, and even the first page will have a blank space unused on the bottom.

<img width="803" alt="image" src="https://github.com/user-attachments/assets/dbb7ae8a-aaf1-48b4-b35d-74ad256480aa">

So I was expect to be able to make a `@page :last {margin-bottom : 70mm}`, but it doesn't work....

I'm pretty sure there is a way to do this ;)
Thanks

**Comment by bsweeney** [comment]
FYI, `:last` is not a pseudo-selector. And I doubt it would necessarily help anyway since adding the bottom margin would make your sample move the content to the next page, which means it would no longer be the last page, meaning there's room for it on the next-to-last page ... and on and on.

I believe the only way to accommodate this type of layout would be through callbacks. I started working through a potential solution for the very similar question in #3520, but haven't had time to finalize it. Watch that discussion for updates.

**Comment by Adesin-fr** [comment]
Thanks, I'll have a look at callbacks so ;)

**Comment by Adesin-fr** [comment]
Hi

I've gave a look quickly but didn't understand how it's supposed to work yet ;)

How am I supposed to know that there is more page to go, and there will not be enough space to print the final footer ? 
Even If I know the footer height, I suppose I must hook into the begin_frame event, but how do I know I'm printing the last row of my table ? 

Am I going a wrong way ?

**Comment by bsweeney** [comment]
Sometimes we overlook the easier solution when focusing on the specific problem. I am smh at how easy that was to resolve.
