### ISSUE TITLE
Hebrew Characters don't work!

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#426]
_Original author: guido.ro...@gmail.com (February 07, 2012 19:19:33)_

<b>What steps will reproduce the problem?</b>
I tried create a PDF with UTF-8 characters.

<b>What is the expected output? What do you see instead?</b>
I get a '?' character, not characters in hebrew.

<b>What version of dompdf are you using? What version of PHP? On what</b>
<b>operating system?</b>
DOMPDF 0.6.0 beta2
PHP 5.3.5-1ubuntu7.2 with Suhosin-Patch (cli) (built: May  2 2011 23:00:17) 
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

<b>Please provide the HTML source code you want to convert, or any additional</b>
<b>information.</b>

HTML code
&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.1//EN&quot; &quot;http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd&quot;&gt;
&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; dir=&quot;rtl&quot;&gt;
    &lt;head&gt;
            &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;
    &lt;/head&gt;
    &lt;body&gt;
                שלום בעולם הזה הוא מבחן.
    &lt;/body&gt;
&lt;/html&gt;

PHP code
$dompdf = new DOMPDF();
$dompdf-&gt;load_html($html, 'UTF-8');
$dompdf-&gt;render();
$pdfoutput = $dompdf-&gt;output();
$filename = sfConfig::get('sf_web_dir') . '/pdf/report_'.time().'_contract.pdf';
$fp = fopen($filename, &quot;a&quot;);
fwrite($fp, $pdfoutput);
fclose($fp); 

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=420_

**Comment by rajesh0231** [comment]
Hi 

I am using dompdf library for print of my data, i am facing one issue w.r.t wrapping of text .
i.e i am display content in div with image and followed by content , image is floated to right side the text is on left side with word-wrap:break-word property.

the issue is that if i have a continuous line of text without any white space ex. URL's or any string word-wrap property doesnt work for same.

Please suggest me the best way to handle this issue. plz ref attach pdf file

Thanks
Rajesh
[test.pdf](https://github.com/dompdf/dompdf/files/2444991/test.pdf)

**Comment by bsweeney** [comment]
@rajesh0231 Which version of Dompdf are you using? When I tested with 0.8.x the text flows below the image before wrapping.

If you're using a recent version please open a new issue or post to the support forum. Be sure to include sample HTML+CSS that exhibits the issue.
