### ISSUE TITLE
Missing files in "classes" folder?

### ISSUE THREAD

**Issue by calvyno** [dompdf/dompdf#636]
Hello,

This was my first time trying to play around with dompdf.  I had everything set up and uploaded to my site.  However when I test it, it has problems loading the dompdf files.  These are the 2 errors I get.

Warning: require_once(/home/content/c/a/l/test/html/gdppv/dompdf/lib/php-font-lib/classes/font.cls.php) [function.require-once]: failed to open stream: No such file or directory in /home/content/c/a/l/test/html/test/dompdf/dompdf_config.inc.php on line 335

Fatal error: require_once() [function.require]: Failed opening required '/home/content/c/a/l/test/html/gdppv/dompdf/lib/php-font-lib/classes/font.cls.php' (include_path='.:/usr/local/php5/lib/php') in /home/content/c/a/l/test/html/gdppv/dompdf/dompdf_config.inc.php on line 335

I looked in the classes folder and there were no such files.  Where are these files?  Am I doing something wrong?

Thanks!

**Comment by arsendovlatyan** [comment]
Hello Guys. 
bsweeney, You advise developers to use composer to get the library. I did so, but, after composer download, I can see that php-font-lib folder is empty.It is located under vendor/phenx. Can You please update the composer.json file in the repo so, that it place it in the right place, or instead of it, update config file so that it require that lib from the correct location. (dompdf => 0.6.1, phenx => 0.2.2)

Thank You

**Comment by bsweeney** [comment]
Both libraries are in the expected location since Composer takes care of library management, not dompf. You should read the Composer [quick-start guide](https://github.com/dompdf/dompdf/wiki/DOMPDF-and-Composer-Quick-start-guide) in the wiki.

In brief, use composer's autoloader and disable dompdf's by setting `DOMPDF_ENABLE_AUTOLOAD` to false. You will still need to include dompdf_config.inc.php.

**Comment by arsendovlatyan** [comment]
Hello bsweeney.

Thank's for the quick response.

In my project I use composer update to get all the required libraries (including dompdf).
First of all, i'm beginning working doing "composer update". Everything works fine, it get dompdf library, I can use it to create nice pdf's (setting "DOMPDF_ENABLE_AUTOLOAD" to false).

But what if i want to include my fonts into the library?

As I understand correctly I have to navigat to the dompdf folder (http://example.com/vendor/dompdf/www) and I have to see the dompdf intro page, where I can add my fonts manualy. I can't do so, because I have and error saying that php-font-lib/classes/font.php is missed. Instead of this, all the required classess to be included in the dompdf/lib/php-font-lib folder, they are included in the vendor/phenx folder and if I open the config file, I can see that dompdf requires that classes from the vendor/dompdf/lib/php-font-lib folder and it can't work.

So my question is the following.

Why that lib classes are located in the wrong location?

**Comment by getmanzooronline** [comment]
This answer worked for me.
http://stackoverflow.com/a/24505929/1357033

**Comment by arsendovlatyan** [comment]
getmanzooronline, you are write, thank you. But It works, if you manually put the lib classes in the mentioned folder. But this is not the right solution if You use composer to install the library.

**Comment by bsweeney** [comment]
Again, the lib classes are loaded in the correct location. That's how things work with Composer, it handles dependencies (placing libraries in the vendor directory) and all you have to do is load the composer autoload script.

The issue appears to be that end-to-end testing was not done for the 0.6.x release and so Composer support seems to work with the dompdf class, but the extras apparently have some issues. I haven't personally tested with Composer so I will spend more time with it for a future release. Your best bet may be to use the CSS `@font-face` rule to load your fonts. If you're trying to use the extras (e.g. font loader) you'll need to modify the files so that whenever dompdf_config.inc.php is included so is the Composer autoload script.
