### ISSUE TITLE
CSS - Overflow Hidden

### ISSUE THREAD

**Issue by craigwillis85** [dompdf/dompdf#644]
Hi

I'm trying to use the `overflow:hidden` with some HTML that I'd like to output as a PDF.

The HTML looks like: http://jsfiddle.net/Kewmx/

You can see the expected output, but in my PDF, the image of the flowers shows the full image and the overflow doesn't seem to be functioning.

Can someone help explain what I'm doing wrong?

Thanks

**Comment by helgator** [comment]
Still a issue in 0.8.3. putting a div with overflow:hidden into a table cell cuts off the div but the cell still expands as if the overflow is not hidden in the generated pdf.

**Comment by helgator** [comment]
BTW: word-break is also not a solution because not supported in dompdf.

**Comment by bsweeney** [comment]
`word-break` is not, but we do support `word-wrap: break-word;` which is an alias of `overflow-wrap: break-word;` ([ref](https://www.w3.org/TR/css-text-3/#overflow-wrap-property)).

This doesn't work when applied directly to a table cell, but if you wrap your content in a div with a specified width it will break the word (this was previously reported in #1017). So you would utilize it like this:

```
<table>
  <tr>
    <td>
      <div style="width: 100px; word-wrap: break-word;">
        averylongstringoftextthatismorethanthespecifiedwidthofthediv
      </div>
    </td>
  <tr>
</table>
```

**Comment by helgator** [comment]
Thanks for the quick response. Your approach works. I tried 

`white-space: nowrap; overflow: hidden; text-overflow: ellipsis;`

on the inner div which does not work and exapands the table cell.

**Comment by helgator** [comment]
Just discovered that your approach only works on the surface. When you select the text in the container underneath it reveals the over flowing text. At the same time it seams to alter the line height which is why bigger in the generated PDF than in the HTML view: 
![1](https://user-images.githubusercontent.com/760995/53141532-c51bb180-3590-11e9-9d59-90e2f3ec0303.png)
![2](https://user-images.githubusercontent.com/760995/53141530-c4831b00-3590-11e9-8bb3-c97856fad9a7.png)

**Comment by bsweeney** [comment]
The text is rendered in full by design. Overflow text is hidden by a mask and not literally cropped to fit the designated container.

The hidden text shouldn't affect other text on the page since they are rendered separately. There are some other issues around line height that may be causing problems. But feel free to open a ticket with some sample HTML that we can use to test.

How text selection works would be a function of the PDF viewer, though certainly we could explore potential improvements to how we lay out text to prevent that particular issue. Feel free to open an enhancement request.
