### ISSUE TITLE
Devnagari words are not rendered properly

### ISSUE THREAD

**Issue by sameer-shelavale** [dompdf/dompdf#655]
सुविधा 
is rendered as
सुवधिा 

the character ि is should rendered before व , even though it is after व in the character sequence

this issue exists with all similar characters.

It makes dompdf completely unusable to use with Devnagari text.

it was reported earlier at http://code.google.com/p/dompdf/issues/detail?id=503

**Comment by jasmeetdd** [comment]
Did anyone find a solution?
Or do we have no choice but to shift to TCPDF.

**Comment by bsweeney** [comment]
Sorry, nothing yet on our end.

**Comment by rohit-brainpan** [comment]
@jasmeetdd Did you find anything?

**Comment by rohit-brainpan** [comment]
@bsweeney Can tell me what should I try? Am also facing the same issue...

**Comment by bsweeney** [comment]
I know of no workaround for this issue (unlike with Arabic text #712). I took a quick look at the issue again and there are at least two problems.

First, php-font-lib has not yet implemented support for some font features encoded in tables like GPOS and GSUB ([info on the FontForge site](https://fontforge.github.io/gposgsub.html).

You can get around that issue by using a different library that does support those features. I compared the UFM output from [php-font-lib](https://github.com/phenx/php-font-lib) to the output from [Everything Fonts](https://everythingfonts.com/ttf-to-ufm). Discounting differences in output due to implementation details, just looking at the size of the two files (17KB vs 19MB, respectively) says a lot.

So you can get around that issue by generating your UFM from another source for the time being. Since php-font-lib is used to subset, however, you'd have to embed the full-size font in the file.

Second, even with the full UFM and a non-subsetted font I believe we're missing some information from the generated PDF that would allow this to display correctly. At least based on a quick test I did, and in which the glyph mapping in the rendered PDF was completely broken (it was OK with sub-setting enabled).

The Dompdf team can look into the second issue. But the first issue would have to be a feature enhancement request to the php-font-lib project.
