### ISSUE TITLE
Images with display styling do not render after first page

### ISSUE THREAD

**Issue by ghost** [dompdf/dompdf#693]
Hello,

I made a PDF consisting of multiple pages and multiple images.
On the first page the images are displayed fine, on all the other pages images aren't displayed at all.

When i check the html file the images are displayed fine.

How could I fix that issue?

Thank you!

**Comment by joostdekeijzer** [comment]
`Frame_Factory::decorate_frame` overrides the `$style->display` property based on the nodeName and sets display to `-dompdf-image`, see https://github.com/dompdf/dompdf/blob/master/include/frame_factory.cls.php#L191 .

In `Renderer::render` the "original" `$style->display` is used, so for and image with `display:block;`, the image is not recognized as an image. See https://github.com/dompdf/dompdf/blob/master/include/renderer.cls.php#L67 and below.

I don't know if either the changes from `Frame_Factory` should be available in `Renderer` or that in `Renderer::render` equivalent code should be inserted.

**Comment by bsweeney** [comment]
@joostdekeijzer thanks for the follow up. Should help in working out a fix for the issue.

Just as an FYI, in versions of dompdf prior to 0.6.0 image elements were converted into a container element plus the image. Styling implementation is significantly different when using that type of document structure internally.

**Comment by simison** [comment]
+1, this bug still exists with 0.7.x beta versions.

**Comment by JorenRapini** [comment]
@simison Thank you, that solution worked for me.

**Comment by Makreig** [comment]
been trying to solve a different issue for a while now, but i think it might be related (and possibly the same/cause of this)...
i am able to get an error on mine:

PHP Fatal error:  Class 'Dompdf\FrameDecorator\Debug' not found in /home/makreig/Projects/fad-force-generator/vendor/dompdf/dompdf/src/FrameDecorator/Page.php on line 358

So i think its the same issue in that it's seeing the images as display: block instead of -dompdf-image.
i don't really have the option of not setting the images to block as i'm trying to convert a page into a pdf, so i've used the fix suggested by @simison. That has resolved the error, however the images haven't rendered into the pdf (just alt tags and empty space)...

PHP 5.6
