### ISSUE TITLE
Issues with list items

### ISSUE THREAD

**Issue by Ugoku** [dompdf/dompdf#708]
I started using dompdf today and I gotta say, it's doing a fine job! However, I'm running into two small issues with list items:
1. list-item numbers don't align with the text when line-height is not 100%
2. using a custom list item (instead of a bullet) gives problems for nested lists.
Attached is an image of the problems
![dompdf](https://f.cloud.github.com/assets/3470653/1067620/6ae89c88-13d5-11e3-938e-5e957bb106ed.png)

Relevant CSS and HTML:

```
body {
    font: 11pt/175% Arial, sans-serif; /* 175% seems to correspond to 150% in MS Word */
}
ul {
    list-style: none;
}
ul li:before {
    content: '- ';
    margin-left: -20px;
    margin-right: 10px;
}
```

```
<html>
<body>
    <ol>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed rutrum volutpat sagittis. Maecenas porttitor fermentum tristique. Vivamus nisl dui, porttitor eu lacinia et, pretium faucibus sapien.
        <li>Duis facilisis arcu vel nisi posuere commodo.<ul>
            <li>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut nec sapien nec purus euismod suscipit. Sed tempus velit id mi convallis, et laoreet orci placerat
            <li>Suspendisse laoreet facilisis dictum. Donec sem metus, pretium at odio non, fringilla commodo felis.
        </ul>
    </ol>
</body>
</html>
```

If more info is needed, I'd be happy to help :)

**Comment by bsweeney** [comment]
Looks like the second issue may have been addressed.

But still seeing problems for the first issue.

**Comment by sdkcarlos** [comment]
Using the mentioned CSS snippet doesn't work for me:

```css
ul > li:before {
  content: '-';
}

ul , ul > li {
    list-style: none;
}
```
And with a very simple markup:

```html
<ul>
    <li>Text</li>
    <li>Text</li>
    <li>Text</li>
</ul>

<ul>
    <li>Text</li>
    <li>Text</li>
    <li>Text</li>
</ul>
```

In some `ul `elements appear normally, but in others the "-" is appearing twice.

**Comment by sdkcarlos** [comment]
As I needed to fix this quick and can't modify the DOMPdf library by myself, solved the issue by simply using an image in the `list-style-image` attribute on the `ul` element instead of the content property of the `li` elements:

```css
ul {
    list-style-image: url('../path-to-images/pdf_bullet_list.png');
    margin: 0;
}
```

Pitifully the dimensions of the image can't be modified given the list-style-image attribute, so you may need to modify your image and adjust the padding or location with transparent spaces. I used the following bullet as image:

![pdf_bullet_list](https://user-images.githubusercontent.com/11634719/34197653-bdb1bd74-e567-11e7-8aac-b94c97e094cc.png)

I hope it may help others that are in a hurry as well until this issue is fixed.

**Comment by TravisHi** [comment]
I'm not sure if this will provide any more insight, but I was able to get my <ol> lists on the same level by messing with the font size and line height of my <p> and <ol> tags in my CSS. Note: the font family for the p and ol tags had to be the same.
`  p {
      line-height: 16px;
      font-size: 14px;
   }
  
  ol {
      line-height: 14px;
      font-size: 14px;
  }
`

HTML for reference:
`
<ol type="1">
  <li><p>content</p></li>
  ect.
</ol>
`

**Comment by dmitrimag** [comment]
Thanks to @TravisHi for "p-in-li"-idea. Modified it for my `<ul>` case with offset.

HTML
```
<ul>
    <li><p>Text 1</p></li>
    <li><p>Text 2</p></li>
</ul>
```
CSS
```
ul {
    font-size: 15px;
    line-height: 1;
}
p {
    margin: 0;
    position: relative;
    top: -5px;
}
```

**Comment by mohkoma** [comment]
How I solve it ☝️

```
ol {
    line-height: 1;
    position: relative;
}
ol > li > p {
    margin-top: 0;
    position: relative;
    top: 7px;
}
```

**Comment by Mellthas** [comment]
List markers are not run through the logic for vertical alignment, which is responsible for the text not being rendered exactly in the middle of the line. #2658 now applies vertical alignment to list markers, so that they are properly aligned with the text, regardless of line height. Improving vertical alignment in itself is another issue that can now be addressed independently.
