### ISSUE TITLE
margin top content for next page

### ISSUE THREAD

**Issue by mrtuvn** [dompdf/dompdf#783]
I setup for show header and footer on all page . But problem is that content break from before page overlap on header page . Can anyone help me fix this issue
Thanks all

**Comment by diguinhorocks** [comment]
what i supposed to do if the entire content of pdf is coming from database?

**Comment by bsweeney** [comment]
@diguinhorocks same thing. The source of the content doesn't matter since all you're doing is feeding Dompdf an HTML document. You might want to go ahead and open a new ticket with more details or (more appropriate I think) start a new thread in the [discussion group](http://groups.google.com/group/dompdf).
