### ISSUE TITLE
empty dir php-font-lib

### ISSUE THREAD

**Issue by permanyer** [dompdf/dompdf#901]
ISSUE:
I downloaded dompdf zip and it did not work. 

CAUSE:
That was because php-font-lib folder was empty. (see file dompdf_config.inc.php line 332:  require_once(DOMPDF_LIB_DIR . "/php-font-lib/classes/Font.php");)

WORKAROUND:
So I went to https://github.com/PhenX/php-font-lib and downloaded the project, then extracted its src/Fontlib folder to my empty php-font-lib directory and renamed it to 'classes'.
Now it works

**Comment by bsweeney** [comment]
This is a commonly-reported issue. You downloaded a ZIP of the code repository instead of the the actual release. I you visit the [releases page](http://github.com/dompdf/dompdf/releases) you want to click on the link that indicates the version (e.g. dompdf-0.6.1.zip) instead of the link that says "source code."
