### ISSUE TITLE
ul in ol

### ISSUE THREAD

**Issue by Cipa** [dompdf/dompdf#917]
Hi,

Using ul in ol doesn't output properly

Code is
```
<ol>
<li>Test</li>
<ul>
<li>Test</li>
<li>Test</li>
<li>Test</li>
</ul>
<li>Test</li>
<li>Test</li>
</ol>
```

Should look like
![screen shot 2015-03-17 at 10 49 22 am](https://cloud.githubusercontent.com/assets/293377/6689873/5e5098c2-cc93-11e4-8f04-bb1c7a95f7ed.png)

Looks like
![screen shot 2015-03-17 at 10 49 12 am](https://cloud.githubusercontent.com/assets/293377/6689872/5e50551a-cc93-11e4-8bf3-2ad8b0c96b31.png)

**Comment by DavidBruchmann** [comment]
There was recently a change with ul/ol (see mailinglist or on github).
Did you use the most recent code-base?

**Comment by Cipa** [comment]
I think I used the latest stable. Will upgrade and try again

**Comment by Cipa** [comment]
So develop doesn't work for php 5.2, what would be the latest php 5.2 available version
Thank you

**Comment by Cipa** [comment]
So the problem is not fixed on master and I can't use develop, can you  show me what can be changed in master to make the lists work?

**Comment by DavidBruchmann** [comment]
Sorry, don't use 5.2, so I don't know.

Easy way: download xampp as zip / 7zip.
Stop your web-server and just click on apache_start.bat (in windows) or
ressembling in another system to start apache with the choosen PHP-Version.
Your default database can still run and be used by that apache/php
combination.

**Comment by Cipa** [comment]
I am not local, this is a server I can't touch/update :(

**Comment by DavidBruchmann** [comment]
check this:

https://github.com/dompdf/dompdf/issues/403#issuecomment-62094435

regrettable the message I remembered belongs to another framework.
Perhaps the link above solves a bit more, is already a bit older and could
be part of the current version.


On Tue, Mar 17, 2015 at 10:07 PM, David Bruchmann <david.bruchmann@gmail.com
> wrote:

> Sorry, don't use 5.2, so I don't know.
>
> Easy way: download xampp as zip / 7zip.
> Stop your web-server and just click on apache_start.bat (in windows) or
> ressembling in another system to start apache with the choosen PHP-Version.
> Your default database can still run and be used by that apache/php
> combination.
>

**Comment by bsweeney** [comment]
Which release are you using? 0.6.1 should still be compatible with PHP 5.2. The next release (what's in the develop branch definitely will not be). I'm not seeing the same issue, but I don't have PHP 5.2 (though I can set it up if need be for testing).

There could be some other code messing things up as well. Can you reproduce the error using only that HTML?

Another recommendation, get on your host. PHP 5.2 is seriously out of date at this point--it hasn't been updated since 2011.

**Comment by Cipa** [comment]
Thanks

**Comment by bsweeney** [comment]
If you continue to have problems feel free to follow up here.

**Comment by jimmy0699** [comment]
still occurs in `dompdf/dompdf`: `^2.0.1`. and `php 8.1.12`

**Comment by bsweeney** [comment]
This was working for a while, but broke again with 2.0.0 ... for a valid reason. The issue is that the syntax is invalid and the HTML5 parser _attempts_ to fix the syntax prior to rendering. Though I think it's fair to say the HTML5 parser doesn't do a great job fixing the document in this particular case.

A syntactically correct structure would be:

```
<ol>
  <li>Test</li>
  <li>
    <ul>
      <li>Test</li>
      <li>Test</li>
      <li>Test</li>
    </ul>
  </li>
  <li>Test</li>
  <li>Test</li>
</ol>
```

But of course this produces an undesirable result, with the nested list preceded by a bullet for the containing LI element. To work around the rendering issue of the syntactically correct version you can style the LI containing the nested list so that it doesn't have a bullet:

```
<ol>
  <li>Test</li>
  <li style="list-style-type: none;">
    <ul>
      <li>Test</li>
      <li>Test</li>
      <li>Test</li>
    </ul>
  </li>
  <li>Test</li>
  <li>Test</li>
</ol>
```

Another option would be to construct your own DOM directly and use loadDom instead of loadHtml. Doing that would bypass the HTML5 parser.

A potential long-term solution would be to update to Dompdf to support the `:has` pseudo-class. Though styling for that would still be challenging since you would need to vary it based on whether or not there is other content within the LI (besides the nested list). There is no way, even with the more recent selector options, to select an element that contains only a nested list and nothing else.

So, all that to say I don't have a "good" solution at present. Just a syntactically valid one.

**Comment by jimmy0699** [comment]
Thanks for quick response, I work around this in this way:
```
<ol>
  <li>Test</li>
    <ol style="list-style-type: circle;">
      <li>Test</li>
      <li>Test</li>
      <li>Test</li>
  </ol>
  <li>Test</li>
  <li>Test</li>
</ol>

```

**Comment by Mellthas** [comment]
You can simply move the `ul` into the preceding `li`:

```html
<ol>
  <li>Test
    <ul>
      <li>Test</li>
      <li>Test</li>
      <li>Test</li>
    </ul>
  </li>
  <li>Test</li>
  <li>Test</li>
</ol>
```

That’s the usual (and syntactically valid) way of nesting lists, as far as I know: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul#nesting_a_list
