### ISSUE TITLE
I Got Logo On Last Page Only

### ISSUE THREAD

**Issue by ksvplnarendra** [dompdf/dompdf#947]
Hi,
I got my logo on last page only, Please check my code.

```php
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();

$canvas = $dompdf->get_canvas();
$header = $canvas->open_object();
$font = Font_Metrics::get_font("helvetica", "bold");
$image = SITEPATH."images/ef-logo.png";
$canvas->image($image,png, 20, 125, 50, 25);
$canvas->page_text(490, 25, "EF No.".$filename, $font, 8, array(0, 0, 0));
$canvas->close_object();
$canvas->add_object($header, "all");
```

Thanks in advance,

**Comment by bsweeney** [comment]
Due to the way objects are added this is the expected result (see the [CPDF_Adapter](https://github.com/dompdf/dompdf/blob/v0.6.1/include/cpdf_adapter.cls.php#L290)). Until we build in a way to instantiate the PDF renderer earlier in the process you won't be able to add objects in this way.

That's not to say it can't be done. You'll have to work around the issue by using page scripts. Page scripts run on all pages after the document has rendered, thus allowing you to perform all the same actions on a page-by-page basis. It's not as efficient since it recreates the PDF elements each time, but unless you have a fairly large image it shouldn't be an issue.

```php
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();

$canvas = $dompdf->get_canvas();
$canvas->page_script('
  $font = Font_Metrics::get_font("helvetica", "bold");
  $image = "' . SITEPATH . 'images/ef-logo.png";
  $pdf->image($image, 20, 125, 50, 25);
  $pdf->text(490, 25, "EF No.".$filename, $font, 8, array(0, 0, 0));
');
```

Note the usage of `page_text()`. This method is similar to `page_script()` in how it runs, i.e. it's added to all pages after the document is rendered. What you want to use if you're adding to an object is the `text()` method.
