### ISSUE TITLE
BUG: php 5.2 incompatible due to php-font-lib

### ISSUE THREAD

**Issue by maximoguerrero** [dompdf/dompdf#998]
The requirements section says php 5.0 (5.3+ recommended). But when using php 5.2 your library won't load because the dependent php-font-lib(https://github.com/PhenX/php-font-lib) is php 5.3 only causing the following error. Is there a way to get it to work with php 5.2.

Parse error: syntax error, unexpected T_STRING in .. /dompdf/lib/php-font-lib/Font.php on line 9

**Comment by bsweeney** [comment]
Which version of dompdf and which version of php-font-lib. dompdf 0.6.x uses [php-font-lib 0.2.x](https://github.com/PhenX/php-font-lib/tree/0.2.2) which is compatible with php 5.0 (though I don't know that we specify that anywhere).

If you're downloading the code instead of using composer it's easier to grab an [packaged copy of the release](https://github.com/dompdf/dompdf/releases/download/v0.6.1/dompdf-0.6.1.zip).
